from pathlib import Path
from PIL import Image
import json,hashlib,copy,importlib.util
P=Path(__file__).parent; ROOT=Path('/workspace/cqc-game-working/cqc-versus-v056')
def sha(b):return hashlib.sha256(b).hexdigest()
def canon(o):return sha(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode())
def write(n,o):
 q=P/n
 if q.exists():raise RuntimeError('Refusing existing output: '+str(q))
 q.parent.mkdir(parents=True,exist_ok=True);q.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n')
def source(file,url,material,authority,note):
 q=P/'references'/file
 return dict(url=url,path=str(q),sha256=sha(q.read_bytes()),bytes=q.stat().st_size,material=material,authority=authority,originNote=note,physicallyViewed=True)
runner=source('running-man-msx2-original-sprite.webp','https://thecodex.wiki/images/3/35/Running_Man.webp','game_sprite','official_material_mirror','Extracted small original1990 MSX2 Running Man game sprite mirrored by The Codex: green trousers/forearms, light grey upper shoulder areas, dark/ochre head and ochre/dark boot pixels. Physically compared with original R.MAN game captures. Tiny source cannot establish realistic face, hair style, headwear, upper tailoring or boot model; these are physically occluded or silhouette in accepted scenes. Hosting-page fan power/combat statistics are excluded entirely.')
red=source('red-blaster-msx2-original-sprite.webp','https://thecodex.wiki/images/d/d0/Red_Blaster.webp','game_sprite','official_material_mirror','Extracted original1990 MSX2 Red Blaster game sprite mirrored by The Codex: extremely small green human body with dark/ochre extremities, rather than literal red military costume. No fine face, hair, equipment or gun model discernable. Original gameplay RED-B scenes independently match body palette. Hosting-page fan interpretation excluded.')
refs={}
for uid,names,part in [('core__runner_mg2',['24-Metal_Gear_2_0281.png','27-Metal_Gear_2_0287.png'],23),('core__redblaster_mg2',['30-Metal_Gear_2_0470.png','33-Metal_Gear_2_0471.png','34-Metal_Gear_2_0479.png'],26)]:
 refs[uid]=[source(f'lp{part}-'+n,f'https://lparchive.org/Metal-Gear-1-2/Update%20{part}/'+n,'game_screenshot','game_capture',('Original1990 MSX2 R.MAN named boss capture: green trousers and pale-grey/green upper palette, grey tiled industrial room with vents. Original gas/danger mechanic is NOT rendered as gas in the alternate story which explicitly replaces it by a limit lamp.' if part==23 else 'Original1990 MSX2 RED-B game capture: small green opponent on elevated dark gallery, olive-yellow ribbed industrial walls, grey/olive tiled floor and elevator. Original dialogue names grenades, and crossed white immobilizing tripwire lines are visible. HUD weapon icon belongs to player Snake, never misattributed to Red Blaster. Source pixels cannot establish exact grenade or launcher model.')) for n in names]
manual=source('original1990-msx2-japanese-manual-text.pdf','https://archive.org/download/metal-gear-2-solid-snake-manual-original/MetalGear%202%20-%20SolidSnake%20Manual%20%28Original%29_text.pdf','game_manual','official_material_mirror','Saved scan of original1990 Japanese MSX2 Metal Gear2 manual, not later Subsistence guide. Printed page42 physically rendered and viewed in manual-original1990-page42.png: Running Man former Olympic sprinter/doping/mercenary/traps; Red Blaster SPETSNAZ explosive sabotage and grenade mastery. Original text provides no detailed boss portrait, clothing or exact grenade/launcher model. Page rendering is reference inspection only, not alteration of any generated PNG.')
allcanon=[runner,red,*refs['core__runner_mg2'],*refs['core__redblaster_mg2'],manual]
write('SOURCE_REFERENCE_MANIFEST.json',dict(schema='cqc.external-canonical-reference-selection/1',reviewDate='2026-10-02',fidelityTarget='1:1',absolute1to1Certified=False,sources=allcanon,manualPageInspection=dict(path=str(P/'references/manual-original1990-page42.png'),sha256=sha((P/'references/manual-original1990-page42.png').read_bytes()),physicallyViewed=True),sourceNotes=['The Codex saved game-sprite pixels are evidence; its fan-analysis statistics never used.','LPArchive index/source contains original MSX2 R.MAN/RED-B names, before later rerelease portrayals; original manual corroborates original identities.','Original codec transcription in lp-update-26.html says grenade launcher and immobilizing crossed traps. Its portrait GIF alone is not proof of that text. Exact launcher model is unknown and not painted.','Original LP Red Blaster video request failed proxy403; untouched failure log/empty metadata preserved, no claimed inspection or source timing invented.','All scene expanded architecture, floor plans, electronics, training opponents, storage and ordinary interpretation of small grenade hardware follow already existing alternate CQC stories, not newly official lore.']))
chosen={}
for slug in ['running-man','red-blaster']:
 for phase in ['intro','outro']:
  for i in range(1,4):
   b=f'{slug}-{phase}-{i:02}';chosen[b]=b
for b in ['running-man-intro-02','running-man-intro-03','running-man-outro-02','running-man-outro-03','red-blaster-intro-02','red-blaster-outro-03']:chosen[b]=b+'-v2'
notes={
'running-man-intro-01':'Face-free close crop, one ordinary finger traces worn start line, green trouser knee, pale-grey/green sleeve, second supporting hand and unmarked analogue stopwatch. No helmet/medal inferred from prop token. Cloth mottling/boot trim are declared interpretation.',
'running-man-intro-02':'Exactly8 adult anonymous training opponents counted separately from main actor: four back-row and four front-row figures. Main head/hair physically concealed by extended left pillar in final V2. Amber limit lamp, clear air, absolutely no active poison gas. Opponent clothes/translucency are authored training interpretation.',
'running-man-intro-03':'Oblique overhead actual first corner with one waiting anonymous adversary; main slows mid-stride. Generated overhead beam hides main head/hair completely in final V2. No weapon, gas or extra opponents.',
'running-man-outro-01':'Face-free close left crop with main hand/green trouser/pale-grey shoulder, intact analogue stopwatch and blurred unlabelled screen, quiet finish floor. No medal or victory crowd painted.',
'running-man-outro-02':'Narrow service door opens to visibly uneven empty corridor; original grey circuit behind. V2 door edge occludes head/hair fully. Slow walking rather than sprinting; key is ordinary narrative object, no public.',
'running-man-outro-03':'Single running human rear silhouette on bare uneven inland earth below continental hills, old industrial circuit behind. Final V2 all body/head details in complete dark silhouette. Native output1672x940 unchanged, no resizing to force requested941.',
'red-blaster-intro-01':'Overhead left planning table, natural hands with overlapping circle contours and a path; exactly one anonymous listening soldier as cropped shoulder. Main face/head cropped/obscured, no gun. Suspended olive-yellow industrial architecture tied to original room family.',
'red-blaster-intro-02':'Exactly8 anonymous training opponents counted separately from main: four in left cluster and four in right. V2 near hanging support fully conceals main head/hair. Small dropped conventional grenade, green clothes and upper gallery; no rifle despite preserved prop metadata token.',
'red-blaster-intro-03':'Main green sleeve/human hand holds one small grenade back behind pillar; head/face outside crop. Exactly one distant anonymous opponent moves in protected strip. No C4/remote trigger, pistol, rifle, rollers, explosion or gas.',
'red-blaster-outro-01':'Oblique overhead aftermath: main green figure walks a continuous undamaged tiled strip between exits; impacts and thin smoke flank it. Head unreadable in shadow/distance, no assertive portrait. No active explosion or victims.',
'red-blaster-outro-02':'Main face-free hand crop corrects plain circles and arrows; exactly one young adult anonymous novice carries one crate through protected floor in background. Blank book, no gun. Extra novice details authored training only.',
'red-blaster-outro-03':'Main hand returns one unused conventional grenade into storage; room with continuous intact band beyond. Final V2 foreground pipe physically hides main head/hair/face. No concluding explosive effect or extra character.'}
limitations=[
'1:1 remains target; these realistic paintings interpret tiny original1990 MSX2 sprite/capture pixels and do not certify absolute equivalence. Unsupported main face/head/hair identities are cropped, physically occluded or silhouettes. Fine cloth texture, folds, camouflage-like painterly mottling, seams, belt/webbing, boot trim and skin tone are closest-supported rendering, not individually confirmed original costume details.',
'Running Man source supports broad green/pale-grey/ochre sprite palette and sprinting/gas arena; alternate story explicitly replaces gas by limit signal. Paintings preserve that existing simulation text. Medal/helmet/glove tokens never establish original worn equipment and are not automatically painted.',
'Red Blaster source confirms conventional grenade/explosive expertise and room traps. Original codec transcription says grenade launcher; no exact realistic launcher or grenade model visually established. Generic small green/dark grenade form, pin/spoon/segmentation visible in some narrative paintings is artistic category interpretation, not a named canon-certified real-world model. No rifle/pistol/rollers/remote C4 equipment inferred from inherited metadata.',
'All training opponents, service door/rough passage, inland exterior, stopwatch/screen/map/book/crate/storage, precise expanded room structures, light/camera and authored events follow existing alternative CQC stories. They are not asserted official MG2 events or exact original room topology. Each of the two8-opponent pictures contains8 opponents plus the separate main actor.',
'Imagegen only exposes prompt aspect/size request; accepted PNGs are native1672x941 except Running Man outro3 native1672x940. Every accepted/rejected original byte is retained unchanged: no raster resize, crop, retouch or recompression.']
items=[];snapshots=[];data=json.loads((ROOT/'data/chronicles-v056.json').read_text())
for uid,slug in [('core__runner_mg2','running-man'),('core__redblaster_mg2','red-blaster')]:
 snap=json.loads((P/(uid+'-snapshot.json')).read_text());story=snap['story'];f=snap['fighter'];assert data['stories'][uid]==story
 snapshots.append(dict(uid=uid,snapshotPath=str(P/(uid+'-snapshot.json')),snapshotFileSha256=sha((P/(uid+'-snapshot.json')).read_bytes()),canonicalJsonSha256=canon(story),routeSha256=canon(story['route']),metadataSha256=canon({k:v for k,v in story.items() if k not in ('intro','outro','route')}),sourceCurrentStoryEqualBeforeImport=True,status=story['status'],evidence=story['evidence'],routeOpponents=[r['opponent'] for r in story['route']]))
 sources=[runner if slug=='running-man' else red,*refs[uid],manual];urls=[s['url'] for s in sources]
 for phase in ['intro','outro']:
  for i,s in enumerate(story[phase]):
   base=f'{slug}-{phase}-{i+1:02}';job=chosen[base];r=json.loads((P/'jobs'/(job+'.result.json')).read_text());a=json.loads((P/'jobs'/(job+'.args.json')).read_text());q=Path(r['preservedPath']);assert sha(q.read_bytes())==r['sha256']
   scene=dict(key=f'{uid}:{phase}:{i}',uid=uid,phase=phase,index=i,title=s['title'],place=s['place'],camera=s['camera'],propRawUnchanged=s['prop'],stage=s['stage'],focus=s['focus'],text=s['text'],paragraphs=s['paragraphs'],sceneSource=copy.deepcopy(s),currentVisual=copy.deepcopy(s['visual']),needsFullScenePainting=True)
   ident='mg2-msx2-'+slug.replace('-','')+f'-{phase}-{i+1:02}'
   review=dict(status='accepted',fidelityTarget='1:1',fidelityResult='closest_supported',absolute1to1Certified=False,reviewer='pass6_narratives / physically inspected original MSX2 evidence',physicalReviewDate='2026-10-02',physicallyViewed=True,limitations=limitations,incarnation=dict(uid=uid,episode=f['ep']),sources=copy.deepcopy(sources),checks={
    'character':dict(status='accepted',sourceUrls=[urls[0]],notes=f'Exact original1990 UID {uid}; no unsupported realistic main face/hair portrait. '+notes[base]),
    'costume':dict(status='accepted',sourceUrls=[urls[0],urls[1]],notes=('Original Running Man broad green trousers/arms and pale grey upper areas; tiny original sprite cannot establish actual realistic tailoring. No modern tactical redesign. ' if slug=='running-man' else 'Original Red Blaster green cloth palette rather than literal-red Fatman suit. No rollers, plate armor or weapon belt model claimed. ')+limitations[0]),
    'weapons':dict(status='accepted',sourceUrls=[urls[0],urls[-1]],notes=('Main Running Man has no hand-held gun or weapon in any painting; sprinting/gas/trap category contextual only, alternate scene never paints real gas.' if slug=='running-man' else 'Only conventional small grenade category in narrative; exact grenade pin/spoon/segmentation interpretation not named original model. Source codec launcher category retained as evidence, no modern launcher model painted. No rifle/pistol/C4 remote/roller equipment.')),
    'stage':dict(status='accepted',sourceUrls=urls[1:-1],notes=('Original grey tiled closed track, vents and ordinary industrial architecture family; existing story expands circuit/service corridor/continental exterior, not literal original screen map.' if slug=='running-man' else 'Original upper dark gallery, olive-yellow ribbed walls, grey/olive tiled floor/elevator and crossed traps; alternate story expands into suspended training structures, planning/storage and aftermath, not official new stage.')),
    'lore':dict(status='accepted',sourceUrls=[urls[-1],urls[1]],notes=('Original manual identifies sprinter turned mercenary, original gas race; existing8-duel alternate story explicitly changes gas to harmless limit signal, no invented canonical sequel.' if slug=='running-man' else 'Original manual identifies SPETSNAZ/explosive sabotage/grenade expert. Existing8-duel authored story preserves terrain control and intact route, no supernatural explosions or invented canonical sequence.'))})
   prompt=json.loads((P/'jobs'/(base+'.args.json')).read_text())['prompt']
   if job!=base:prompt+='\nFINAL NATIVE IMAGEGEN EDIT: '+a['prompt']
   items.append(dict(id=ident,sceneKey=scene['key'],uid=uid,phase=phase,index=i,title=s['title'],place=s['place'],camera=s['camera'],prop=s['prop'],stage=s['stage'],focus=s['focus'],storyTextSha256=sha(s['text'].encode()),sourceSceneSnapshot=scene,prompt=prompt,promptSource=str(P/'jobs'/(base+'.args.json')),finalEditPromptSource=str(P/'jobs'/(job+'.args.json')) if job!=base else None,referencePaths=[x['path'] for x in sources],sourcePath=r['sourcePath'],file=q.relative_to(P).as_posix(),sha256=r['sha256'],bytes=r['bytes'],width=r['width'],height=r['height'],approved=True,qaStatus='accepted_closest_supported_original_msx2_external_source_review',generationTool='image_gen__imagegen',generationJob=job,nativeBytesPreserved=True,reviewNotes=notes[base],canonicalReview=review))
results=[json.loads(f.read_text()) for f in sorted((P/'jobs').glob('*.result.json'))];assert len(results)==18
approved=set(chosen.values());reject={b:'Unsupported visible main hair/head/costume details; superseded by imagegen physical occlusion or final complete silhouette as appropriate.' for b,j in chosen.items() if b!=j}
assert set(r['job'] for r in results)-approved==set(reject)
for r in results:
 r.update(accepted=r['job'] in approved,physicallyViewed=True,reviewVerdict=notes[next(b for b,j in chosen.items() if j==r['job'])] if r['job'] in approved else reject[r['job']]);assert sha(Path(r['sourcePath']).read_bytes())==r['sha256']==sha(Path(r['preservedPath']).read_bytes())
write('NATIVE_ATTEMPTS_PRESERVATION.json',dict(schema='cqc.native-image-generation-preservation/1',generatedAttempts=18,acceptedNativeOutputs=12,rejectedAttempts=6,allNativeBytesPreserved=True,attempts=results))
manifest=dict(schema='cqc.approved-narrative-manifest/1',batch='reprise-pass6-mg2-msx2-narratives-2026-10-02',reviewer='pass6_narratives',reviewDate='2026-10-02',assets=items,nativeGenerationAttempts=18,acceptedNativeOutputs=12,rejectedAttempts=6,preservationManifest='NATIVE_ATTEMPTS_PRESERVATION.json',sourceStorySnapshots=snapshots,fidelityTarget='1:1',absolute1to1Certified=False,notes=['Exactly12 independent native full-scene paintings:6Running Man and6Red Blaster. No portraits altered.','All external original sprites/captures/manual PDF/page rendered and physically viewed; URLs/SHA and explicit limitations saved.','Raw existing text/paragraph/title/place/prop/camera/stage/focus/8-route data unchanged, only future approved visual mapping importer owned by root.','All18native generatedPNG including6rejected preserved byte exact. Narrative grenade form artistic interpretation; no named model certification.','Artist writes isolated delivery folder only; root owns production copy/import.'])
write('APPROVED_NARRATIVE_MANIFEST.json',manifest);write('IMPORT_READY_MANIFEST.json',manifest)
spec=importlib.util.spec_from_file_location('importer',ROOT/'tools/reprise/integrate_cqc_reprise.py');mod=importlib.util.module_from_spec(spec);spec.loader.exec_module(mod)
plan,report=mod.build_plan(ROOT,P/'IMPORT_READY_MANIFEST.json');write('READONLY_IMPORT_PLAN.json',report)
write('FINAL_NARRATIVE_QA.json',dict(status='passed',acceptedScenes=12,generatedAttempts=18,rejectedAttemptsPreserved=6,uniqueAcceptedHashes=len(set(i['sha256'] for i in items)),nativeDimensions={f"{i['width']}x{i['height']}":sum(x['width']==i['width'] and x['height']==i['height'] for x in items) for i in items},allNativeByteExact=True,all12PhysicallyViewed=True,all18AttemptsPhysicallyViewed=True,existingNarrativeAndRoutesUnchanged=True,sourceSnapshots=snapshots,noProductionWrites=True,noPortraitWrites=True,readOnlyImporterPlanPassed=True,importPlanReportPath='READONLY_IMPORT_PLAN.json',canonicalResult='closest_supported',absolute1to1Certified=False,notes=['Both8opponent pictures each count8separate opponents plus main actor.','All unsupported main visible head/hair traits hidden by actual native imagegen edits or final dark silhouette; earlier6attempts preserved rejected.','Red Blaster grenade model/hardware fine detail remains category interpretation; no precise source timing proof or launcher model claimed.']))
files=[dict(path=f.relative_to(P).as_posix(),bytes=f.stat().st_size,sha256=sha(f.read_bytes())) for f in sorted(P.rglob('*')) if f.is_file()]
write('DELIVERY_FILE_SHA256_MANIFEST.json',dict(schema='cqc.source-delivery-sha256/1',fileCount=len(files),files=files))
print(json.dumps(dict(accepted=12,attempts=18,rejected=6,importReport=report,manifestSha256=sha((P/'APPROVED_NARRATIVE_MANIFEST.json').read_bytes()),totalNativeBytes=sum(r['bytes'] for r in results)),ensure_ascii=False,indent=2))
