from pathlib import Path
import json
P=Path(__file__).parent
base='''Create ONE complete, independent cinematic narrative painting, landscape 16:9 about 1672x941 pixels. One continuous realistic hand-painted 1990s espionage concept-art scene, subtle brush texture, restrained green/ochre/grey industrial palette. Main gestures and actors concentrated LEFT 55 percent; RIGHT 45 percent continues the SAME environment with quiet lower contrast for narration. NO letters, words, numbers, subtitles, HUD, panels, collage, borders, logos, luminous magic or anachronistic modern tactical redesign. Attached original MSX2 sprite and original1990 game captures are evidence, NOT a request to paint their pixels or embedded text. Realistic reinterpretation follows tiny source broad clothing palette, never invents an identifiable face, exact armor, gas mask, headwear, gun model or named equipment. This scene is explicitly an ALTERNATE CQC simulation using original Metal Gear2: Solid Snake 1990 MSX2 identity; these events/expanded architecture are NOT asserted as official canon. Zanzibar Land is inland Central Asia: no ocean, palm trees or coast. Anatomically plausible humans and period objects. Do not put any gun in the main actor's hands. Do NOT render any words from this preserved scene text: '''
descs={
'running-man-intro-01':'''CLOSE ground-level view of one ordinary human finger tracing a worn pale start line on a grey industrial floor at LEFT. Crouched Running Man almost entirely cropped out: show ONE hand and green trouser knee only, head/face/hair/upper costume outside frame. His other hand supports him naturally, no glove asserted. Worn repeated shoe marks converge at that exact patch. A small old unmarked stopwatch, its face blurred and no readable digits, lies beside the line. Closed grey metal track hall with ribbed walls continues into quiet RIGHT. No soldier, medal, helmet, audience or weapon.''',
'running-man-intro-02':'''WIDE closed industrial simulation running circuit grounded in original grey tiled MSX2 room, ventilation ducts above. One main runner at FAR LEFT in a ready stance, head fully obscured behind nearer duct support, green trousers and pale grey upper-body glimpse consistent with tiny original sprite, no detailed face or gear. EXACTLY EIGHT separate anonymous adult opponents in background LEFT and MIDDLE: two ranks of FOUR, every entire silhouette visible and individually separated; subtle transparent training projections, not eight extra Running Men. No ninth opponent, guard or audience. A single simple amber limit lamp beside ceiling ventilation signifies simulated limit, clean ordinary breathable air, absolutely NO poisonous gas, smoke cloud or respirator. Rightmost45 percent quiet same empty room.''',
'running-man-intro-03':'''OBLIQUE OVERHEAD camera at first hard right-angle corner of grey tiled enclosed industrial running track. Main Running Man enters at LEFT with planted foot and body subtly slowing mid-stride, green trousers and restrained pale grey upper garment, head face hidden by overhead beam and angle. Exactly ONE anonymous adult training opponent waits calmly at next corner MIDDLE LEFT, rather than chasing him. No other people or weapons. Physical bend in corridor clearly shows predicted next pass; no drawn map, arrows or projected path. Empty track continuation at RIGHT. No gas.''',
'running-man-outro-01':'''CLOSE arrival after the exercise: main runner's relaxed open hand and green trouser knee at LEFT beside an intact small old unmarked stopwatch and softly blurred timing screen, NO legible digits or letters. His face, hair, upper tailoring and headwear completely outside crop. Visible body language pause instead of celebration. Scuffed pale finish line across grey tiled floor. Two short quiet reflected lamps, expanded empty grey track continues at RIGHT. No medal, helmet, audience or opponents; timing equipment natural period electronics.''',
'running-man-outro-02':'''PROFILE corridor scene, one main Running Man at LEFT seen from back with head hidden behind the opening thick industrial door jamb, one hand opens a narrow old steel SIDE service door. Show green trousers and pale grey upper-body only, feet simply walking slowly on uneven stone/concrete floor. No speed blur or sprinting, no guards or spectators. Interior grey tiled circuit behind him contrasts with short rough dim service passage ahead. A tiny ordinary key remains in old lock if visible, no close complex design. RIGHT continues quiet empty rough corridor.''',
'running-man-outro-03':'''LONG rear SILHOUETTE shot: one lone lean human runner at FAR LEFT leaving a dim square industrial complex doorway and accelerating onto bare inland earth, small stones and naturally curved track, distant continental dry hills. Main completely silhouetted, no face, headwear, gun, fantasy motion trail or exact garments asserted. Show actual uneven terrain forcing slight natural turn. Quiet dawn greys and muted olive slopes. Closed track remains behind as distant unmarked door only, no timer signal. No ocean or palm trees. RIGHT calm open ground/hills.''',
'red-blaster-intro-01':'''OBLIQUE OVERHEAD close left-side planning table in old olive-yellow industrial room with overhead suspended platforms grounded in original MG2 boss room. Main Red Blaster's two green sleeves and hands only: one hand draws overlapping plain circular pencil contours on a physical floor plan; other points at a preserved path crossing a circle. No text, letters or numbered labels on map. Face/head/hair hidden completely by hanging beam and camera crop. Exactly ONE ordinary soldier at left edge listening, seen shoulder/hand only, not a named character. Neither holds a gun. Green cloth, no modern armor. Quiet RIGHT continues platform shadows and empty room.''',
'red-blaster-intro-02':'''WIDE suspended-structure industrial training room: olive-yellow ribbed walls, grey/olive tiled floor, high dark suspended gallery at left. Main Red Blaster at FAR LEFT in green cloth, head wholly shadowed behind gallery rail; one ordinary small grenade lying/rolling on floor just below his low empty hand, no active explosion. EXACTLY EIGHT separate anonymous adult training opponents in background LEFT/MIDDLE, in two groups of FOUR, every silhouette fully visible and separated, faint transparent projections of ordinary humans; NO ninth opponent. No one has visible gun. Retain a clear band of safe floor and distant plain door. No rifle even though old metadata token says rifle. Grenade must remain small conventional non-glowing object, no asserted real-world model. Quiet RIGHT45 percent same room.''',
'red-blaster-intro-03':'''PROFILE at an industrial room corner: main Red Blaster at LEFT almost entirely obscured behind a thick olive-yellow pillar, green sleeve and ordinary hand visible holding back a SINGLE small dark conventional grenade rather than throwing it. His head and face completely hidden. Exactly ONE anonymous distant adult opponent chooses a farther foot placement at MIDDLE LEFT. Clear intact narrow band of floor next to wall deliberately spared; NO explosion, smoke, muzzle flash, gun, C4, remote detonator or roller skates. Grounded olive-yellow ribbed wall, grey floor and suspended gallery; RIGHT quiet intact floor.''',
'red-blaster-outro-01':'''OBLIQUE OVERHEAD aftermath of industrial training-room demolition: one green-clothed main Red Blaster at LEFT walking deliberately along a narrow perfectly INTACT strip of tiled floor that visibly connects two plain exits. Head completely shadowed by overhead beam, no face or headwear. Black soot/impact craters flank both sides of safe strip, restrained thin residual smoke near damaged tiles, no active blast or bodies. No other people. The strip is continuous and passable, NOT broken. Original olive-yellow ribbed walls, suspended walkway geometry. Quiet RIGHT continues room and safe strip.''',
'red-blaster-outro-02':'''CLOSE planning-table scene, main Red Blaster's green sleeves and hands only at LEFT revises plain circle contours plus short directional arrows on paper floor plan, without ANY labels, numbers or lettering. Face/head/boots outside crop. Precisely ONE young adult novice seen in profile silhouette in LEFT BACKGROUND carries a modest wooden supply crate through intact band of room floor, his face deliberately unseen and no weapon. Story is authored training, not new canonical character. Table holds pencil, CLOSED ordinary blank book, no gun or C4/remote. Original olive-yellow room, RIGHT quiet wall/table extension.''',
'red-blaster-outro-03':'''REAR SILHOUETTE close-mid shot at old industrial complex exit/storage: main Red Blaster at FAR LEFT, face/hair/head details wholly dark and obscured by overhead doorway. He places ONE small dark conventional grenade from his equipment into open simple storage tray with his ordinary human hand. Grenade not exploding, no triumph explosion or effect; green sleeves very subtly visible. Through door in MIDDLE LEFT a marked training room with one intact passable band of floor remains visible, no bodies or opponents. No rifle, pistol, launcher model, remote detonator, C4, futuristic gadget or rollers. RIGHT same quiet olive-yellow wall.'''
}
for uid,slug in [('core__runner_mg2','running-man'),('core__redblaster_mg2','red-blaster')]:
 s=json.loads((P/(uid+'-snapshot.json')).read_text())['story']
 ident='Running Man: original sprite broadly green trousers, pale grey shoulder/upper-body areas and small dark human head; original pixels cannot establish a realistic face or precise upper tailoring. No modern military redesign or helmet. ' if slug=='running-man' else 'Red Blaster: original sprite is green cloth and a tiny dark/ochre human head, not a red modern suit. Original room upper dark gallery/olive-yellow industrial walls. Original weapon category grenades (codec also says grenade launcher); no particular model established, no pistol/rifle/roller skates or remote C4 identity. '
 refs=['running-man-msx2-original-sprite.webp','lp23-24-Metal_Gear_2_0281.png','lp23-27-Metal_Gear_2_0287.png'] if slug=='running-man' else ['red-blaster-msx2-original-sprite.webp','lp26-30-Metal_Gear_2_0470.png','lp26-33-Metal_Gear_2_0471.png']
 for phase in ['intro','outro']:
  for i,sc in enumerate(s[phase]):
   job=f'{slug}-{phase}-{i+1:02}'
   prompt=base+sc['title']+' — '+sc['place']+'. '+sc['text']+'\nSOURCE IDENTITY LIMITS: '+ident+'\nCOMPOSITION AND EXACT MOMENT: '+descs[job]
   args={'prompt':prompt,'referenced_image_paths':[str(P/'references'/n) for n in refs],'transparent_background':False}
   (P/'jobs'/(job+'.args.json')).write_text(json.dumps(args,ensure_ascii=False,indent=2)+'\n')
print('Prepared12 narrative imagegen jobs; production unchanged.')
