from pathlib import Path
from PIL import Image
import hashlib,json

B=Path(__file__).parent
UID='core__raven'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(name,data):
 p=B/name;p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');return str(p)

selected={'a-right':'A_RIGHT_01','a-left':'A_LEFT_02','b-right':'B_RIGHT_01','b-left':'B_LEFT_02','c-right':'C_RIGHT_02','c-left':'C_LEFT_02'}
body=json.loads((B/'BODY_GROUND_PIVOTS.json').read_text())
source_rows=[]
for key,name in selected.items():
 p=B/'native-attempts'/(name+'.png');im=Image.open(p);meta=json.loads((B/'metadata'/(name+'.result-summary.json')).read_text());inspection=json.loads((B/'inspections'/(name+'.components.json')).read_text())
 assert sha(p)==sha(meta['nativeOriginal'])
 source_rows.append({'source':str(p),'nativeOriginal':meta['nativeOriginal'],'sha256':sha(p),'bytes':p.stat().st_size,'width':im.width,'height':im.height,'key':key,'columns':4,'rows':3,'poseCount':12,'facing':1 if key.endswith('right') else -1,'mirror':False,'inspection':str(B/'inspections'/(name+'.components.json')),'layout':str(B/'layouts'/(key+'.json')),'observedBodyHeights':[c['rect'][3]for c in inspection['components']],'standingSourceHeight':body['standingSourceHeights'][key],'observedBodyPivots':body['observedBodyPivots'][key],'completeCanvasContact':str(B/'inspections'/('Canvas-complete-'+key+'.png'))})

video='https://archive.org/download/PSXLongplay001MetalGearSolid/PSX_Longplay_001_Metal_Gear_Solid.mp4'
refs=[]
for name,url,kind,role in [
 ('ch09_body.jpg','https://www.konami.com/mg/archive/mgs/character/images/ch09_body.jpg','official-art-reference','Konami original Shinkawa MGS1 concept: enormously muscular bare torso/arms, harness, olive trousers, boots and enormous carried cannon. Cropped gun/rear details are not orthographic geometry or exact PS1 palette.'),
 ('ch09_face.jpg','https://www.konami.com/mg/archive/mgs/character/images/ch09_face.jpg','official-art-reference','Konami original Shinkawa MGS1 face: bald head, raven forehead/brow tattoo and broad stern human face. Exact PS1 texture coordinates and tattoo stroke widths not certified.'),
 ('ps1-raven-16840.png',video+'#t=16840','original-game-capture','Original PS1 cutscene rear-side view: gigantic dark ribbed ammunition pack, crossbars, feed apparatus and shirtless upper arms. Front receiver obscured.'),
 ('ps1-raven-16880.png',video+'#t=16880','original-game-capture','Original PS1 front low-angle view: massively oversized waist-carried Vulcan cannon with squared cradle and long rotary barrel cluster, two-hand carrying stance, bald bare-torso Raven and dark harness.'),
 ('ps1-raven-17000.png',video+'#t=17000','original-game-capture','Original PS1 top-down warehouse boss: Raven walks with huge carried cannon. Small body and overhead viewpoint limit precise hand/texture geometry.'),
 ('ps1-raven-17200.png',video+'#t=17200','original-game-capture','Original PS1 post-boss body/pack silhouette and bare arm support reference. Wounded state and discarded cannon gesture excluded from ordinary costumes and attacks.'),
 ('ps1-raven-17220.png',video+'#t=17220','original-game-capture','Original PS1 post-boss frontal face, dark harness and massive ribbed pack. Blood/wounds excluded from all selected sheets. Obscured tattoo/palette not inferred from this frame.'),
]:
 p=B/'references'/name;im=Image.open(p);refs.append({'file':str(p),'url':url,'sourceKind':kind,'sha256':sha(p),'bytes':p.stat().st_size,'width':im.width,'height':im.height,'incarnation':'Metal Gear Solid (1998), original PlayStation polygon/model design','role':role,'viewed':True,'originNote':'Original low-polygon PS1 game visually identified in RickyC/worldoflongplays archive, metadata deposited2015. Emulated versus physical console framebuffer and calibrated color cannot be independently certified.' if kind=='original-game-capture' else 'Konami-hosted original game artwork, not Twin Snakes.'})

limits=[
 'Target is 1:1 original MGS1 1998 PlayStation Raven where evidence supports it. Native detailed 2D poses are new authored fighting-game artwork, not extracted PS1 sprites or a certified exact original mesh. Fidelity closest_supported; absolute1to1Certified false.',
 'Original bald muscular shirtless Raven with forehead raven tattoo, dark crossing military harness, olive cargo trousers, heavy boots, oversized rotary Vulcan cannon and huge rear ammunition pack/feed is supported by viewed original references. No Twin Snakes model, tactical jacket, ordinary assault rifle, pistol, Raging Raven armor or supernatural attack substituted.',
 'Publisher identifies aircraft Vulcan cannon category. Exact real-world model, barrel count, original PS1 receiver proportions, tiny harness seams, tattoo coordinates, wrist/boot texture and precise hidden reverse feed/grip geometry cannot be certified from these low-resolution views. Left/right native artwork independently reconstructs the same category of apparatus without claiming exact source orthographics.',
 'Cannon feed/cartridge palette, pack rib details and some outlines vary between independent A/B/C native sheets. Both-facing canonical identity/costume and gear category retained, but exact identical line/palette and every hardware fastener are not certified1:1. There are no runtime image mirrors or destructive image edits.',
 'All punches, gun-housing strikes, kicks, grapples, jumps, hit/KO, guards, low firing posture, body pivots and animation timing are authored existing Versus adaptation. Original boss evidence establishes carried cannon and walking/firing, not these CQC moves. Shaman/raven lore is not proof of summoned attacking birds, spirit beam, levitation or invulnerability; no such native effects added.',
 'Heat, cooling, resource costs, armor-brace and salvo counts are authored Versus balancing. FrameC5/6/7 is actual low kneeling horizontal cannon firing for specialForward; standing shoot is C2/3/4 and super is C10/11. Do not reuse standing shoot for low projectiles or claim low/cooling poses are source-extracted original mechanics.',
 'displayHeight260 and per-sheet standingSourceHeight are authored Canvas readability geometry, not original certified centimetres. Native human feet/body points separate carrier anchoring from very long gun/feed alpha centroid. LOW muzzle suggested world heights approx64left/70right, ordinary muzzle approx154/158 and super approx142/153 using original renderer scale1.12, subject to actual runtime verification.',
 'Every selected PNG has12 major isolated alpha>80 components and no opaque outer border. Low-alpha/hiddenRGB fringe pixels are retained intact. Some rectangular crops overlap neighboring body pixels; the unchanged historical component contour metadata must clip these at Canvas draw time, never rewrite the PNG.',
 'The viewer displayed hidden brown RGB underalpha0 on B_LEFT attempts. Full native alpha/components analysis and browser Canvas contacts confirmed background transparent. B_LEFT02 was valid and selected; B_LEFT03 removal tool attempt was unnecessary and is preserved unselected, not falsely claimed an opaque-source fix.',
 'First 1280-wide preview contacts clipped extended left hands/muzzles at diagnostic canvas border because body-centred cells were too narrow. These screenshots are preserved; later1600-wide complete contacts physically show all72 full poses, using same native PNG and historical contour crops. This was preview geometry only.',
 'Cannon nose direction stays original facing except the final incapacitated prone silhouette has its own authored lie-down orientation; the firearm is no longer aimed at a target inKO. Do not useKO as a firing origin.',
 'All reference seeks, failed requests, unselected scans, generation prompts/results and11native attempts are preserved. Scanned Snake, Liquid, codec and warehouse timeline frames are not canonical Raven proof. No complete movie downloaded.'
]
layout={
 'idle':{'sheet':'a','indices':[0,1],'fps':4,'loop':True},'walk':{'sheet':'a','indices':[2,3,4,5],'fps':8,'loop':True},'guard':{'sheet':'a','indices':[6,7],'fps':4,'loop':True},'crouch':{'sheet':'a','indices':[8,9],'fps':4,'loop':True},'jump':{'sheet':'a','indices':[10,11],'fps':5,'loop':False},
 'punch':{'sheet':'b','indices':[0,1,2],'fps':12,'loop':False},'heavy':{'sheet':'b','indices':[3,4,5],'fps':10,'loop':False},'low':{'sheet':'b','indices':[6,7,8],'fps':10,'loop':False},'hit':{'sheet':'b','indices':[9],'fps':0,'loop':False},'ko':{'sheet':'b','indices':[10,11],'fps':6,'loop':False},
 'throw':{'sheet':'c','indices':[0,1],'fps':9,'loop':False},'shoot':{'sheet':'c','indices':[2,3,4],'fps':10,'loop':False},'deploy':{'sheet':'c','indices':[5,6,7],'fps':10,'loop':False},'recover':{'sheet':'c','indices':[8,9],'fps':5,'loop':False},'charge':{'sheet':'c','indices':[10,11],'fps':9,'loop':False}}
slots={'light':'punch','heavy':'heavy','low':'low','throw':'throw','special':'shoot','specialDown':'heavy','specialForward':'deploy','specialBack':'guard','super':'charge','utility':'recover'}
phase={k:{'startup':[0],'active':[1],'recovery':[2]}for k in ['punch','heavy','low','shoot','deploy']}
phase.update({k:{'startup':[0],'active':[1],'recovery':[0]}for k in ['throw','charge','guard']})
phase['recover']={'startup':[0],'active':[1],'recovery':[1]};phase['walk']={'startup':[0],'active':[1,2],'recovery':[3]}
review={'uid':UID,'incarnation':'Original Metal Gear Solid1998PS1 Vulcan Raven, warehouse carried-cannon costume','status':'approved','reviewer':'pass7_raven_native / producer original-reference,11native and sixcompleteCanvas-contact physical review','reviewedAt':'2026-10-02','sourceKind':'original-game-capture','absolute1to1Certified':False,'fidelityStatus':'closest_supported','target':'1:1 originalPS1 incarnation where physically viewed source evidence supports it','checks':{'identity':True,'costume':True,'equipment':True,'anatomicalSides':True,'singleFigure':True,'transparentBackground':True},'sources':refs,'limits':limits,'sourcePriority':['Konami originalMGS1 character artwork/descriptions','Physically identified originalPS1 low-polygon gameplay/cutscenes','Independent new2D native poses, authored adaptation only'],'completeContacts':[str(B/'inspections'/('Canvas-complete-'+key+'.png'))for key in selected]}
write('CANONICAL_REVIEW.json',review)
marks={}
for side,groups in [('right',{'shoot':[1439,182],'deploy':[1089,633],'charge':[1438,888]}),('left',{'shoot':[1099,168],'deploy':[732,626],'charge':[1096,888]})]:
 row=next(x for x in source_rows if x['key']=='c-'+side);im=Image.open(row['source']);marks[side]={}
 for action,point in groups.items():
  idx={'shoot':3,'deploy':6,'charge':11}[action];rgba=list(im.getpixel(tuple(point)));assert rgba[3]>80
  ground=body['observedBodyPivots']['c-'+side][str(idx)];height=(ground[1]-point[1])/row['standingSourceHeight']*260*1.12
  marks[side][action]={'action':action,'frame':1,'sourcePoseIndex':idx,'file':'assets/combat-sprites/'+UID+'/c-'+side+'-v1.png','source':row['source'],'sha256':row['sha256'],'point':point,'pointRGBA':rgba,'bodyGroundPoint':ground,'suggestedWorldHeight':round(height,4),'note':'Physically viewed front muzzle edge of actual original-category rotary cannon, alpha>80. Authored Versus spawn geometry, not exact sourcePS1 muzzle coordinates. deploy is lowShoot group, never a planted device.'}
write('SOURCE_COMBAT_ORIGINS.json',{'uid':UID,'schema':'cqc.pass7.native-source-combat-marks/1','coordinateSystem':'Untouched native full-sheet PNG x,y, no resize/flip. frame is local action index; sourcePoseIndex full-sheet zero-based.','slotSourceGroups':{'special':'shoot','specialForward':'deploy','super':'charge'},'gameplayGroupToSourceAction':{'shoot':'shoot','lowShoot':'deploy','charge':'charge'},'marks':marks,'sourceIncarnation':'Original MGS1PS1 warehouse Raven, oversized carried Vulcan and ammunition pack'})
write('SOURCE_AND_ACTION_CONTRACT.json',{'uid':UID,'incarnation':'Original MGS1PlayStation1998','sourceBank':str(B/'CANONICAL_REVIEW.json'),'noRuntimeEdits':True,'actionLayout':layout,'actionMap':slots,'phaseMap':phase,'poseCount':72,'independentFacings':True,'mirror':False,'phaseSemantics':{'shoot':'standing cannon brace/actual muzzle aim/settle','deploy':'three actual low grounded horizontal cannon frames, source action for gameplay lowShoot/specialForward','charge':'upright cannon sustained-barrage windup/active','guard':'defensive cannon crossbody brace, authored armor-buff adaptation only','recover':'relaxed cooled pause, no missing scopes/gadgets added'},'excluded':['Unverified attacks with summoned ravens/spirit energy','MGS1TwinSnakes redesign','Canonical perfect heat/ammunition simulation','Hidden source geometry certified1:1']})

statuses={'A_RIGHT_01':'approved-final','A_LEFT_02':'approved-final','B_RIGHT_01':'approved-final','B_LEFT_02':'approved-final','C_RIGHT_02':'approved-final','C_LEFT_02':'approved-final','A_LEFT_01':'rejected-wrong-facing','B_LEFT_01':'rejected-mixed-facings','C_LEFT_01':'rejected-mixed-facings','C_RIGHT_01':'rejected-missing-low-fire-group','B_LEFT_03':'preserved-unselected-unnecessary-alpha-removal-variation'}
attempts=[]
for p in sorted((B/'native-attempts').glob('*.png')):
 m=json.loads((B/'metadata'/(p.stem+'.result-summary.json')).read_text());assert sha(p)==sha(m['nativeOriginal']);im=Image.open(p)
 attempts.append({'key':p.stem,'source':str(p),'nativeOriginal':m['nativeOriginal'],'sha256':sha(p),'bytes':p.stat().st_size,'width':im.width,'height':im.height,'status':statuses[p.stem],'physicallyViewed':True,'pixelEdit':False})
write('NATIVE_PNG_INDEX.json',{'uid':UID,'attempts':attempts,'nativeImages':11,'approvedBodySheets':6,'poses':72,'rejectedAttempts':4,'preservedUnselectedVariation':1,'requestValidationFailuresWithoutNative':4,'nativeBytesEdited':False})
selectedrefs={r['file']for r in refs}
write('REFERENCE_PRESERVATION_INDEX.json',{'uid':UID,'files':[{'file':str(p),'sha256':sha(p),'bytes':p.stat().st_size,'selectedCanonical':str(p)in selectedrefs,'note':'All raw searches/downloads/native seeks retained; unselected timeline scans not canonical proof.'}for p in sorted((B/'references').iterdir()) if p.is_file()],'totalBytes':sum(p.stat().st_size for p in (B/'references').iterdir() if p.is_file()),'canonicalSelectedImages':len(refs),'fullMoviesDownloaded':0,'selectedGameSeconds':[16840,16880,17000,17200,17220]})
producer={'uid':UID,'status':'approved','reviewer':review['reviewer'],'displayHeight':260,'sources':{r['key']:{'sha256':r['sha256'],'completeBodyAndWeaponViewed':True,'standingSourceHeight':r['standingSourceHeight'],'observedBodyPivots':r['observedBodyPivots'],'notes':['Twelve full isolated figures physically viewed at original sheet and completeCanvascontact.','Alpha/components and Canvas composition independently confirmed transparent background.','Per-sheet source standing height fixed; bodyfeet anchor independent of long cannon.']}for r in source_rows},'limits':limits,'spritePixelsModified':False,'completeContactsPhysicallyViewed':True,'ownedBrowserClosed':True,'ownedServerStopped':True,'browserSkill':'vercel:agent-browser and vercel:agent-browser-verify; owned session ravenp7, port9327'}
write('PRODUCER_VISUAL_REVIEW.json',producer)
delivery={'schema':'cqc.native-combat-delivery/1','uid':UID,'name':'VULCAN RAVEN','game':'Metal Gear Solid (1998)','incarnation':'Original MGS1PlayStation Vulcan Raven, warehouse carried-Vulcan costume','selectedCostume':'Bald raven forehead tattoo, massive bare torso/arms, dark crossing harness, olive cargo trousers, heavy boots, oversized rotary Vulcan, gigantic dark ammunition pack/feed','basis':'Original huge carried aircraft cannon and warehouse Raven silhouette; CQC normals, low firing, heat and armor are declared authored Versus adaptation, no supernatural combat imported.','displayHeight':260,'coverage':'action-frames','facing':1,'mirror':False,'sourceFiles':source_rows,'actionLayout':layout,'actionMap':slots,'phaseMap':phase,'review':review,'nativeSourceCombatOrigins':str(B/'SOURCE_COMBAT_ORIGINS.json'),'producerVisualReview':str(B/'PRODUCER_VISUAL_REVIEW.json'),'bodyGroundPivots':str(B/'BODY_GROUND_PIVOTS.json'),'limits':limits}
write('FINAL_DELIVERY.json',delivery)
print(json.dumps({'uid':UID,'selectedSources':6,'nativeAttempts':len(attempts),'poses':72,'referencesBytes':sum(p.stat().st_size for p in (B/'references').iterdir()if p.is_file()),'delivery':str(B/'FINAL_DELIVERY.json')},indent=2))
