#!/usr/bin/env python3
"""Produce source-only Old Snake delivery; no image edits or runtime mutations."""
from pathlib import Path
from PIL import Image
import hashlib,json,sys

B=Path(__file__).resolve().parent
UID='core__old_snake'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(name,data):
    p=B/name;p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');return str(p)

video='https://archive.org/download/PS3_Longplay_081_Metal_Gear_Solid_4/PS3_Longplay_081_Metal_Gear_Solid_4.mkv'
contract=json.loads((B/'references/source-contract.json').read_text())
refs=[]
for r in contract['references']:
    p=B/'references'/r['file']
    refs.append({'file':str(p),'url':r['url'],'sha256':sha(p),'bytes':p.stat().st_size,'sourceKind':'official-game-reference','viewed':True,'scope':contract['physical_inspection']['notes'][{'konami-mgs4-ps3-screenshot-01.jpg':'01','konami-mgs4-ps3-screenshot-03.jpg':'03','konami-mgs4-ps3-screenshot-04.jpg':'04','konami-mgs4-archive-key-art.jpg':'key_art'}[r['file']]]})
captures={900:'Original full body frontal costume, fitted segmented gray OctoCamo, tan harness/pouches, black gloves and dark lower-shin boots. Original asymmetrical equipment and elderly face.',1880:'Original side crouch before receiving equipment, boot/toe geometry and opaque surface-pattern OctoCamo; small Mk.II robot is shown as a separate device, not the pistol.',1975:'Original frontal close-up with broad gray moustache, gray hair, bandana and black Solid Eye over anatomical LEFT eye; optic is not a black patch on right eye.',2000:'Original Mk.II robot hands Snake a long black handgun with cylindrical suppressor/barrel; right glove on grip, visible side silhouette. Exact manufacturer engraving and internal gun anatomy not certified.',2100:'Original gameplay HUD reads MK.2 PISTOL and NON-LETHAL, confirming the selected gun category and supported sleep intent; body is opaque camouflaged prone, no supernatural invisibility.',32000:'Original gameplay HUD reads CHAFF G. with count1 and vertical rectangular cyan silhouette. Confirms item/loadout and rough silhouette, NOT physical color, detailed fuze geometry, electronic effect or explosion behavior.',32004:'Original gameplay over-shoulder view with CHAFF G. still selected and visible aimed throw trajectory; NV filter obscures physical body/weapon colors. This is a physical throw reference, no chaff effect is certified here.'}
for seconds,note in captures.items():
    p=B/'references'/f'original-ps3-frame-{seconds:05d}s.png';im=Image.open(p)
    refs.append({'file':str(p),'url':video+'#t='+str(seconds),'sha256':sha(p),'bytes':p.stat().st_size,'width':im.width,'height':im.height,'sourceKind':'original-game-capture','viewed':True,'timeSeconds':seconds,'scope':note,'captureMethod':'Remote ffmpeg single native1280x720 PS3 longplay frame, no resize/recolor/image editing and no full video download. Source metadata identifies PS3 original recording deposited2014; hardware framebuffer extraction itself is not independently certified.'})

limits=[
 'Target is original2008 PS3 MGS4 Old Snake with base gray OctoCamo, bandana and anatomicalLEFT Solid Eye. This is authored detailed 2D combat art and Versus animation, not original PS3 model extraction or absolute1:1 certification. fidelityStatus=closest_supported; original references outrank generated design consistency sheets.',
 'Primary Konami screenshots establish fitted segmented gray suit, tan webbing, gloves and left-eye optic; original PS3 fullbody frame900 supplies lower legs and dark boots. Fine pouch counts, hidden harness joins, holster underside, exact seams, stitching and laces are partly interpreted. No numeric count or hidden-side model geometry is certified.',
 'Both orientations are generated independently, mirror=false. ScreenRIGHT exposes bare near anatomicalRIGHT eye; Solid Eye stays on far anatomicalLEFT side and can be hidden. ScreenLEFT exposes the electronic left-eye lens. Rejected A_RIGHT_01 risked a near/right-eye optic and is retained, never approved or repurposed as an OC.',
 'The gray moustache is retained but its fine hair density and width vary slightly among small generated poses; elderly face/moustache, no beard, original hair and nape remain. Illustration contour/material rendering cannot be pixel-identical to PS3 low-resolution rasterization.',
 'Original Mk.2 Pistol loadout, long dark cylindrical suppressor shape and NON-LETHAL HUD are supported by original frames2000/2100. Tiny engraving, exact rear sight, magazine/bolt topology and finger contact are not certified. No manufacturer/model beyond original-game MK.2 PISTOL is asserted. Original weapon fired/held by right glove with left support, overlapping support fingers can be occluded.',
 'CH​AFF G. existence, rectangular HUD silhouette and physical throw arc are source supported at32000/32004. Cyan HUD is NOT physical color evidence. Small dark rectangular canister with short top fitting in C5/C6 is closest-supported authored readability interpretation; precise physical color/fuze/details and source electronic effect remain unresolved by these images. No frag sphere, detonation, smoke or damage effect is drawn. Root owns electronic Versus behavior and any separate prop.',
 'C7 is a self equipment-check gesture, never an offensive eye laser, hard target lock or psychic attack. On screenRIGHT the near eye stays bare, but occluded far-side exact fingertip-to-optic contact cannot be certified; this drawing establishes a self checking gesture only.',
 'OctoCamo source changes opaque surface material/pattern in original gameplay; transparent cloak/invisibility is not supported. These native gray body sheets remain opaque body illustration; runtime camo tint/pattern and balanced duration are root-owned authored adaptations, not a source1:1 animation claim.',
 'CQC jab/elbow/sweep/grab/charge, walk/guard/crouch/jump, hit/KO, reload and exact phase timing are authored Versus poses. CQC identity and pistol category are source supported; exact motion capture frames, numerical damage/stamina/timings and one-pose freeze are not source-extracted mechanics.',
 'Sources are untouched native RGBA1536x1024 with12 complete major body components each. Low-alpha fringe/residual background remains natively preserved; Canvas contour metadata excludes neighboring poses in close rows. No pixel cleanup, resize, horizontal flip, crop export, repaint or alpha editing occurred. Some near source-edge gutters are narrow but complete alpha>80 body and gear stay on canvas.',
 'Standing source-height recommendations measure non-low native pose extents for fixed per-sheet scale, not canonical centimetres. Opposite-facing small design/scale differences and final Canvas contours, contact geometry, live gameplay/mobile and phase origins require independent integrator/browser review. Producer delivery does not certify those later checks.',
 'Fourteen remote single PS3 frames, including searches of unsuitable costume/gameplay views, are retained. Only the seven named original-frame references above are selected; alternate civilian costume1200 and Otacon1950 are research only. No video/movie file downloaded in full and no source image pixels modified.'
]
checks={k:True for k in ['identity','costume','equipment','anatomicalSides','singleFigure','transparentBackground']}
review={'uid':UID,'status':'approved','reviewer':'pass7_old_snake_native / producer physical original-reference and six-native-sheet review','reviewedAt':'2026-10-02','sourceKind':'original-game-capture','fidelityStatus':'closest_supported','absolute1to1Certified':False,'target':'Closest supported original2008 PS3 Old Snake identity and selected equipment, continuing toward1:1 only where originals support it.','checks':checks,'sources':refs,'limits':limits,'approvalScope':'Six source-native body atlases and72 authored pose semantics only; runtime integration, contour physical review, live scale/contact/phase/mobile tests remain independent.'}
layout={
 'idle':{'sheet':'a','indices':[0,1],'fps':4,'loop':True},'walk':{'sheet':'a','indices':[2,3,4,5],'fps':8,'loop':True},'guard':{'sheet':'a','indices':[6,7],'fps':4,'loop':True},'crouch':{'sheet':'a','indices':[8,9],'fps':4,'loop':True},'jump':{'sheet':'a','indices':[10,11],'fps':5,'loop':False},
 'punch':{'sheet':'b','indices':[0,1,2],'fps':12,'loop':False},'heavy':{'sheet':'b','indices':[3,4,5],'fps':10,'loop':False},'low':{'sheet':'b','indices':[6,7,8],'fps':10,'loop':False},'hit':{'sheet':'b','indices':[9],'fps':0,'loop':False},'ko':{'sheet':'b','indices':[10,11],'fps':6,'loop':False},
 'throw':{'sheet':'c','indices':[0,1],'fps':9,'loop':False},'shoot':{'sheet':'c','indices':[2,3,4],'fps':10,'loop':False},'deploy':{'sheet':'c','indices':[5,6],'fps':8,'loop':False},'optic':{'sheet':'c','indices':[7],'fps':0,'loop':False},'recover':{'sheet':'c','indices':[8,9],'fps':5,'loop':False},'charge':{'sheet':'c','indices':[10,11],'fps':9,'loop':False}}
slots={'light':'punch','heavy':'heavy','low':'low','throw':'throw','special':'shoot','specialDown':'deploy','specialForward':'throw','specialBack':'crouch','super':'charge','utility':'recover'}
phase={k:{'startup':[0],'active':[1],'recovery':[2]} for k in ['punch','heavy','low','shoot']}
phase.update({k:{'startup':[0],'active':[1],'recovery':[0]} for k in ['throw','deploy','charge']});phase['optic']={'startup':[0],'active':[0],'recovery':[0]};phase['recover']={'startup':[0],'active':[1],'recovery':[1]};phase['crouch']={'startup':[0],'active':[1],'recovery':[0]}
selected={'a-right':'A_RIGHT_02','a-left':'A_LEFT_01','b-right':'B_RIGHT_01','b-left':'B_LEFT_01','c-right':'C_RIGHT_01','c-left':'C_LEFT_01'}
final=[]
for key,name in selected.items():
    p=B/'sources'/f'{name}.png';m=json.loads((B/'metadata'/f'{name}.result-summary.json').read_text());doc=json.loads((B/'layouts'/f'{key}.json').read_text());im=Image.open(p)
    if key[0]=='a':indices=[0,1]
    elif key[0]=='b':indices=[0,1,2]
    else:indices=[7]
    heights=[doc['cells'][i]['bbox'][3]-doc['cells'][i]['bbox'][1] for i in indices]
    row={'key':key,'source':str(p),'nativeOriginal':m['nativeOriginal'],'sha256':sha(p),'bytes':p.stat().st_size,'width':im.width,'height':im.height,'columns':4,'rows':3,'poseCount':12,'facing':1 if key.endswith('right') else -1,'mirror':False,'layout':str(B/'layouts'/f'{key}.json'),'standingReferencePoseIndices':indices,'standingSourceHeight':round(sum(heights)/len(heights),2),'observedBodyHeights':[c['bbox'][3]-c['bbox'][1] for c in doc['cells']],'canvasContourFrames':doc['foreign_body_frames']}
    assert sha(m['nativeOriginal'])==row['sha256'];final.append(row)
marks={}
points={'right':{'shoot':[1514,73],'deploy':[1148,442],'charge':[1513,783],'throw':[766,92]},'left':{'shoot':[1167,75],'deploy':[795,421],'charge':[1158,787],'throw':[396,116]}}
indices={'shoot':3,'deploy':6,'charge':11,'throw':1}
notes={'shoot':'Original-style Mk.2 long suppressor muzzle opening, actual visible opaque native end. Root may spawn tranq from this muzzle; not Solid Eye/torso/lens.','deploy':'Visible anatomical right glove at chaff canister release, immediately before tiny authored rectangular grenade. Hand source only, no physical color/fuze1:1 or electronic-effect certification.','charge':'Active native forward open glove tip for physical CQC charge contact, root-owned gameplay geometry; no energy emission.','throw':'Active native open glove tip for physical CQC grab contact, root-owned target/contact geometry; no magic projectile.'}
for side,groups in points.items():
    row=next(r for r in final if r['key']=='c-'+side);im=Image.open(row['source']);marks[side]={}
    for action,point in groups.items():
        rgba=list(im.getpixel(tuple(point)));assert rgba[3]>80
        marks[side][action]={'action':action,'frame':1,'sourcePoseIndex':indices[action],'file':f'assets/combat-sprites/{UID}/c-{side}-v1.png','source':row['source'],'nativeOriginal':row['nativeOriginal'],'sha256':row['sha256'],'point':point,'pointRGBA':rgba,'note':notes[action]}
write('SOURCE_COMBAT_ORIGINS.json',{'schema':'cqc.pass7.native-source-combat-marks/1','uid':UID,'coordinateSystem':'Full untouched native-sheet PNG pixel x,y, no resize/flip. frame=local action index; sourcePoseIndex=whole-sheet zero-based pose.','marks':marks,'slotSourceGroups':{'special':'shoot','specialDown':'deploy','specialForward':'throw','super':'charge'},'sourceScope':'Source-visible muzzle and authored glove contacts, independent runtime clamping/geometry still root-owned.'})
write('CANONICAL_REVIEW.json',review)
write('SOURCE_AND_ACTION_CONTRACT.json',{'uid':UID,'actionLayout':layout,'actionMap':slots,'phaseMap':phase,'facingIndependent':True,'mirror':False,'poses':72,'noRuntimeEdits':True,'weapons':{'Mk.2':'Original PS3 name/NON-LETHAL HUD+long suppressor silhouette supported.','Chaff':'Name/HUD silhouette/aimed throw supported; detailed physical body and anti-electronic operation not certified by stills.'},'phaseSemantics':{'shoot':'right-held original-style pistol raise / level muzzle aim / lower recovery','deploy':'right-hand rectangular canister windup / extended release glove, no explosion','charge':'grounded CQC ready / physical reaching lunge','throw':'CQC open glove ready / physical active reach','optic':'self equipment-check gesture, no offensive lock','specialBack':'opaque low OctoCamo stance, no authored invisibility'}})
attempts=[]
for p in sorted((B/'native-attempts').glob('*.png')):
    m=json.loads((B/'metadata'/f'{p.stem}.result-summary.json').read_text());attempts.append({'key':p.stem,'source':str(p),'nativeOriginal':m['nativeOriginal'],'sha256':sha(p),'bytes':p.stat().st_size,'status':'rejected-anatomical-optic-side-risk' if p.stem=='A_RIGHT_01' else 'approved-final','retainedUnchanged':True,'reason':'Initial RIGHT silhouette put dark equipment too prominently over visible near/right eye; regenerated RIGHT02 has near anatomicalRIGHT eye bare, sourceLEFT optic retained. Rejected source never imported or made OC.' if p.stem=='A_RIGHT_01' else 'Native complete original-incarnation closest-supported body poses physically viewed.'})
write('NATIVE_PNG_INDEX.json',{'uid':UID,'attempts':attempts,'nativeImages':len(attempts),'approvedBodySheets':6,'approvedPoses':72,'rejectedNativeImages':1,'pixelEdits':0,'generatedOtherOCs':0})
delivery={'schema':'cqc.native-combat-delivery/1','uid':UID,'name':'OLD SNAKE','game':'Metal Gear Solid 4: Guns of the Patriots (2008), original PlayStation3','incarnation':'Original2008 PS3 Old Snake base gray OctoCamo, bandana and anatomicalLEFT Solid Eye, original Mk.2 loadout; no Touch/MPO/FaceCamo alternate','selectedCostume':'original-ps3-old-snake-gray-octocamo-left-solid-eye','basis':'Original Mk.2 tranquilizer pistol identity, opaque OctoCamo surface matching and physical veteran CQC; selected Chaff throw silhouette, no invented damaging explosion or optical attack.','displayHeight':230,'coverage':'action-frames','facing':1,'mirror':False,'sourceFiles':final,'actionLayout':layout,'actionMap':slots,'phaseMap':phase,'review':review,'nativeSourceCombatOrigins':str(B/'SOURCE_COMBAT_ORIGINS.json'),'limits':limits}
write('FINAL_DELIVERY.json',delivery)
write('REFERENCE_PRESERVATION_INDEX.json',{'uid':UID,'selectedCanonicalReferences':len(refs),'selectedImageBytes':sum(r['bytes'] for r in refs),'budgetBytes':15000000,'allRetainedResearchAndReferenceImageBytes':sum(p.stat().st_size for p in (B/'references').glob('*') if p.suffix.lower() in {'.png','.jpg','.gif'}),'rawUnselectedFrames':[1200,1600,1800,1950,2050,2300,2400],'originalSourceContractUnchanged':sha(B/'references/source-contract.json')==sha('/workspace/cqc-pass7-reference-selection/core__old_snake/source-contract.json'),'fullMoviesDownloaded':0,'nativeFramebufferImagesUnmodified':True,'references':[{'path':str(p.relative_to(B)),'bytes':p.stat().st_size,'sha256':sha(p),'selectedCanonical':str(p) in {r['file'] for r in refs}} for p in sorted((B/'references').rglob('*')) if p.is_file()]})
print(json.dumps({'status':'producer-source-reviewed-ready-for-independent-integration','uid':UID,'delivery':str(B/'FINAL_DELIVERY.json'),'sheets':6,'poses':72,'nativeGeneratedPNG':7,'rejectedRetained':1,'sourceScales':{r['key']:r['standingSourceHeight'] for r in final},'selectedReferenceBytes':sum(r['bytes'] for r in refs)},indent=2))
