from pathlib import Path
import sys,json,hashlib,os,statistics
from PIL import Image
from scipy import ndimage
from matplotlib.path import Path as PolygonPath
import numpy as np
P=Path(__file__).parent;F=P/'armor';sys.path.insert(0,str(P));import inspect_mantis_complete as ins
UID='core__screaming_mantis';choices={'a-right':'A_RIGHT_01','a-left':'A_LEFT_01','b-right':'B_RIGHT_03','b-left':'B_LEFT_01','c-right':'C_RIGHT_01','c-left':'C_LEFT_01'}
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(n,d):
 p=F/n;p.parent.mkdir(parents=True,exist_ok=True);raw=(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode()
 if p.exists() and p.read_bytes()!=raw:
  old=p.read_bytes();bak=p.with_name(p.stem+'.previous-'+hashlib.sha256(old).hexdigest()[:12]+p.suffix)
  if not bak.exists():bak.write_bytes(old)
 p.write_bytes(raw)
checks=[]
def check(n,v):checks.append({'assertion':n,'passed':bool(v)});assert v,n
rows=[];layouts={};geo={};visual={};alphas=[];pivots={}
for key,n in choices.items():
 src=F/'native-attempts'/f'{n}.png';dst=F/'sources'/f'{n}.png'
 if not dst.exists():os.link(src,dst)
 meta=json.loads((F/'metadata'/f'{n}.result-summary.json').read_text());im=Image.open(src);a=np.array(im.getchannel('A'));h,w=a.shape;digest=sha(src);check(key+' native original unchanged',digest==sha(meta['nativeOriginal'])==sha(dst));check(key+' native transparent RGBA',im.mode=='RGBA' and a.min()==0 and (a==0).sum()>100000)
 labels,_=ndimage.label(a>=8);cnt=np.bincount(labels.ravel());ids=[i for i,z in enumerate(cnt) if i and z>=1000];check(key+' twelve complete body-arms-threads-dolls groups',len(ids)==12)
 edge=[int((z>=48).sum()) for z in [a[0],a[-1],a[:,0],a[:,-1]]];check(key+' complete native figures do not touch canvas border',not any(edge))
 asset=f'assets/combat-sprites/{UID}/{key}-v1.png';lay=ins.inspect(src,key,asset);groupids={c['component'] for c in lay['cells']}
 for c in lay['cells']:
  i=c['index'];fr=c['frame'];rx,ry,rw,rh=fr['rect'];check(key+f' pose{i} positive whole equipment rect and body pivot',rw>0 and rh>0 and all(0<=z<=1 for z in fr['pivot']))
  yy,xx=np.where(labels==c['component']);check(key+f' pose{i} rect contains every source group pixel >=8 including dolls and threads',np.all((xx>=rx)&(xx<rx+rw)&(yy>=ry)&(yy<ry+rh)))
  if 'clipPolygon' in fr:
   poly=np.array(fr['clipPolygon'])*[rw,rh];pp=PolygonPath(poly,closed=True);local=labels[ry:ry+rh,rx:rx+rw];localalpha=a[ry:ry+rh,rx:rx+rw];oy,ox=np.where((local==c['component'])&(localalpha>80));inside=pp.contains_points(np.c_[ox,oy]);check(key+f' pose{i} actual Canvas polygon retains every own opaque body/doll pixel',bool(inside.all()))
   fy,fx=np.where((local!=c['component'])&np.isin(local,list(groupids))&(localalpha>80));foreign=pp.contains_points(np.c_[fx,fy]);check(key+f' pose{i} actual Canvas polygon excludes all neighboring opaque fragments',not foreign.any())
  else:check(key+f' pose{i} rectangle has no foreign equipment group pixels',c['foreign_body_opaque_pixels_in_rect']==0)
 write('layouts/'+key+'.json',lay);layouts[key]=str(F/'layouts'/f'{key}.json');pivots[key]={str(c['index']):c['observedBodyPivotFullSheet'] for c in lay['cells']}
 heights=ins.HEIGHTS[key];geo[key]={'recommendStandingSourceHeight':heights,'observedUprightIndices':[0,1] if key.startswith('a') else ([0,2] if key.startswith('b') else [11]),'observedHelmetUpperPointsFullSheet':ins.HEADS[key],'measuredLayouts':layouts[key],'basis':'Physically observed main wearer helmet-to-boots anatomical source height, not overall high-reaching machinery/doll bbox. Body/support x observed manually; body support y uses actual lower opaque main wearer component, excluding detached-alpha dolls. Fixed positive per-sheet scale, no crouch/KO stretching.'}
 rows.append({'key':key,'source':str(dst),'nativeOriginal':meta['nativeOriginal'],'sha256':digest,'bytes':src.stat().st_size,'width':w,'height':h,'columns':4,'rows':3,'poseCount':12,'facing':1 if key.endswith('right') else -1,'mirror':False})
 visual[key]={'sha256':digest,'completeBodyAndWeaponViewed':True,'all12RequestedFacingViewed':True,'transparentBackground':True,'completeSourceLayout':layouts[key],'completeSourceLayoutSha256':sha(layouts[key]),'completeBodyAndEquipmentLayoutOverride':True,'standingSourceHeight':heights,'observedBodyPivots':pivots[key],'notes':['All twelve main bodies physically viewed, six extra mechanical arms, complete source curved blades, both distinct attached original dolls.','Source alpha8 threads connect equipment groups; alpha80 component-only crop is incomplete. Complete reviewed alpha8 layout required, PNG unchanged.','Mechanical arm occlusion and helmet oval limit exact side details; authored native projection targets original original PS3 closest_supported.','B RIGHT active heavy blade corrected through image_gen, then cell7 cut claw regenerated; every selected source has zero alpha>=48 canvas edge pixels.']}
 alphas.append({'key':key,'sha256':digest,'alphaExtrema':[int(a.min()),int(a.max())],'transparentPixels':int((a==0).sum()),'opaqueBorderPixels48':edge,'completeAlpha8Groups':len(ids),'nativePixelsEdited':False,'all12BodiesAndBothDollsPhysicallyViewed':True})
 meta['status']='accepted_closest_supported_after_producer_physical_review';write('metadata/'+n+'.result-summary.json',meta)
video='https://archive.org/download/PS3_Longplay_081_Metal_Gear_Solid_4/PS3_Longplay_081_Metal_Gear_Solid_4.mkv';scopes={36638:'Original PS3 close armor and Mantis doll: gas-mask doll with two large round pale-yellow eyepieces/filter, slender grey-blue suited body; dark oval main helmet with amber dots; olive cylindrical arm mounts and chest straps/pouches.',36636:'Original PS3 armor/bracers and Sorrow doll: smaller pale round lenses, dark grey hooded/military coat, pale hands and grey trousers. Distinct small doll, not a thrown grenade.',36802:'Original PS3 main armor, SIX extra mechanical arms plus two human braced arms, attached curved mechanical blades and BOTH small suspended dolls: frontal Mantis doll on wearer right/image left, Sorrow doll on wearer left/image right.',36634:'Original PS3 rear/side shoulder cylindrical machinery and attached extra arms; exact partly occluded reverse details qualified.',36960:'Original PS3 complete hovering armored main wearer, source boot soles and physical broad mechanical claw/attached blade rig; captured motion partially blurs fingertips.'}
refs=[]
for t,scope in scopes.items():
 p=P/'references'/f'original-ps3-hd-{t}s.jpg';im=Image.open(p);refs.append({'file':str(p),'url':video,'sourceKind':'original-game-capture','sha256':sha(p),'bytes':p.stat().st_size,'width':im.width,'height':im.height,'timeSeconds':t,'viewed':True,'scope':scope,'platformEvidence':'Archive WorldofLongplays original PS3 recording dated2014, creator Spazbo4. Original2008 game renderer, not a remake. Hardware/framebuffer not independently certified.','captureMethod':'ffmpeg single remote-seek decoded1280x720 frame encodedJPEG q2. Original reference pixels not recolored/resized/cropped; no full movie download.'})
limits=['Target 1:1 original MGS4 PS3, closest_supported newly authored 2D sprites from original3D source captures; no absolute pixel/model/material/animation identity certification.','Main human wearer is enclosed in original olive/charcoal armor, black oval closed helmet with amber dot sensors, olive chest rig and cylindrical mounts. SIX additional articulated black mechanical arms plus two actual human arms; attached source crescent blades and TWO distinct small Mantis/Sorrow dolls remain gear rather than extra fighters.','Original dolls are supported by close captures36636/36638/36802: gas-mask grey-blue Mantis and dark hooded/military-coat Sorrow. Exact miniature seams, lens hue, strings, fine mask/filter topology, and occluded reverse anatomy are interpreted at sprite scale; Sorrow lens highlights in B RIGHT remain warmer than neutral source. Number/orientation of visibly exposed blade edges varies with authored arm occlusion; source-original blade counts in all original animation frames are not certified.','Source supplies doll holding/suspension, machinery and SOP/nanomachine manipulation of relevant soldiers. Sprite C keys represent Mantis-doll activation, Sorrow-doll activation, physical machinery grasp and reset. All control doll landmarks are HELD-OBJECT positions, not firearm muzzles or projectile origins. No thrown explosive doll, autonomous trap, magic shield, railshot, telekinetic universal duel effect or generic psychic aura is supported by this delivery. Original story Psycho Mantis/Sorrow associations are not erased; bounded Versus mechanics need explicit adaptation labels.','Normal light/mechanical strikes, heavy attached blade sweep, low strike, guard, crouch, bounded hover, hit/KO and physical grasp are newly authored Versus adaptations. They are not extracted original animations or canonical duel evidence.','All six facings independently generated, no mirrored raster and no source pixel edit outside image_gen. B RIGHT1 rejected wrong heavy active empty claw; B RIGHT2 retained corrected heavy but cut canvas-right claw; B RIGHT3 final is complete without opaque borders. All eight native attempts, exact args and rejects preserved, no OC conversion.','Puppets and thin strings require reviewed COMPLETE alpha8-equipment layout. Original generic threshold80 inspector would crop separated dolls. Custom layout only supplies native rectangles/concave Canvas contours/pivots; every own opaque body/doll pixel retained and neighboring opaque fragments excluded in geometric checks. Integrator must inspect actual Canvas rendering and verify final ground/move phase alignment.']
review={'status':'approved','reviewer':'bb_screaming_mantis producer / physical review of six complete armor atlases and five original PS3 reference frames','reviewedAt':'2026-10-02','sourceKind':'original-game-capture','checks':{k:True for k in ['identity','costume','equipment','anatomicalSides','singleFigure','transparentBackground']},'fidelityStatus':'closest_supported','absolute1to1Certified':False,'sources':refs,'limits':limits,'approvalScope':'Source-specific MGS4 PS3 armored main identity/rig and distinct dolls,72 authored action poses and complete source layout metadata. Runtime integration and actual Canvas source-scale validation root-owned.'}
t=json.load(open(P/'beauty/FINAL_DELIVERY.json'));actions=t['actionLayout'];phase=t['phaseMap'];slots=dict(t['actionMap']);slots['super']='shoot'
marks={'schema':'cqc.pass8.native-source-held-object-marks/1','uid':UID,'coordinateSystem':'Native whole-source x,y, unscaled/unreflected. Actual HELD doll head point, no firearm/muzzle/projectile.','ballisticOriginApplicable':False,'marks':{}}
for side,key,points in [('right','c-right',{'mantis':[450,84],'sorrow':[334,534]}),('left','c-left',{'mantis':[464,100],'sorrow':[347,434]})]:
 row=next(r for r in rows if r['key']==key);im=Image.open(row['source']);marks['marks'][side]={}
 for doll,point in points.items():
  action='shoot' if doll=='mantis' else 'deploy';idx=1 if doll=='mantis' else 4;rgba=list(im.getpixel(tuple(point)));check(side+' '+doll+' held landmark actual source alpha',rgba[3]>80);lay=json.load(open(layouts[key]));rx,ry,rw,rh=lay['cells'][idx]['frame']['rect'];check(side+' '+doll+' held landmark inside actual active source crop',rx<=point[0]<rx+rw and ry<=point[1]<ry+rh)
  marks['marks'][side][doll]={'action':action,'frame':1,'sourcePoseIndex':idx,'file':f'assets/combat-sprites/{UID}/{key}-v1.png','source':row['source'],'sha256':row['sha256'],'point':point,'pointRGBA':rgba,'kind':'held-original-doll-landmark','note':'Physically observed original doll head in active manipulation pose, doll remains attached. Versus targeting cue may anchor here; never a ballistic launch or invented psychic projectile.'}
write('SOURCE_COMBAT_ORIGINS.json',marks)
contract={'uid':UID,'incarnation':'Original2008 MGS4 PS3 Screaming Mantis full Beast armor in Outer Haven command center','selectedEquipment':'Original mask, bracers, shoulder cylinders, six additional mechanical arms, curved source blades and two small distinct attached Mantis/Sorrow dolls','sourceFiles':refs,'actionLayout':actions,'actionMap':slots,'phaseMap':phase,'actionSemantics':{'shoot':'Mantis doll held activation / source-targeting cue, not ballistic','deploy':'Sorrow doll held activation, no thrown/deployed independent trap','throw':'physical machinery grasp, authored Versus adaptation','recover':'arms and control rig reset','heavy':'attached mechanical crescent blade sweep'},'completeLayoutOverrides':layouts,'limits':limits,'sourceProfileSnapshotsSha256':sha(P/'PROFILE_SNAPSHOTS.json'),'productionMutation':False};write('SOURCE_AND_ACTION_CONTRACT.json',contract)
delivery={'schema':'cqc.native-combat-delivery/1','uid':UID,'name':'SCREAMING MANTIS','game':'Metal Gear Solid4: Guns of the Patriots (2008, PS3)','incarnation':'Original2008 MGS4 PS3 armored Beast, closed black dotted helmet, olive cylinders and rig, six extra mechanical arms, attached curved blades and distinct Mantis/Sorrow doll puppets','selectedCostume':'original-mgs4-ps3-screaming-mantis-full-beast-armor','basis':'Original PS3 physical references and all source bodies/dolls reviewed; bounded newly authored Versus gestures and attached machinery, no generic supernatural projectile certification.','displayHeight':245,'coverage':'action-frames','facing':1,'mirror':False,'sourceFiles':rows,'actionLayout':actions,'actionMap':slots,'phaseMap':phase,'review':review,'counts':{'selectedNativePngSheets':6,'totalPoseCells':72,'poseCellsPerSheet':12,'facings':2,'nativeGenerationAttempts':8,'rejectedNativeAttempts':2,'selectedWeaponPropAtlases':0},'sourceGeometry':geo,'layouts':layouts,'completeSourceLayouts':layouts,'layoutOverrideRequired':True,'sourceCombatOrigins':str(F/'SOURCE_COMBAT_ORIGINS.json'),'sourceContract':str(F/'SOURCE_AND_ACTION_CONTRACT.json'),'nativeAlphaReview':str(F/'NATIVE_ALPHA_REVIEW.json'),'limits':limits,'requiresGameplayContract':'Do not use old invented thrown doll damage trap, Sorrow grenade, magic barrier or generalized psychic projectile. Preserve dolls held/attached. Mechanical blade/claw/grasp attacks and scoped SOP targeting cues must remain clearly Versus adaptations.'};write('FINAL_DELIVERY.json',delivery)
write('PRODUCER_VISUAL_REVIEW.json',{'uid':UID,'status':'approved','reviewer':'bb_screaming_mantis producer','sources':visual,'displayHeight':245,'allSixNativeAtlasesPhysicallyViewed':True,'all72CompleteBodiesAndBothDollsPhysicallyViewed':True,'completeLayoutOverrideRequired':True,'limits':limits});write('CANONICAL_REVIEW.json',review);write('NATIVE_ALPHA_REVIEW.json',{'uid':UID,'status':'passed','sheets':alphas,'nativePixelEdits':False});write('BODY_GROUND_PIVOTS.json',{'uid':UID,'schema':'cqc.pass8.native-body-ground-pivots/1','coordinates':'Native full-source x/y, no image edits, independent of broad arm/puppet alpha centroid','pivots':pivots,'sourceGeometry':geo});write('DELIVERY_VERIFICATION.json',{'uid':UID,'status':'passed','assertions':len(checks),'failures':0,'checks':checks,'acceptedNativeSheets':6,'authoredPoses':72,'independentFacings':True,'nativePixelsEdited':False,'runtimeVerified':False});write('FILE_SHA256_MANIFEST.json',{'uid':UID,'files':[{'path':str(x.relative_to(F)),'bytes':x.stat().st_size,'sha256':sha(x)} for x in sorted(F.rglob('*')) if x.is_file() and x.name!='FILE_SHA256_MANIFEST.json']})
print(json.dumps({'uid':UID,'delivery':str(F/'FINAL_DELIVERY.json'),'sha256':sha(F/'FINAL_DELIVERY.json'),'checks':len(checks),'completeNativeEquipmentGroups':72,'heldDollMarks':4,'sourceHeights':{k:v['recommendStandingSourceHeight'] for k,v in geo.items()}},indent=2))
