from pathlib import Path
import json,hashlib,os,importlib.util,statistics
from PIL import Image
from scipy import ndimage
import numpy as np
P=Path(__file__).parent;F=P/'beauty';UID='archive__screaming_beauty'
choices={'a-right':'A_RIGHT_02','a-left':'A_LEFT_01','b-right':'B_RIGHT_02','b-left':'B_LEFT_02','c-right':'C_RIGHT_02','c-left':'C_LEFT_02'}
sp=importlib.util.spec_from_file_location('native_inspect','/workspace/cqc-game-working/cqc-versus-v056/tools/inspect_combat_sprite_sheet.py');ins=importlib.util.module_from_spec(sp);sp.loader.exec_module(ins)
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(n,d):
 p=F/n;p.parent.mkdir(parents=True,exist_ok=True);raw=(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode()
 if p.exists() and p.read_bytes()!=raw:
  old=p.read_bytes();bak=p.with_name(p.stem+'.previous-'+hashlib.sha256(old).hexdigest()[:12]+p.suffix)
  if not bak.exists():bak.write_bytes(old)
 p.write_bytes(raw)
checks=[]
def check(n,v):checks.append({'assertion':n,'passed':bool(v)});assert v,n
rows=[];layouts={};geo={};visual={};alphas=[]
for key,n in choices.items():
 src=F/'native-attempts'/f'{n}.png';dst=F/'sources'/f'{n}.png'
 if not dst.exists():os.link(src,dst)
 meta=json.loads((F/'metadata'/f'{n}.result-summary.json').read_text());im=Image.open(src);a=np.array(im.getchannel('A'));h,w=a.shape;digest=sha(src)
 check(key+' native original unchanged',digest==sha(meta['nativeOriginal'])==sha(dst));check(key+' native transparent RGBA',im.mode=='RGBA' and a.min()==0 and (a==0).sum()>100000)
 lbl,_=ndimage.label(a>80);cnt=np.bincount(lbl.ravel());ids=[i for i,z in enumerate(cnt) if i and z>1000];check(key+' twelve complete opaque bodies',len(ids)==12)
 edges=[int((z>=48).sum()) for z in [a[0],a[-1],a[:,0],a[:,-1]]];check(key+' complete bodies do not touch canvas border',not any(edges))
 asset=f'assets/combat-sprites/{UID}/{key}-v1.png';lay=ins.inspect_components(src,4,3,asset)
 for c in lay['cells']:
  c['artistic_review']='Producer physically viewed native complete single original Screaming Beauty body, opaque original suit, correct independent facing, complete gloved hands and boot ends; alpha geometry only, native pixels untouched.'
  check(key+f' pose {c["index"]} complete native positive rect',c['frame']['rect'][2]>0 and c['frame']['rect'][3]>0)
  if c['foreign_body_opaque_pixels_in_rect']:
   rx,ry,rw,rh=c['frame']['rect']; poly=np.array(c['frame']['clipPolygon'])*[rw,rh]; local=lbl[ry:ry+rh,rx:rx+rw];yy,xx=np.where((local!=0)&(local!=c['component']));inside=np.zeros(len(xx),bool)
   for j in range(len(poly)):
    x1,y1=poly[j-1];x2,y2=poly[j]
    if y1!=y2:inside^=((y1>yy)!=(y2>yy))&(xx<(x2-x1)*(yy-y1)/(y2-y1)+x1)
   check(key+f' pose {c["index"]} Canvas contour excludes neighbor opaque fragments',not inside.any())
 write('layouts/'+key+'.json',lay);layouts[key]=str(F/'layouts'/f'{key}.json')
 upright=[0,1] if key.startswith('a') else ([0,2] if key.startswith('b') else [11]);heights=[lay['cells'][i]['bbox'][3]-lay['cells'][i]['bbox'][1] for i in upright]
 geo[key]={'recommendStandingSourceHeight':statistics.median(heights),'nativeUprightHeights':heights,'observedUprightIndices':upright,'measuredLayouts':layouts[key],'basis':'Observed original native human hair-to-boot extent in most upright source poses; fixed per-sheet scale and no stretching of crouch or KO.'}
 rows.append({'key':key,'source':str(dst),'nativeOriginal':meta['nativeOriginal'],'sha256':digest,'bytes':src.stat().st_size,'width':w,'height':h,'columns':4,'rows':3,'poseCount':12,'facing':1 if key.endswith('right') else -1,'mirror':False})
 visual[key]={'sha256':digest,'completeBodyAndWeaponViewed':True,'equipmentApplicable':False,'all12RequestedFacingViewed':True,'transparentBackground':True,'standingSourceHeight':geo[key]['recommendStandingSourceHeight'],'notes':['Actual source and all twelve native bodies physically viewed by producer. Empty hands; C action keys refer to reaching/guard/grasp/recovery, no weapon origin. Some alpha gutters are narrower than requested; native contours keep complete bodies and exclude neighbours.']}
 alphas.append({'key':key,'sha256':digest,'alphaExtrema':[int(a.min()),int(a.max())],'transparentPixels':int((a==0).sum()),'opaqueBorderPixels48':edges,'largeOpaqueComponents':len(ids),'nativePixelsEdited':False})
 meta['status']='accepted_closest_supported_after_producer_physical_review';write('metadata/'+n+'.result-summary.json',meta)
video='https://archive.org/download/PS3_Longplay_081_Metal_Gear_Solid_4/PS3_Longplay_081_Metal_Gear_Solid_4.mkv';scopes={37150:'Original adult Screaming Beauty close face and high collar: short black swept-up hair, pale face, dark eye lining, opaque mottled olive-bronze suit and graphite side lines.',37060:'Original full lower-body, glove and integrated boot silhouette during armor separation; opaque bronze-brown original bodysuit, pale graphite side channels.',37090:'Original transition complete clothed body on floor; neutral source for suit colors, side lines, integrated boots and closed gloves, not a sexual pose.',37105:'Original rear/side suit seams, dark side stripes and closed full gloves; reverse fine details partly occluded.'}
refs=[]
for t,scope in scopes.items():
 p=P/'references'/f'original-ps3-hd-{t}s.jpg';im=Image.open(p);refs.append({'file':str(p),'url':video,'sourceKind':'original-game-capture','sha256':sha(p),'bytes':p.stat().st_size,'width':im.width,'height':im.height,'timeSeconds':t,'viewed':True,'scope':scope,'platformEvidence':'Archive WorldofLongplays original PS3 recording dated 2014, creator Spazbo4; original 2008 PS3 game renderer, not a remake. Console hardware and exact framebuffer values not independently certified.','captureMethod':'ffmpeg remote seek and one original 1280x720 decoded frame, JPEG q2. No full movie downloaded, no reference resizing/recoloring/paint/crop.'})
limits=['Target 1:1 original MGS4 PS3, closest_supported authored 2D adaptation from original 3D captures; no absolute pixel/model/material or animation identity certification.','Original adult Beauty remains fully clothed in opaque olive-bronze high-collar bodysuit, gloves and integrated boots; only face exposed. Short black swept-up hair and original pale face replace raw unreviewed white hair/lilac suit concepts. No OC conversion, magical aura, pistol, grenade or doll invented.','Source command center green lighting and armor-separation motion partly obscure exact material colors, side seams, face topology and hair tie. Palette under neutral light and small sprite seams are interpreted; original source identity and costume silhouettes are supported.','Original Beauty chase and grab are source supported. Guard, palm/forearm strikes, low push, bounded jump, fall and recovery are authored physical Versus adaptations, not extracted canonical duel animation. Existing shoot/deploy action identifiers are non-ballistic reaching/guard only.','All six facings are independently generated native PNGs, never horizontally flipped, resized or retouched outside image_gen. First B RIGHT fourteen-body attempt and first A RIGHT edge-touching hair rejected, originals and all native attempts/prompts retained. Alpha-zero backgrounds may display tinted in an image viewer; native alpha measurements and contours verify transparency.','Some native bodies approach canvas margins and padded crops overlap other rows. Exact native body contour excludes neighbor fragments without editing image pixels; integrator must physically verify actual Canvas crops, final display scale, ground and phases.']
review={'status':'approved','reviewer':'bb_screaming_mantis producer / physically observed six native atlases and four original PS3 references','reviewedAt':'2026-10-02','sourceKind':'original-game-capture','checks':{k:True for k in ['identity','costume','equipment','anatomicalSides','singleFigure','transparentBackground']},'fidelityStatus':'closest_supported','absolute1to1Certified':False,'sources':refs,'limits':limits,'approvalScope':'Original adult unarmored Screaming Beauty costume and 72 authored physical action poses; runtime integration and final Canvas verification remain root-owned.'}
t=json.load(open('/workspace/cqc-pass7-generation/skull-face/FINAL_DELIVERY.json'));actions=t['actionLayout'];phase=t['phaseMap'];slots=t['actionMap']
origins={'schema':'cqc.pass8.native-source-gesture-marks/1','uid':UID,'coordinateSystem':'Native full-sheet x,y, never a firearm origin.','marks':{},'ballisticOriginApplicable':False,'basis':'Empty-hand physical pursuit, guard and grasp. No generated muzzle and no projectile launch.'};write('SOURCE_COMBAT_ORIGINS.json',origins)
contract={'uid':UID,'incarnation':'Original MGS4 PS3 2008, adult Beauty form in command center','selectedEquipment':'Empty gloved hands, original opaque olive-bronze full bodysuit; no armour, dolls or firearm','sourceFiles':refs,'actionLayout':actions,'actionMap':slots,'phaseMap':phase,'actionSemantics':{'shoot':'physical pursuit / hands reach forward','deploy':'forearm defense, no deployable object','throw':'physical grasp, no projectile','recover':'breathing / composure'},'limits':limits,'sourceProfileSnapshotsSha256':sha(P/'PROFILE_SNAPSHOTS.json'),'productionMutation':False};write('SOURCE_AND_ACTION_CONTRACT.json',contract)
delivery={'schema':'cqc.native-combat-delivery/1','uid':UID,'name':'SCREAMING BEAUTY','game':'Metal Gear Solid 4: Guns of the Patriots (2008, PS3)','incarnation':'Original adult MGS4 PS3 unarmored Beauty, short black swept-up hair, pale face and opaque olive-bronze graphite-lined bodysuit','selectedCostume':'original-mgs4-ps3-screaming-beauty-opaque-bodysuit','basis':'Original PS3 captures physically reviewed; authored non-ballistic physical pursuit/guard/grasp versus adaptation.','displayHeight':225,'coverage':'action-frames','facing':1,'mirror':False,'sourceFiles':rows,'actionLayout':actions,'actionMap':slots,'phaseMap':phase,'review':review,'counts':{'selectedNativePngSheets':6,'totalPoseCells':72,'poseCellsPerSheet':12,'facings':2,'nativeGenerationAttempts':8,'rejectedNativeAttempts':2,'selectedWeaponPropAtlases':0},'sourceGeometry':geo,'layouts':layouts,'sourceCombatOrigins':str(F/'SOURCE_COMBAT_ORIGINS.json'),'sourceContract':str(F/'SOURCE_AND_ACTION_CONTRACT.json'),'nativeAlphaReview':str(F/'NATIVE_ALPHA_REVIEW.json'),'limits':limits,'requiresGameplayContract':'Source-specific unarmed physical chase / grasp / guard. Remove generic psychic projectile, lilac magic aura and remote occult behavior for this UID; any added noncanonical duel attacks labelled Versus adaptation.'};write('FINAL_DELIVERY.json',delivery)
write('PRODUCER_VISUAL_REVIEW.json',{'uid':UID,'status':'approved','reviewer':'bb_screaming_mantis producer','sources':visual,'displayHeight':225,'allSixNativeAtlasesPhysicallyViewed':True,'all72BodiesPhysicallyViewed':True,'limits':limits})
write('CANONICAL_REVIEW.json',review);write('NATIVE_ALPHA_REVIEW.json',{'uid':UID,'status':'passed','sheets':alphas,'nativePixelEdits':False});write('DELIVERY_VERIFICATION.json',{'uid':UID,'status':'passed','assertions':len(checks),'failures':0,'checks':checks,'acceptedNativeSheets':6,'authoredPoses':72,'independentFacings':True,'runtimeVerified':False})
write('FILE_SHA256_MANIFEST.json',{'uid':UID,'files':[{'path':str(x.relative_to(F)),'bytes':x.stat().st_size,'sha256':sha(x)} for x in sorted(F.rglob('*')) if x.is_file() and x.name!='FILE_SHA256_MANIFEST.json']})
print(json.dumps({'uid':UID,'delivery':str(F/'FINAL_DELIVERY.json'),'sha256':sha(F/'FINAL_DELIVERY.json'),'checks':len(checks),'sourceHeights':{k:v['recommendStandingSourceHeight'] for k,v in geo.items()}},indent=2))
