from pathlib import Path
import json
P=Path(__file__).parent
for form in ['beauty','armor']:
 for folder in ['prompts','metadata','native-attempts','sources','layouts','rejects']:(P/form/folder).mkdir(parents=True,exist_ok=True)
base='Create a faithful high quality illustrated 2D fighting game sprite atlas, sourced from the attached actual original 2008 Metal Gear Solid 4 PS3 game captures. Transparent RGBA background. EXACTLY TWELVE separate complete full-body poses in a FOUR COLUMN THREE ROW landscape grid, reading left to right then top to bottom. Prefer 1536x1024. Fixed orthographic side/three-quarter game view and constant standing body scale. Every head, hand, foot and costume end fully inside its own cell; generous 35 pixel alpha gutters, 25 pixel outer alpha margins. No text, grid lines, scenery, floor shadows, glow, particles, detached props or extra people. Crisp detailed hand painted game art, original costume proportions and colors under neutral light. '
beauty='Screaming Beauty, original adult MGS4 unarmored form, not an original character. Source adult female face: pale skin, dark lined eyes and black short hair swept up and back in a compact high crest, small pulled back rear section, no long loose hair and no white hair. Fully opaque bronze/olive brown fitted full length original nanotech bodysuit with subtle mottled material, high closed collar, seam across waist, integrated matching brown full gloves and close fitting boots, parallel dark graphite blue-grey lines following outside of shoulders and arms and outside of legs. Entire body clothed from neck to feet, hands gloved; only actual face uncovered. No nudity, exposed abdomen, cleavage, lingerie, wet transparency or sexual posing. Original source shows distress, walking toward opponent and grasping attempts; these are normal nonsexual gameplay adaptations. Empty hands, no gun, dolls, armor, halo, psychic fire or symbols. Athletic adult human proportions, normal practical heel shape, not exaggerated anatomy. '
poses={
'A':'Row 1: 0 upright cautious idle with open hands near sides; 1 second idle breathing variation, slightly shifted weight; 2 walking left foot forward; 3 walking transition right foot raised. Row 2: 4 walking right foot forward; 5 walking transition left foot raised; 6 protective unarmed forearm guard near chest; 7 firmer guard braced arms. Row 3: 8 compact crouch bent knees; 9 low crouching guard shorter height but same body scale; 10 small jump ascent with knees bent; 11 jump descent ready to land. Face always points requested direction.',
'B':'Row 1: 0 unarmed reaching palm strike startup; 1 active forward palm strike; 2 withdrawing palm recovery. Row 2: 3 startup broad defensive forearm sweep; 4 active body-weight forearm push; 5 recovery arm lowered. Row 3: 6 low reaching startup knees bent; 7 active low physical push crouched; 8 low recovery; 9 single restrained recoil from a hit with face still requested direction; 10 falling sideways beginning KO with head on requested forward side; 11 side lying nonsexual KO head on requested forward side, knees slightly bent, no gore. All moves remain physical authored versus adaptations.',
'C':'Row 1: 0 original chase/grab intent startup hands brought forward; 1 active reaching BOTH empty gloved hands forward toward opponent; 2 hands withdraw recovery. Row 2: 3 braced defensive movement startup; 4 active forearms guarding head and chest; 5 relax guard recovery. Row 3: 6 close-range physical grab startup; 7 active two handed grasp at imaginary opponent forearm, no other person drawn; 8 releasing physical grab recovery; 9 recovery posture catching breath; 10 second breathing recovery hands near abdomen over fully opaque suit; 11 upright return to cautious stance. No supernatural or ballistic projectile implied by any gesture.'}
refs=[str(P/'references'/f'original-ps3-hd-{t}s.jpg') for t in [37150,37060,37090,37105]]
for letter in ['A','B','C']:
 for side in ['RIGHT','LEFT']:
  args={'prompt':base+beauty+'ALL TWELVE poses face SCREEN '+side+'. This must be an independently authored anatomical view; do not mirror or flip an existing atlas. Sheet '+letter+' exact poses: '+poses[letter],'referenced_image_paths':refs,'transparent_background':True}
  (P/'beauty/prompts'/f'{letter}_{side}_01.args.json').write_text(json.dumps(args,ensure_ascii=False,indent=2)+'\n')
print('Prepared six independently facing Beauty requests; source pixels untouched.')
