from pathlib import Path
import json
P=Path(__file__).parent;F=P/'armor'
base='Create a faithful detailed illustrated 2D fighting-game sprite atlas of SCREAMING MANTIS in her original 2008 Metal Gear Solid 4 PS3 full armored Beast form. Use the attached ACTUAL original PS3 game frames as exact costume, mask, arm and puppet references. Transparent RGBA PNG, landscape 1536x1024 preferred. EXACTLY 12 separate COMPLETE full-body figures, a strict FOUR COLUMNS THREE ROWS grid, one pose per cell in row-major order. Each figure and all its equipment stay wholly inside its cell with real alpha gutters 25px between cells and 25px outer margins. Fit whole figure, its SIX extra mechanical arms, ALL blades and BOTH connected dolls in each cell. At most 275px standing main-body height and about330px width for complete figure including equipment. Fixed orthographic side/three-quarter projection, constant main-body scale. Entire heads, fingertips, curved blades, strings, dolls and boot soles complete. No floor, scenery, cell borders, labels, FX, magic, glow aura or shadows. Native original materials readable under neutral light, not oversaturated green. '
identity='IDENTITY EQUIPMENT: adult HUMAN wearer completely enclosed inside dark charcoal/olive smooth armored nanotech suit, pale grey side seams, angular grey-olive chest harness with original rectangular pouches and straps; smooth dark-black closed OVAL face-covering helmet with tiny amber-yellow indicator dots as original, no visible human hair/face, no insect antennas or exposed breasts. Human-shaped legs in complete closed matching suit and close-fitting armored boots. TWO original human arms with long olive-grey plated forearm bracers and black gloved hands carrying compact puppet-control handles. SIX EXTRA black slim segmented MECHANICAL arms attached by stout bronze/olive cylindrical motor sleeves to upper back/shoulders: three on each anatomical side, curved bent elbows and black articulated claw hands. Among those mechanical arms preserve the original curved crescent/scythe blades held at the ends; exact blade contours follow original refs, no rifles or missiles. Mechanical arms remain attached to the wearer in every pose; do not draw insect legs in place of human legs. TWO DISTINCT original PUPPET DOLLS travel with her in EVERY pose, NOT two extra full-size people: each about20-25% human body height, suspended from clearly attached fine opaque strings/control connection held by original hands, contained in same cell. Original MANTIS doll belongs on anatomical RIGHT side: narrow grey-blue suited humanoid, rounded GAS MASK with TWO big round yellowish eyepieces and small round filter. Original SORROW doll belongs on anatomical LEFT side: dark grey long hooded/military coat, smaller pale circular spectacles on head, pale tiny hands, grey trousers. Match both dolls from the supplied close PS3 frames exactly, keep visually distinct and NEVER swap their identities by mirroring. In KO the dolls lie compactly against still-connected arms or suit, not loose detached separate objects. No magical fire, generic energy cannon, thrown doll grenade, autonomous trap, ornate fantasy staff or shield. Mechanical strikes, guard and grabbing are explicitly authored versus adaptations of original gear, not claimed extracted canonical animation. '
poses={
'A':'ROW ONE exactly four cells: cell0 upright hovering idle arms spread within cell and dolls suspended close; cell1 alternate idle breathing arm bend; cell2 forward grounded/low-hover glide with one human foot forward; cell3 glide transition next foot lifts. ROW TWO exactly four cells: cell4 glide other foot forward; cell5 glide transition opposite foot lifts; cell6 compact mechanical forearm guard, dolls secure; cell7 braced crossed human arms and mechanics guard. ROW THREE exactly four cells: cell8 lowered compact crouch all arms folded close; cell9 deeper guarded crouch, same body scale; cell10 short hover ascent legs slightly tucked; cell11 hover descent ready to land. All twelve masks point requested side; doll mask faces may be partially forward but do not flip their anatomical assignments.',
'B':'ROW ONE exactly four cells: cell0 mechanical hand strike startup, dolls held; cell1 one forward mechanical claw extends for active physical strike, other arms folded; cell2 claw withdrawing recovery; cell3 curved blade sweep startup. ROW TWO exactly four cells: cell4 active attached curved mechanical blade sweep; cell5 attached blade recovers; cell6 low claw windup knees bent; cell7 active close low claw swipe, dolls secure. ROW THREE exactly four cells: cell8 low recovery; cell9 restrained hit recoil; cell10 fall beginning KO on side with whole equipment folded close; cell11 complete side-lying KO with helmet on requested forward side, machinery and BOTH dolls connected folded alongside body. NO fourth row. All 12 main masks look requested side and all arm/blade tips fit cells.',
'C':'ROW ONE exactly four cells: cell0 Mantis-doll control startup raises anatomical RIGHT control handle; cell1 active raises anatomical RIGHT Mantis doll and moves original control hands while Mantis doll STAYS SUSPENDED and attached; cell2 Mantis-doll control recovery; cell3 Sorrow-doll control windup raises anatomical LEFT control handle. ROW TWO exactly four cells: cell4 active Sorrow-doll control gesture while Sorrow doll STAYS SUSPENDED, attached and distinct; cell5 Sorrow control recovery; cell6 physical mechanical grasp windup; cell7 forward mechanical claw physical grabbing toward imaginary opponent, no extra opponent. ROW THREE exactly four cells: cell8 mechanical grasp releases/recovery; cell9 machinery lowers to rest; cell10 second reset/rest pose; cell11 upright neutral recovery. All masks point requested side, both dolls remain present and connected, no shooting muzzle, no projectile and no magic aura.'}
refs=[str(P/'references'/f'original-ps3-hd-{t}s.jpg') for t in [36638,36636,36802,36634]]
for letter in ['A','B','C']:
 for side in ['RIGHT','LEFT']:
  args={'prompt':base+identity+' ALL TWELVE main figures face SCREEN '+side+'. This is an independently generated native anatomical view, never a flipped raster. Sheet '+letter+': '+poses[letter]+' Exactly twelve complete bodies, each with all six extra arms and two connected small distinct dolls.','referenced_image_paths':refs,'transparent_background':True};(F/'prompts'/f'{letter}_{side}_01.args.json').write_text(json.dumps(args,ensure_ascii=False,indent=2)+'\n')
print('Six armor requests prepared from physically viewed original PS3 arms and distinct dolls.')
