from pathlib import Path
from PIL import Image
import json,hashlib,statistics,sys
BASE=Path('/workspace/cqc-pass8-generation/paz-eva')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def make(c):
 p=BASE/c
 uid='npc53__paz_gz' if c=='paz-gz' else 'archive__paz'
 def write(n,d):
  f=p/n;raw=(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode()
  if f.exists() and f.read_bytes()!=raw:
   old=f.read_bytes();bk=f.with_name(f.stem+'.previous-'+hashlib.sha256(old).hexdigest()[:12]+f.suffix)
   if not bk.exists():bk.write_bytes(old)
   f.unlink()
  if not f.exists():f.write_bytes(raw)
 sel={'a-right':'A_RIGHT_01','a-left':'A_LEFT_01','b-right':'B_RIGHT_01','b-left':'B_LEFT_02' if c=='paz-gz' else 'B_LEFT_01','c-right':'C_RIGHT_01','c-left':'C_LEFT_01'}
 src=[];geom={};alpha=[]
 for key,k in sel.items():
  f=p/'sources'/f'{k}.png';im=Image.open(f);d=json.loads((p/'layouts'/f'{key}.json').read_text());inds=[0,1] if key[0]=='a' else [0,2] if key[0]=='b' else [9,11]
  assert len(d['cells'])==12 and all(x['pixels']>=1000 for x in d['cells'])
  assert im.mode=='RGBA' and im.getchannel('A').histogram()[0]>0
  hs=[d['cells'][i]['bbox'][3]-d['cells'][i]['bbox'][1] for i in inds]
  native=json.loads((p/'prompts'/f'{k}.result.json').read_text())['nativeOriginal'];assert sha(f)==sha(Path(native))
  src.append({'key':key,'source':str(f),'nativeOriginal':native,'sha256':sha(f),'bytes':f.stat().st_size,'width':im.width,'height':im.height,'columns':4,'rows':3,'poseCount':12,'facing':1 if key.endswith('right') else -1,'mirror':False})
  geom[key]={'recommendStandingSourceHeight':statistics.median(hs),'nativeUprightHeights':hs,'observedUprightIndices':inds,'measuredLayouts':str(p/'layouts'/f'{key}.json'),'basis':'Measured actual native upright head-to-foot source height; fixed positive per-sheet scale, lowered poses retain actual body height and are not stretched.'}
  alpha.append({'key':key,'sha256':sha(f),'mode':im.mode,'alphaExtrema':list(im.getchannel('A').getextrema()),'alphaZeroPixels':im.getchannel('A').histogram()[0],'completePhysicallyViewedBodies':12,'foreignOpaqueRectFrames':d['foreign_body_frames'],'nativePixelsEdited':False,'frameCanvasContoursUsed':bool(d['foreign_body_frames'])})
 assert len(set(x['sha256'] for x in src))==6
 proto=json.loads(Path('/workspace/cqc-pass7-generation/skull-face/FINAL_DELIVERY.json').read_text())
 if c=='paz-gz':
  game='Metal Gear Solid V: Ground Zeroes (2014)';inc='Original GZ adult Paz age23, short cropped blond hair, pale worn long prisoner shirt/tunic, rolled sleeves and bare feet; post-restraint-release authored bonus poses';costume='original-gz-paz-prisoner-shirt'
  selectedRefs=[('original-2990s.png','Original GZ Xbox One title-card closeup proves short cropped blond hair, adult face, simple pale open-neck prisoner shirt; orange source light is not neutral color calibration.'),('original-3005s.png','Original GZ Xbox One reverse/side short cropped hair and worn turned collar, buttons, sleeve materials; released-posture adapted sprites omit restraints and graphic trauma.'),('original-3100s.png','Original GZ Xbox One rescued Paz carried by Snake; rolled pale sleeves, loose tunic and bare feet. Cloth hem/seams partly occluded and lighting dark.'),('original-3250s.png','Original GZ Xbox One carried whole-body rear, actual bare feet, tunic/cuffs. Night vision distorts fabric colors; not used for neutral palette certification.')]
  url='https://archive.org/download/Xbox_One_Longplay_004_Metal_Gear_Solid_V_Ground_Zeroes/Xbox_One_Longplay_004_Metal_Gear_Solid_V_Ground_Zeroes.mp4'
  limits=['Paz selected here is the adult original GZ prisoner incarnation with short cropped blond hair, pale worn collared/buttoned tunic, sleeves rolled at elbows, bare lower legs/feet. She is not the TPP medical hallucination with braids/blue gown and not PW school-cover outfit.', 'Dark/orange and night-vision original capture lighting occludes neutral pale shirt hue, reverse seams and some garment hem details. Sprite pale beige-grey-green hue, cloth stain placement, exact buttons/finger topology and feet anatomy remain closest_supported, not exact model/material1:1.', 'These calm support/defense, authored normals/jump/guard, light recoil/tired-rest KO, empty-hand signal/protection/CQC/composure poses are bonus versus simulation after restraint release, not a canonical recovered GZ duel or an assertion that original trauma never occurred. No wounds, graphic violence, underwear, chains or bomb scenes appear.', 'B LEFT01 omitted a body and contains11 rather than12 poses; it is rejected, preserved and replaced by independently regenerated B LEFT02 containing12 complete bodies. No pixel erasure/paint/mirroring was used.']
  rejects={'B_LEFT_01':'Native generator supplied only11 complete bodies; required low-recovery pose was omitted. All source bytes kept; new image_gen B LEFT02 has12.'}
 else:
  game='Metal Gear Solid: Peace Walker (2010), original design viewed in Xbox360 HD port';inc='Original PW adult Paz age21 student-cover appearance, short wavy blond hair, navy blazer/pleated skirt, white collar/red ribbon and high dark boots; HD-port source qualified';costume='original-pw-paz-dark-school-cover'
  selectedRefs=[('mania-original-50s.png','Original Xbox360 PW HD source face/shoulders: short wavy blond hair, dark navy/grey-blue blazer lapels, white blouse collar, thin red ribbon tie. Actual source physically viewed.'),('mania-original-90s.png','Original Xbox360 PW HD whole-body student-cover outfit: dark blazer/pleated skirt, dark high footwear. Low-resolution whole-body original gameplay does not certify sole/stitching/stocking vs boot material edges.'),('mania-original-100s.png','Original Xbox360 PW HD original Paz whole-body gesture; confirms dark skirt, bare knees and dark high footwear silhouette, no firearm or military armor. A small dark rounded handheld object is visible in this gameplay episode; its exact shape/material is low-resolution.'),('mania-original-160s.png','Original Xbox360 guide shows Xbox achievement interface and MGS PEACE WALKER HD title; hardware/platform evidence for original-design HD port, not PSP framebuffer/pixel certification.')]
  url='https://archive.org/download/youtube-lsOxdkVK7dQ/lsOxdkVK7dQ.mp4'
  limits=['Actual original PW HD captures prove dark navy/grey-blue blazer and pleated skirt, white collar and thin red ribbon, short wavy blond hair and dark high footwear. Earlier speculative white blouse/green skirt assumption is excluded; no ponytail or TPP double-braid blue gown is used.', 'References are the original2010 design in Xbox360 HD port as identified in source/achievement footage, not direct PSP hardware capture. Their original adult face proportions, clothing silhouette and palette guide these 2D authored poses; exact PSP mesh/framebuffer, material, seams, eye color, button/stitch topology, boot shaft/stocking distinction and pixel1:1 are not certified.', 'Introductory red Shinkawa coat is retained as an unused reference to another scene. Existing mislabeled archive portrait was actually TPP hallucination and is not used. Another Date with Paz video had already unlocked the underwear variant; its attempts/captures are conserved for research, excluded from these fully clothed sprites.', 'The original gameplay around mania90s shows a dark rounded handheld object with a short stem/handle (a pan is probable). It does not prove a firearm or ZEKE control. The source capture is preserved. These selected native pose groups intentionally use free hands as authored bonus human gestures; they do not certify every original-game posture, absence of all equipment or a source-extracted empty-handed duel. No invented weapon is drawn.', 'All72 poses remain neutral fully clothed adult school-cover appearance, ordinary authored human support/defense gestures, never sexualized/minor portrayal or an assertion of canon schoolgirl combat proficiency.']
  rejects={}
 limits+=['Target remains1:1 fidelity to selected original incarnation, closest_supported output only. Newly illustrated2D poses are not extracted original animation; absolute1:1 artistic or gameplay certification is false.', 'No firearm/grenade/projectile origin, bomb, ZEKE control, armor inheritance, psychic field or summoned machine is invented. Existing action keys shoot/deploy merely identify non-ballistic signal/protection pose groups; root must explicitly supersede historical generic weapon behavior.', 'Native source PNGs and all attempts unchanged. Both facings independently generated and SHA-distinct, no mirrored body raster. Every selected atlas and each12 complete bodies physically viewed by producer. Canvas crops/contours, source scale, mobile/desktop, phase/hitbox/finisher behavior remain independently root-owned.', 'Close native row spacing produces recorded foreign opaque pixels in some bounding rectangles. Metadata Canvas contour stencils exclude neighbors; no image pixels edited. Use the measured upright source height for each sheet, retaining actual lowered crouch/KO size.']
 refs=[]
 for n,scope in selectedRefs:
  f=p/'references'/n;refs.append({'file':str(f),'url':url,'sourceKind':'original-game-capture','scope':scope,'viewed':True,'sha256':sha(f),'bytes':f.stat().st_size,'captureMethod':'ffmpeg remote-seek one native-resolution decoded frame, no complete movie download, crop, resize, recolor or pixel painting. Exact args and stderr preserved.'})
 review={'status':'approved','reviewer':'paz_two_versions_eva producer original source and complete72-pose physical review','reviewedAt':'2026-10-02','sourceKind':'original-game-capture','checks':{'identity':True,'costume':True,'equipment':True,'anatomicalSides':True,'singleFigure':True,'transparentBackground':True},'fidelityStatus':'closest_supported','absolute1to1Certified':False,'sources':refs,'limits':limits,'approvalScope':'Source-qualified adult original-game clothing/identity and72 authored human unarmed bonus poses, no canon duel or runtime integration certification.'}
 write('SOURCE_COMBAT_ORIGINS.json',{'schema':'cqc.pass8.native-source-combat-marks/1','uid':uid,'coordinateSystem':'Full unchanged native PNG sheet pixels; no ballistic points applicable.','marks':{'right':{},'left':{}},'slotSourceGroups':{},'ballisticOriginsApplicable':False,'sourceScope':'Unarmed humanoid source-supported appearance only. Open-hand gestures/CQC are not projectile muzzles.'})
 write('NATIVE_ALPHA_REVIEW.json',{'schema':'cqc.pass8.native-alpha-review/1','uid':uid,'status':'passed','sources':alpha,'nativeImageBytesUntouched':True})
 d={'schema':'cqc.native-combat-delivery/1','uid':uid,'name':'PAZ ORTEGA ANDRADE — GROUND ZEROES' if c=='paz-gz' else 'PAZ ORTEGA ANDRADE — PEACE WALKER','game':game,'incarnation':inc,'selectedCostume':costume,'basis':'Apparence originale adulte vérifiée sur captures ; mouvements unarmés de soutien/défense et simulation versus explicite, sans arme, pouvoir ou bombes inventés.','displayHeight':205,'coverage':'action-frames','facing':1,'mirror':False,'sourceFiles':src,'actionLayout':proto['actionLayout'],'actionMap':proto['actionMap'],'phaseMap':proto['phaseMap'],'review':review,'counts':{'selectedNativePngSheets':6,'totalPoseCells':72,'poseCellsPerSheet':12,'facings':2,'nativeGenerationAttempts':7 if c=='paz-gz' else 6,'rejectedNativeAttempts':1 if c=='paz-gz' else 0,'selectedWeaponPropAtlases':0},'sourceGeometry':geom,'layouts':{k:str(p/'layouts'/f'{k}.json') for k in sel},'sourceCombatOrigins':str(p/'SOURCE_COMBAT_ORIGINS.json'),'sourceContract':str(p/'SOURCE_AND_ACTION_CONTRACT.json'),'nativeAlphaReview':str(p/'NATIVE_ALPHA_REVIEW.json'),'limits':limits,'requiresGameplayContract':'Unarmed bonus simulation only: shoot=non-ballistic human signal, deploy=protective guard, throw=authored physical CQC, recover=composure. Remove historical firearm/grenade/ZEKE/psychic claims; runtime integration root-owned.'}
 write('SOURCE_AND_ACTION_CONTRACT.json',{'schema':'cqc.pass8.source-and-action-contract/1','uid':uid,'sourceCostume':costume,'canonicalWeapon':None,'canonicalEquipmentScope':'No firearm in these selected source captures; PW has a small black rounded held object, probably a pan, not represented in chosen free-hand authored gestures. No exhaustive equipment-absence certification.' if c=='paz-pw' else 'No weapon held in selected GZ prisoner rescue captures; not a claim about every Paz canon event.','unarmed':True,'ballisticOriginsApplicable':False,'canonicalCombatMovesExtracted':False,'slotSourceGroups':{'special':'shoot','specialDown':'deploy','super':'throw','utility':'recover','throw':'throw'},'selectedAgeIsAdult':True,'limits':limits})
 write('FINAL_DELIVERY.json',d)
 write('PRODUCER_PHYSICAL_REVIEW.json',{'schema':'cqc.pass8.producer-physical-review/1','uid':uid,'status':'approved','reviewer':'paz_two_versions_eva','completeSelectedNativePngViewed':6,'completePoseBodiesViewed':72,'sources':{x['key']:{'sha256':x['sha256'],'completeBodyAndWeaponViewed':True,'weaponApplicable':False,'handsAndBareFeetOrBootsObserved':True,'standingSourceHeight':geom[x['key']]['recommendStandingSourceHeight'],'notes':['Physically observed complete single adult body and source clothing; empty hands and feet/boots inside native boundaries. Final Canvas and runtime review remains root-owned.']} for x in src},'limits':limits})
 write('ATTEMPT_STATUS.json',{'selected':sel,'rejected':rejects,'variation':{}})
 write('FILE_SHA256_MANIFEST.json',{'schema':'cqc.pass8.producer-files/1','files':[{'path':str(f.relative_to(p)),'sha256':sha(f),'bytes':f.stat().st_size} for f in sorted(p.rglob('*')) if f.is_file() and f.name!='FILE_SHA256_MANIFEST.json']})
 print(json.dumps({'uid':uid,'delivery':str(p/'FINAL_DELIVERY.json'),'sha256':sha(p/'FINAL_DELIVERY.json'),'selectedNative':6,'poses':72,'ballisticOrigins':0,'sourceReferencesBytes':sum(x['bytes'] for x in refs)},indent=2))
if __name__=='__main__':
 for c in sys.argv[1:]:make(c)
