from pathlib import Path
from PIL import Image
import json,hashlib,statistics
BASE=Path('/workspace/cqc-pass8-generation/paz-eva/eva-mgs3')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(name,d):
 p=BASE/name;raw=(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode()
 if p.exists():
  old=p.read_bytes();bk=p.with_name(p.stem+'.previous-'+hashlib.sha256(old).hexdigest()[:12]+p.suffix)
  if old!=raw:
   if not bk.exists():bk.write_bytes(old)
   p.unlink()
 if not p.exists():p.write_bytes(raw)
sel={'a-right':'A_RIGHT_01','a-left':'A_LEFT_02','b-right':'B_RIGHT_01','b-left':'B_LEFT_01','c-right':'C_RIGHT_02','c-left':'C_LEFT_04'}
src=[];geom={};alpha=[]
for key,k in sel.items():
 p=BASE/'sources'/f'{k}.png';im=Image.open(p);layout=json.loads((BASE/'layouts'/f'{key}.json').read_text());inds=[0,1] if key[0]=='a' else [0,2]
 heights=[layout['cells'][i]['bbox'][3]-layout['cells'][i]['bbox'][1] for i in inds];native=json.loads((BASE/'prompts'/f'{k}.result.json').read_text())['nativeOriginal']
 src.append({'key':key,'source':str(p),'nativeOriginal':native,'sha256':sha(p),'bytes':p.stat().st_size,'width':im.width,'height':im.height,'columns':4,'rows':3,'poseCount':12,'facing':1 if key.endswith('right') else -1,'mirror':False})
 geom[key]={'recommendStandingSourceHeight':statistics.median(heights),'nativeUprightHeights':heights,'observedUprightIndices':inds,'measuredLayouts':str(BASE/'layouts'/f'{key}.json'),'basis':'Measured native upright human head-to-boot height. One positive sheet scale, no stretching crouch or KO to standing height.'}
 alpha.append({'key':key,'sha256':sha(p),'mode':im.mode,'alphaExtrema':list(im.getchannel('A').getextrema()),'alphaZeroPixels':im.getchannel('A').histogram()[0],'completePhysicallyViewedBodies':12,'foreignOpaqueRectFrames':layout['foreign_body_frames'],'nativePixelsEdited':False,'frameCanvasContoursUsed':bool(layout['foreign_body_frames'])})
proto=json.loads(Path('/workspace/cqc-pass7-generation/skull-face/FINAL_DELIVERY.json').read_text())
limits=['The target is faithful original MGS3 PS2 source appearance, closest_supported; no absolute 1:1 model, animation, seam, palette or pixel certification.', 'Original Konami model proves adult EVA honey blonde medium layered hair, goggles at neck, ochre/brown open motorcycle clothing over black undergarment, dark gloves, black tall laced boots, belt and anatomical RIGHT thigh holster. Original official page says Uses a Mauser; precise C96/Chinese Type17 designation and exact loading mechanism are not primary-source certified.', 'All 72 authored versus poses, strikes, guard/jump/KO, two aimed firing groups, CQC and restrained occluded reload are authored 2D adaptations, not source-extracted animations. No grenade, SMG, long gun, psychic effect or separate motorcycle is invented. Six-shot super and ammunition are root-owned adapted gameplay, not canonical duel balance.', 'Independent facings are not reflected. A LEFT01 ignored facing and is rejected; C LEFT02 had an opaque dark background patch and cannot be used; C LEFT03 had a second anatomical-left holster and is rejected. C LEFT04 corrects to the single anatomical-right far-side holster. C RIGHT01/C LEFT01 are conserved pre-reload variations. Every original and prompt remains preserved. Imagegen edits can also alter untargeted body rendering; source bytes of earlier variations are untouched and no exact first9-cell preservation is claimed.', 'Closely spaced source bodies need recorded Canvas contours; their source alpha/PNG bytes remain unchanged. Strongly lowered poses retain upright source scale. Reviewer physically viewed every selected complete source sheet and every12 cells, not runtime renders. Root must independently view final Canvas crops, phases, origins/collisions and mobile/desktop.', 'Moonlit original PS2 cutscene lighting and tiny official GIF do not certify exact leather material response, braid/finger topology, reverse stitching or Mauser machining details. The small illustrated long-barrel/broomhandle form is source-supported approximation; no modern detachable magazine or exact Type17 promise.']
refs=[]
for name,url,kind,scope,view in [('konami-eva.gif','https://www.konami.com/mg/archive/mgs3/english/pic/chara_eva_pic.gif','official-original-model','Original Konami PS2 full-body model, costume/hair/boots/right holster/goggles. Official model physically viewed.',True),('konami-eva.html','https://www.konami.com/mg/archive/mgs3/english/chara_eva.html','official-story-page','Official text: Uses a Mauser. A motorbike fanatic. Exact handgun subtype not stated.',False),('original-ps2-7600s.png','https://archive.org/download/PS2_Longplay-001-Metal_Gear_Solid_3-Snake_Eater/PS2_Longplay-001-Metal_Gear_Solid_3-Snake_Eater.mp4','original-game-capture','Original PS2 EVA speaking, honey-blonde layered hair, face and motorcycle jacket under blue night lighting. Not color calibration.',True),('original-ps2-7800s.png','https://archive.org/download/PS2_Longplay-001-Metal_Gear_Solid_3-Snake_Eater/PS2_Longplay-001-Metal_Gear_Solid_3-Snake_Eater.mp4','original-game-capture','Original PS2 full-body standing EVA beside Snake. Low resolution/overhead lighting occludes seams; not weapon model proof.',True)]:
 p=BASE/'references'/name;refs.append({'file':str(p),'url':url,'sourceKind':kind,'scope':scope,'viewed':view,'sha256':sha(p),'bytes':p.stat().st_size})
marks={'right':{},'left':{}}
points={'right':{'shoot':(1,[791,57]),'deploy':(4,[391,463])},'left':{'shoot':(1,[388,69]),'deploy':(4,[43,453])}}
for side,acts in points.items():
 key='c-'+side;row=next(x for x in src if x['key']==key);im=Image.open(row['source'])
 for act,(idx,point) in acts.items():
  assert im.getpixel(tuple(point))[3]>80
  marks[side][act]={'action':act,'frame':1,'sourcePoseIndex':idx,'file':f'assets/combat-sprites/core__eva_mgs3/{key}-v1.png','source':row['source'],'nativeOriginal':row['nativeOriginal'],'sha256':row['sha256'],'point':point,'pointRGBA':list(im.getpixel(tuple(point))),'note':'Actual visible opaque forward Mauser barrel end in first active authored aim pose, independently viewed; not glove, breast or torso. Exact subtype/ballistic/canonical animation not certified.'}
write('SOURCE_COMBAT_ORIGINS.json',{'schema':'cqc.pass8.native-source-combat-marks/1','uid':'core__eva_mgs3','coordinateSystem':'Full unchanged native PNG sheet pixels x,y. Local frame1 is first active action phase.','marks':marks,'slotSourceGroups':{'special':'shoot','specialDown':'deploy','super':'shoot'},'sourceScope':'Four actual source-supported standing/kneeling muzzle origins. Unarmed CQC hand gestures are not ballistic origins.'})
write('NATIVE_ALPHA_REVIEW.json',{'schema':'cqc.pass8.native-alpha-review/1','uid':'core__eva_mgs3','status':'passed','sources':alpha,'nativeImageBytesUntouched':True})
review={'status':'approved','reviewer':'paz_two_versions_eva producer, actual official/capture and six-source72-pose physical inspection','reviewedAt':'2026-10-02','sourceKind':'original-game-capture','checks':{'identity':True,'costume':True,'equipment':True,'anatomicalSides':True,'singleFigure':True,'transparentBackground':True},'fidelityStatus':'closest_supported','absolute1to1Certified':False,'sources':refs,'limits':limits,'approvalScope':'Original PS2 source-supported EVA appearance, native72 authored action poses and four measured firearm muzzle marks; runtime integration is separate.'}
d={'schema':'cqc.native-combat-delivery/1','uid':'core__eva_mgs3','name':'EVA','game':'Metal Gear Solid 3: Snake Eater (2004, PS2)','incarnation':'Original PS2 adult EVA, motorcycle clothing and right-thigh Mauser holster; no Delta, MPO or Big Mama blend','selectedCostume':'original-mgs3-ps2-eva-motorcycle','basis':'Apparence originale Konami PS2 et captures vérifiées ; mouvements versus adaptés. Mauser établi, type exact non certifié, aucune grenade inventée.','displayHeight':226,'coverage':'action-frames','facing':1,'mirror':False,'sourceFiles':src,'actionLayout':proto['actionLayout'],'actionMap':proto['actionMap']|{'super':'shoot','specialDown':'deploy'},'phaseMap':proto['phaseMap'],'review':review,'counts':{'selectedNativePngSheets':6,'totalPoseCells':72,'poseCellsPerSheet':12,'facings':2,'nativeGenerationAttempts':11,'rejectedNativeAttempts':3,'preservedPreReloadVariations':2,'selectedWeaponPropAtlases':0},'sourceGeometry':geom,'layouts':{k:str(BASE/'layouts'/f'{k}.json') for k in sel},'sourceCombatOrigins':str(BASE/'SOURCE_COMBAT_ORIGINS.json'),'sourceContract':str(BASE/'SOURCE_AND_ACTION_CONTRACT.json'),'nativeAlphaReview':str(BASE/'NATIVE_ALPHA_REVIEW.json'),'limits':limits,'requiresGameplayContract':'Standing Mauser shoot, kneeling Mauser deploy, physical CQC throw, actual reload recover; no grenade or magic. Root validates ammunition, adapted6-shot super, phase/collision/finisher/mobile.'}
write('SOURCE_AND_ACTION_CONTRACT.json',{'schema':'cqc.pass8.source-and-action-contract/1','uid':'core__eva_mgs3','sourceCostume':d['selectedCostume'],'canonicalWeapon':'Mauser (precise variant unverified)','slotSourceGroups':{'special':'shoot','specialDown':'deploy','super':'shoot','utility':'recover','throw':'throw'},'appearanceScope':'Original MGS3 PS2. Adult fully clothed original outfit in neutral poses.','canonicalMovesExtracted':False,'inventedGrenade':False,'limits':limits})
write('FINAL_DELIVERY.json',d)
write('PRODUCER_PHYSICAL_REVIEW.json',{'schema':'cqc.pass8.producer-physical-review/1','uid':'core__eva_mgs3','status':'approved','reviewer':'paz_two_versions_eva','completeSelectedNativePngViewed':6,'completePoseBodiesViewed':72,'sources':{x['key']:{'sha256':x['sha256'],'completeBodyAndWeaponViewed':True,'standingSourceHeight':geom[x['key']]['recommendStandingSourceHeight'],'notes':['Independently observed full body, original clothing/face, hands/boots intact. Canvas contour review remains root-owned.']} for x in src},'limits':limits})
write('ATTEMPT_STATUS.json',{'selected':sel,'rejected':{'A_LEFT_01':'All figures face RIGHT instead of LEFT. No mirror remedy.','C_LEFT_02':'Opaque dark bottom-row background connects bodies; no source-pixel erasure used.','C_LEFT_03':'Root and producer found extra near-side anatomical LEFT holster on multiple cells; official source proves anatomical RIGHT only. Superseded via image_gen, all earlier proof preserved.'},'variation':{'C_RIGHT_01':'Pre-reload composure poses. Superseded by visible reload sheet.','C_LEFT_01':'Pre-reload composure poses. Superseded by visible reload sheet.'}})
write('FILE_SHA256_MANIFEST.json',{'schema':'cqc.pass8.producer-files/1','files':[{'path':str(p.relative_to(BASE)),'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(BASE.rglob('*')) if p.is_file() and p.name!='FILE_SHA256_MANIFEST.json']})
print(json.dumps({'uid':d['uid'],'delivery':str(BASE/'FINAL_DELIVERY.json'),'sha256':sha(BASE/'FINAL_DELIVERY.json'),'selectedNative':6,'poses':72,'measuredMuzzles':4},indent=2))
