from pathlib import Path
import json,hashlib,shutil,re
base=Path('/workspace/cqc-pass19-gekko-right-generation');runtime=base/'runtime';app=Path('/tmp/cqc-pass19-application/public/cqc');cat=json.load(open(base/'INDEPENDENT_TWO_FACE_NATIVE_RIGS_V1.json'));rigs={r['id']:r for r in cat['machines']};old=Path('/tmp/cqc-pass19-gekko-generation/integration-candidate-v3/src/cqc-pass19-machine-source-points.js').read_text();a=old.index(' const points=')+len(' const points=');b=old.index(';\n const equal=',a);points=json.loads(old[a:b])
points.update({'pass19__gekko_missile_mgs4_right':{'missile':{'part':'paired_missile_pod','nativeXY':[406,1081],'kind':'upper missile-tube mouth'},'missileLower':{'part':'paired_missile_pod','nativeXY':[393,1174],'kind':'lower missile-tube mouth'},'ballistic':{'part':'machinegun','nativeXY':[1233,68],'kind':'machinegun barrel mouth'}},'pass19__gekko_mgr_right':{'ballistic':{'part':'machinegun','nativeXY':[1374,84],'kind':'machinegun barrel mouth'}}})
for id,slots in points.items():
 m=rigs[id]
 for point in slots.values():
  part=next(p for p in m['parts']if p['id']==point['part']);source=next(s for s in m['sources']if s['id']==part['source']);point['pin']={'machine':id,'part':point['part'],'source':source,'rect':part['rect'],'pivot':part['pivot'],'imageScale':part['imageScale']}
s=old[:a]+json.dumps(points,separators=(',',':'))+old[b:];(runtime/'src/cqc-pass19-machine-source-points.js').write_text(s)
bridge=app/'src/cqc-pass18-machine-bridge.js';s=bridge.read_text();old="face===1?'left-source projection; independent reverse source pending':'native left-source camera'";new="face===1?(id.endsWith('_right')?'native independently rendered right-source camera':'left-source projection; independent reverse source pending'):'native left-source camera'";assert s.count(old)==1;s=s.replace(old,new);(runtime/'src/cqc-pass18-machine-bridge.js').write_text(s)
install='''/* Guarded additive upgrade from five left-only mappings to independent two-face native sources. */
(function(root){'use strict';
 const addition=root.CQC_PASS19_GEKKO_CATALOG,extra=root.CQC_PASS19_GEKKO_DATA,base=root.CQC_MACHINE_PARTS_CATALOG,data=root.CQC_PASS18_MACHINE_DATA;
 if(!addition||!extra||!base||!data||addition.schema!==base.schema)throw Error('Dossiers natifs Gekko indisponibles');
 const old=new Map(base.machines.map(m=>[m.id,m])),fresh=[];
 for(const rig of addition.machines){const exists=old.get(rig.id);if(exists){if(JSON.stringify(exists)!==JSON.stringify(rig))throw Error('Rig Gekko incompatible: '+rig.id);}else fresh.push(rig);}
 for(const [uid,pair]of Object.entries(extra.playable)){const before=data.playable?.[uid];if(before&&JSON.stringify(before)!==JSON.stringify(pair)&&!(JSON.stringify(before)===JSON.stringify([uid,uid])&&JSON.stringify(pair)===JSON.stringify([uid,uid+'_right'])))throw Error('UID Gekko déjà attribué: '+uid);}
 const states={...data.states};for(const [id,state]of Object.entries(extra.states)){if(!states[id])states[id]=state;}
 root.CQC_MACHINE_PARTS_CATALOG={...base,machines:[...base.machines,...fresh]};
 root.CQC_PASS18_MACHINE_DATA={...data,playable:{...data.playable,...extra.playable},states};
})(globalThis);
''';(runtime/'src/cqc-pass19-gekko-install.js').write_text(install)
# Fixed QA input supports ten independently decoded rigs; game cache defaults remain untouched.
fixture=Path('/tmp/cqc-pass19-gekko-generation/runtime/integration-review.html').read_text().replace('integration-src/','src/');fixture=fixture.replace('<script src="src/cqc-pass18-machine-bridge.js"></script>','<script>window.module={exports:{}};</script><script src="src/cqc-pass18-machine-bridge.js"></script><script>CQC_PASS18_MACHINES.dispose();window.CQC_PASS18_MACHINES=module.exports.createBridge({maxRigs:12,maxDecodedBytes:220*1024*1024,rendererOptions:{baseURL:location.href}});delete window.module;</script>');fixture=fixture.replace("const face=j?1:-1;","const face=j?1:-1;").replace("face===1?' : original left source pending reverse':' : native left source'","face===1?' : independent native right source':' : native left source'");fixture=fixture.replace("pose={action,frame:13,phaseProgress:.5,...options}","pose={...(action?{action}:{}),frame:13,phaseProgress:.5,...options}");(runtime/'integration-review.html').write_text(fixture)
anchor=Path('/tmp/cqc-pass19-gekko-generation/runtime/source-anchor-review.html').read_text().replace('integration-src/','src/');a=anchor.index('rows=[');b=anchor.index('];window.anchorReady',a);rows=[{'uid':'pass19__gekko_missile_mgs4_right','file':'gekko-missile-mgs4-right-parts-v1.png','slots':['missile','missileLower'],'rect':[35,1010,405,220],'box':[20,80,820,500]},{'uid':'pass19__gekko_missile_mgs4_right','file':'gekko-missile-mgs4-right-parts-v1.png','slots':['ballistic'],'rect':[950,40,310,280],'box':[900,90,850,540]},{'uid':'pass19__gekko_mgr_right','file':'gekko-mgr-right-parts-v1.png','slots':['ballistic'],'rect':[1010,50,390,230],'box':[450,640,760,430]}];anchor=anchor[:a]+'rows='+json.dumps(rows,separators=(',',':'))+anchor[b+1:];(runtime/'source-anchor-review.html').write_text(anchor)
print(json.dumps({'rootBridgeGuardSHA256':hashlib.sha256(bridge.read_bytes()).hexdigest(),'candidateBridgeSHA256':hashlib.sha256((runtime/'src'/bridge.name).read_bytes()).hexdigest(),'rootCorrectedPoseSHA256':hashlib.sha256((runtime/'src/cqc-pass19-gekko-poses.js').read_bytes()).hexdigest(),'newPointDescriptors':sum(len(s)for s in points.values())}))
