from pathlib import Path
import json,hashlib,shutil,datetime
b=Path('/workspace/cqc-pass19-gekko-right-generation');r=b/'runtime';a=Path('/tmp/cqc-pass19-application/public/cqc');out=b/'integration-candidate-v1';(out/'src').mkdir(parents=True,exist_ok=True)
def pin(p):
 data=p.read_bytes();return {'path':str(p),'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()}
names=['cqc-pass18-machine-bridge.js','cqc-pass19-gekko-catalog.js','cqc-pass19-gekko-install.js','cqc-pass19-machine-source-points.js']
replacements=[]
for n in names:
 src=r/'src'/n;dst=out/'src'/n
 if dst.exists():assert pin(src)['sha256']==pin(dst)['sha256']
 else:shutil.copyfile(src,dst);dst.chmod(0o400)
 q=pin(dst);q.update({'candidate':q.pop('path'),'candidateSHA256':q.pop('sha256'),'destination':str(a/'src'/n),'expectedBeforeSHA256':pin(a/'src'/n)['sha256']});replacements.append(q)
pose=pin(a/'src/cqc-pass19-gekko-poses.js');assert pose['sha256']=='aad2203738e8ddf3159e39f1541fab549a2edf7126474dd482df81d2837ffcc3';assert pose['sha256']==pin(r/'src/cqc-pass19-gekko-poses.js')['sha256']
sources=[];existing=[]
for p in sorted((r/'assets/machines-pass19').glob('*.png')):
 dst=a/'assets/machines-pass19'/p.name;q=pin(p);q.update({'candidate':q.pop('path'),'candidateSHA256':q.pop('sha256'),'destination':str(dst),'expectedDestinationState':'present-identical' if dst.exists() else 'absent','expectedBeforeSHA256':pin(dst)['sha256'] if dst.exists() else None});assert not dst.exists() or q['candidateSHA256']==q['expectedBeforeSHA256'];(existing if dst.exists() else sources).append(q)
qa=pin(b/'qa/INDEPENDENT_RIGHT_BRIDGE_ACTUAL_BROWSER_QA_V5.json');report=json.load(open(qa['path']));assert report['status']=='passed' and len(report['screenshots'])==18
plan={'schema':'cqc.pass19.guarded-independent-two-face-integration/1','createdAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'appRoot':str(a),'noHTMLMutations':True,'replacementFiles':replacements,'nativeSources':sources,'existingNativeSourcesPreserved':existing,'poseFilePreservedUnchangedGuard':pose,'rendererReplacementNeeded':False,'rendererGuard':pin(a/'src/cqc-machine-parts-renderer-v1.js'),'catalogCounts':{'before':55,'after':60,'maximum':64,'newRightRigs':5,'partsAcrossTwoFaces':134},'scriptInsertionOrderInstructions':['Existing base machine catalog','Existing pass16 catalog','Existing pass18 catalog','Replaced pass19 Gekko catalog','Root pose aad220 remains byte-exact','Replaced pass19 pinned source-point module','Replaced guarded pass19 Gekko install','Replaced pass18 bridge','Existing world-scale/costume/VFX wrappers afterward'],'actualQAPins':[qa,pin(b/'qa/INDEPENDENT_RIGHT_PINNED_GUARDS_ACTUAL_V1.json')],'nativeVisualReview':['Physically viewed V5 IDLE/FIRE and V2 native source-port zooms; independent right camera for all five, no mirrored PNG or global 180 degree turn.','Right missile visible-side mount uses actual canonical released-game right-view placement; mouths [406,1081] and [393,1174], machinegun [1233,68]; MGR machinegun [1374,84].','Trenchcoat has exactly three concealed machines, long separately articulated sleeves and native joint pivots, opposite-camera new garment; combined distal leg/hand pieces retain true native wrist pivots.','Source drawing fidelity is reviewed approximation with attested visible anatomy; absolute 1:1 and hidden views are not certified.'],'sourcePointAPI':{'world':'CQC_PASS18_MACHINES.playableSourcePoint(uid,slot,x,y,face,exactAppliedScale,pose,{displayHeight})','rig':'CQC_PASS18_MACHINES.rigSourcePoint(uid,slot,face,pose)','slots':['missile','missileLower','ballistic'],'independentRightSourceNowSelected':True,'uniformScaleOnlyOnce':True,'simulationAndSpatialMutation':False,'displayHeightFallback':450},'baselinePreservation':['All existing55 machine object references and state references retained','Existing arsenal/mgr references and all body/HP/detachment fields unchanged','Existing damage channel names and 67parts per camera retained'],'browserQAQualification':{'draws':170,'states':17,'screenshots':18,'rootVSFlagsExercised':True,'QAOnlyCacheCapacityOverride':{'maxRigs':12,'maxDecodedBytes':230686720},'gameCacheDefaultsChanged':False},'rootOwnsImportAndPublication':True}
p=out/'GUARDED_APP_INDEPENDENT_RIGHT_INTEGRATION_PLAN_V1.json';p.write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n');p.chmod(0o400)
for p in [b/'INDEPENDENT_TWO_FACE_NATIVE_RIGS_V1.json',b/'INDEPENDENT_TWO_FACE_PRESENTATION_MAPS_V1.json']+[r/'src'/n for n in names]:p.chmod(0o400)
print(json.dumps({'plan':str(p),'frozenPlan':pin(out/'GUARDED_APP_INDEPENDENT_RIGHT_INTEGRATION_PLAN_V1.json'),'newNativeSources':len(sources),'nativeBytes':sum(s['bytes']for s in sources),'candidateSHAs':{Path(q['candidate']).name:q['candidateSHA256']for q in replacements}}))
