"""New PASS9 Red Blaster preparation only; original documents remain intact."""
from pathlib import Path
from datetime import datetime,timezone
import os,json,hashlib,shutil

BASE=Path(__file__).resolve().parents[1]
SOURCE=Path('/workspace/cqc-pass8-reference-selection/core__redblaster_mg2')
for name in ['references','prepared-prompts-original','original-reference-preparation','prompts','native-attempts','metadata','rejects','sources','layouts']:
 (BASE/name).mkdir(parents=True,exist_ok=True)
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def write(path,data):
 with path.open('x',encoding='utf-8')as f:json.dump(data,f,ensure_ascii=False,indent=2);f.write('\n')
original=json.loads((SOURCE/'SOURCE_CONTRACT.json').read_text())
for name in ['SOURCE_CONTRACT.json','PROFILE_SNAPSHOT.json','COMBAT_PROFILE_SNAPSHOT.json','FINISHER_PROFILE_SNAPSHOT.json','CHRONICLE_PROFILE_SNAPSHOT.json','CHRONICLE_STORY_SNAPSHOT.json']:
 (BASE/'original-reference-preparation'/name).write_bytes((SOURCE/name).read_bytes())
for q in (SOURCE/'reviewable-prompts').glob('*.args.json'):
 (BASE/'prepared-prompts-original'/q.name).write_bytes(q.read_bytes())
references=[]
for name in ['manual-original1990-page42.png','red-blaster-msx2-original-sprite.webp','lp26-30-Metal_Gear_2_0470.png','lp26-33-Metal_Gear_2_0471.png','lp26-34-Metal_Gear_2_0479.png','lp26-31-Metal_Gear_2_0472.png']:
 old=SOURCE/name;new=BASE/'references'/name;ref=next(r for r in original['references']if r['file']==name)
 assert sha(old)==ref['sha256']and old.stat().st_size==ref['bytes']
 os.link(old,new)
 references.append({'file':str(new),'source':str(old),'bytes':ref['bytes'],'sha256':ref['sha256'],'url':ref['url'],'authority':ref['authority'],'physicallyViewedByProducer':True,'viewedAt':datetime.now(timezone.utc).isoformat(),'preservedByImmutableHardlink':True})
semantics={
 'A':['idle ready1','idle ready2','walk step1','walk step2','walk step3','walk step4','unarmed guard preparation','unarmed held guard','lower crouch','held crouch','rising jump','tucked jump'],
 'B':['jab preparation','jab extension','jab recovery','strong unarmed strike preparation','strong unarmed strike extension','strong unarmed strike recovery','low sweep preparation','low sweep extension','low sweep recovery','backward hit recoil','kneeling KO collapse','complete lying KO'],
 'C':['qualified small hand-grenade throw preparation','first active grenade hand-release','empty-hand throw recovery','low wire placement preparation','first active low-hand white-wire placement','wire placement reset','adapted unarmed grab preparation','adapted unarmed throw followthrough','throw reset','planted recovery preparation','steady breath','return to ready stance']}
contract={'schema':'cqc.pass9.red-blaster-source-and-action-contract/1','uid':'core__redblaster_mg2','name':'RED BLASTER','selectedCostume':'closest-supported-original1990-msx2-green-uniform-ochre-extremities','referenceContractFile':str(BASE/'original-reference-preparation/SOURCE_CONTRACT.json'),'referenceContractSHA256':sha(SOURCE/'SOURCE_CONTRACT.json'),'references':references,'target':'1:1 original1990 MSX2 palette/silhouette where visible, closest_supported elsewhere','absolute1to1Certified':False,'paletteObserved':'Tiny original sprite and gallery screenshots show green compact body/limbs with dark outlines and ochre hands/feet/head; no red uniform or Running Man grey chest patch supported. Fine cloth/head/face detail unresolved.','localizationQualification':'English LP text and original-era MSX2 sprites; translation patch/emulator/ROM unverified, not certified unmodified Japanese1990 execution. Tiny sprite extracted-native provenance and enlargement unverified. Japanese manual page42 separately supports original name/lore.','poseSemantics':semantics,'rootPoseRevision':'Prepared original triplet prompts preserved byte-for-byte; fresh complete-runtime A idle2/walk4/guard2/crouch2/jump2 and B punch3/heavy3/low3/hit1/ko2 variants. C grenade3/wire3/adaptedThrow3/recovery3.','weaponInterpretation':'Grenades/explosive sabotage and crossed immobilizing wires source-supported. Exact grenade launcher and canister/fuze/hardware model unresolved. Restrained connected hand-grenade and low wire placement are expressly authored versus interpretations, not exact original firing animation/model. No firearm model asserted.','manualLoreQualification':'Original Japanese page42 describes study at Leningrad University, SPETSNAZ background, explosive sabotage and grenades. No Bergen biography or unrelated later-era lore is introduced.','unsupportedGearExcluded':['modern pistol','flamethrower','Fatman rollers/bomber suit','C4 vest','launcher model invented as canon','player HUD pistol/ration/grenade model as enemy equipment'],'contactAndGameplayQualification':'Normal strikes, guard/crouch/jump, CQC throw, hit/KO, hand-grenade throw and wire-placement motions, collision/timing and balance are bounded versus adaptations. No stage/gas/tripwire game implementation here.','displayHeight':225,'nativeCombatOrigins':{'right':{},'left':{}},'budget':{'initialMiB':25,'maximumMiB':45,'pauseAndNotifyAboveMaximum':True,'pauseGenerationIfGlobalFreeBytesBelow':104857600,'noHistoricalDeletion':True},'runtimeImported':False,'rootOrShadowSourceModified':False}
write(BASE/'SOURCE_AND_ACTION_CONTRACT.json',contract)
visual='''Create a new native full-body 2D combat sprite atlas guided by the attached ORIGINAL1990 MSX2 Red Blaster reference sprites. The small green figure in the elevated dark gallery is Red Blaster, not the player character or the HUD pistol. Reconstruct the supported compact green-clad adult human silhouette, plain green shirt and trousers/limbs with simple dark outlines, understated small dark/ochre head and ochre/brown extremities. The name does not justify a red uniform. No grey shoulder/chest armour stripe; that is another character. Avoid inventing costume seams, tactical pouches, named headwear, facial identity or hidden asymmetry. Small unobtrusive cloth/head details are merely readability interpretations. Crisp consistent retro pixel-sprite style, same character scale in every pose, not photorealistic modern commando, not an enlargement/copy of source pixels.
This is an authored Versus reconstruction, closest_supported wherever tiny originals cannot resolve detail. No gun/pistol/flamethrower, named grenade launcher, C4 vest, Fatman rollers, bomber suit, unsupported armour/helmet or HUD item. A/B entirely unarmed. For C only, a tiny restrained hand grenade and low thin white wire may be present where described: source grenades/wires are supported but exact models and hand animations are qualified adaptations. Keep all props connected to the hand/body; no detached projectile, explosion, trailing VFX, star, extra body or stage wire.
TRUE RGBA transparent background, complete solid body/cloth, alpha0 outside actors. No opaque backdrop, gradient, glow, shadow floor, checkerboard, caption, grid border, text, watermark or stage. Exactly FOUR columns by THREE rows,12 separate COMPLETE full-body poses in row-major0..11 order. Every complete hand, foot and prop belongs to one clear silhouette, large transparent gaps between neighbors. Fit each entire pose inside its spacious cell with at least24px empty margin. No clipping and no detached spare parts.'''
descriptions={
 'A':'''Exact order:0 calm ready idle;1 subtly different breathing ready idle;2 forward walk step1;3 alternate walk step2;4 forward walk step3;5 planted walk step4;6 open unarmed guard preparation;7 held unarmed guard;8 lowering crouch;9 held crouch with all boots/hands visible;10 upward rising jump with whole feet visible;11 tucked airborne jump with full body. Never replace the last two jumps with crouches. All twelve poses face the specified anatomical direction.''',
 'B':'''Exact order:0 unarmed jab preparation;1 fully extended unarmed jab;2 jab recovery;3 stronger unarmed strike windup;4 long strong hand strike extension;5 recovery;6 low leg sweep preparation;7 low sweep extension with full leg/boot;8 low sweep recovery;9 complete backward hit recoil;10 full kneeling KO collapse with both legs and hands complete;11 completely lying defeated adult body, all limbs/head/boots within one cell. The last three are hit/KO, never jumps or extra attacks. All12 face the specified direction including striking arms and low boot.''',
 'C':'''Exact order:0 grenade-throw preparation, tiny dark/green unbranded grenade restrained and connected in rear throwing hand;1 first active hand-grenade release posture, front throwing hand extends toward the specified direction with small grenade still touching the open hand for a native launch anchor, no detached projectile;2 balanced empty-hand recovery;3 low wire-placement preparation, crouched with hands low;4 first active low hand reaching forward, a SHORT thin white wire segment attached directly to the fingers near the ground, no separate explosive/device/coil box or stage wire;5 low wire-placement reset;6 unarmed open-hand adapted grab preparation without victim;7 unarmed throw follow-through with empty hands;8 unarmed reset;9 planted athletic breathing recovery preparation;10 stationary steady breath with both boots grounded;11 stationary return to ready stance. Frames9-11 MUST NOT run, stride or jump. Grenade/wire motions are qualified Versus interpretations, no firearm model or canonical original hand animation claimed.'''}
refpaths=[str(BASE/'references'/name)for name in ['red-blaster-msx2-original-sprite.webp','lp26-30-Metal_Gear_2_0470.png','lp26-33-Metal_Gear_2_0471.png']]
for group in 'ABC':
 for facing in ['RIGHT','LEFT']:
  name=f'{group}_{facing}_01'
  args={'prompt':visual+'\n\nProduce '+name+'. EVERY POSE anatomically faces '+facing+'. Independently author this facing from the original game references; never mirror any generated sheet or copy poses from another facing.\n'+descriptions[group],'referenced_image_paths':refpaths,'transparent_background':True}
  write(BASE/'prompts'/(name+'.args.json'),args)
  write(BASE/'prompts'/(name+'.generation-context.json'),{'schema':'cqc.pass9.native-prompt-context/1','name':name,'uid':contract['uid'],'sourceContractSHA256':sha(BASE/'SOURCE_AND_ACTION_CONTRACT.json'),'originalPreparedPromptFile':str(BASE/'prepared-prompts-original'/(group+'_'+facing+'.args.json')),'originalPreparedPromptSHA256':sha(BASE/'prepared-prompts-original'/(group+'_'+facing+'.args.json')),'newSeparateVariant':True,'rootApprovedRuntimeCoverage':True,'sourceReferencesPhysicallyViewedBeforeGeneration':True,'originalSourcePixelsNotModified':True})
register=Path('/workspace/cqc-pass9-generation/running-man/tools/register_native_attempt.py')
(BASE/'tools'/'register_native_attempt.py').write_bytes(register.read_bytes())
write(BASE/'PREPARATION_RECEIPT.json',{'sourceContractSHA256':sha(BASE/'SOURCE_AND_ACTION_CONTRACT.json'),'originalContractSHA256':sha(SOURCE/'SOURCE_CONTRACT.json'),'referenceBytes':sum(r['bytes']for r in references),'fullManualCopied':False,'fullLPVideoCopied':False,'refsPhysicallyViewed':6,'sixOriginalPreparedPromptsRetained':True,'sixNewCompleteRuntimeVariants':True,'globalFreeBytesAtPreparation':shutil.disk_usage('/workspace').free,'newNativeImagesProduced':0,'rootR_S_PASS8Modified':False})
print(json.dumps({'base':str(BASE),'contractSHA256':sha(BASE/'SOURCE_AND_ACTION_CONTRACT.json'),'refs':len(references),'referenceBytes':sum(r['bytes']for r in references),'freeBytes':shutil.disk_usage('/workspace').free}))
