from pathlib import Path
from PIL import Image
from scipy import ndimage
import numpy as np
import json,hashlib
B=Path(__file__).parent
UID='core__pain'
GAME='Metal Gear Solid 3: Snake Eater (2004)'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(name,d):
 p=B/name;p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n');return str(p)
video='https://archive.org/download/PS2_Longplay-001-Metal_Gear_Solid_3-Snake_Eater/PS2_Longplay-001-Metal_Gear_Solid_3-Snake_Eater.mp4'
refs=[]
for name,url,kind,role in [
 ('art-0006-original-shinkawa.jpg','https://www.metalgearsolid.be/images/mgs3_art_0006.jpg','official-art-reference','Original Yoji Shinkawa MGS3 drawing: broad masked figure, hornets, costume mass; monochrome is not color authority.'),
 ('konami-pain-native-decoded.png','https://www.konami.com/mg/archive/mgs3/english/pic/chara_pain_pic.gif','official-original-model-reference','Original Konami color model: black balaclava, charcoal FULL long sleeves/black gloves and boots, ochre vest/cartridges, rear ochre equipment. Native first-frame ffmpeg decode retained beside original GIF; no resize/repaint.'),
 ('ps2-pain-10964.png',video+'#t=10964','original-game-capture','Original masked first-phase frontal body with ochre front, charcoal long sleeves; original model geometry and palette supplement.'),
 ('ps2-pain-10970.png',video+'#t=10970','original-game-capture','Original first-phase masked side/back shoulders and ochre rear vest/equipment, extended gloved arm directing swarms.'),
 ('ps2-pain-10975.png',video+'#t=10975','original-game-capture','Original masked face, high open ochre collar and compact upright cartridge arrangement; exact fine counts/seams not all certified at sprite scale.'),
 ('ps2-pain-10983.png',video+'#t=10983','original-game-capture','Original first-phase wide grounded stance with both arms extended, dark full sleeves, covered face and ochre vest. Gesture basis for authored control frames.'),
 ('ps2-pain-11030.png',video+'#t=11030','original-game-capture','Original phase-one masked boss on cave central rock amid thin hornet swarm. No physical gun extracted from this view.'),
 ('ps2-pain-11110.png',video+'#t=11110','original-game-capture','Original phase-one dense natural hornet shell around body; no fire/telekinesis. Caption Grenade describes source-game command, not a new physical pistol.'),
 ('ps2-pain-11170.png',video+'#t=11170','original-game-capture','Original dense hornet shell and blocked body; supplemental swarm source, not hidden equipment authority.'),
 ('ps2-pain-11210.png',video+'#t=11210','original-game-capture','Phase TWO reference EXCLUDED from six selected sheets: balaclava removed, bald disfigured face. Demonstrates incompatible incarnation phase.'),
 ('ps2-pain-11213.png',video+'#t=11213','original-game-capture','Phase TWO uncovered head, original dark sleeves/gloves. Excluded facial state, corroborates no bare arms.'),
 ('ps2-pain-11216.png',video+'#t=11216','original-game-capture','Phase TWO mouth-open Bullet Bee attack emits orange-red streaks from uncovered face. EXCLUDED mouth/Bullet Bee visual from masked first-phase delivery.'),
 ('ps2-pain-11220.png',video+'#t=11220','original-game-capture','Phase TWO Bullet Bee orange-red outgoing trace; explicitly not a phase-one open-palm canonical Bullet Bee.'),
]:
 p=B/'references'/name;im=Image.open(p);refs.append({'file':str(p),'url':url,'sha256':sha(p),'bytes':p.stat().st_size,'width':im.width,'height':im.height,'sourceKind':kind,'role':role,'incarnation':GAME+', original PS2 design','viewed':True,'originNote':'External archive original-model/cutscene recording explicitly labelled PS2 Snake Eater and deposited in 2011, before HD remake and Delta. Console hardware framebuffer/color is not independently certified.' if kind=='original-game-capture' else 'Publisher original model or original drawing; no Delta/re-design accepted.'})
limits=[
 'Target is 1:1 original 2004 PS2 design where physically viewed evidence supports it. New detailed 2D art/poses are authored adaptations of a low-resolution 3D game, not extracted PS2 sprites or certified absolute identity. Fidelity status closest_supported.',
 'All 72 poses use original FIRST PHASE BLACK BALACLAVA. Original Bullet Bee starts in phase two after removing this mask (source11210/11216). Existing specialForward must be documented as an authored accelerated hornet swarm from an open gloved hand if these sheets are used; it is not canonical mouth Bullet Bee. No second-phase face or oral origin is mixed into this costume.',
 'Original long black/charcoal sleeves, black gloves, ochre vest, cartridge detail and plain black boots are present. The monochrome artwork alone can suggest bare arms; official original color model and actual PS2 captures override that interpretation.',
 'Fine cartridge counts, hidden seams, stitching and precise pouch/backpack placement on occluded anatomical sides cannot be certified 1:1 from these limited low-resolution viewpoints. Native both-facing sheets contain conservatively interpreted ochre rear/hip equipment; no unique exclusively left/right pouch fact is claimed. No runtime mirror or pixel reflection is used.',
 'Game-source captures show original control with gloved arms extended and hornets around the body. Forward glove/palm anchors are authored precise Versus spawn points for readability, not a claim that original hornets canonically materialize from the palm. Original hornets control, no guns, magical fire or psychic beam added.',
 'Normal punches/sweep/grapple, walk/guard/crouch/jump, hit/KO, shield pose, recover and exact move phase timings are existing CQC adaptations, not source-extracted original boss combat. The single optic pose is inspection/survey gesture, not a new lore power. specialBack uses authored existing walking retreat, no flight.',
 'displayHeight240 and fixed per-source standing heights are authored simulator geometry/readability suggestions, not original certified centimetres. Runtime human hurtbox, positive scale and all phases/facings remain independently integrator-tested.',
 'Native PNG bytes are untouched, true alpha and twelve major body components per sheet. Alpha<=80 residual isolated/fringe pixels including outside useful body contours exist, and are not destructively cleared. Existing Canvas contour crop must select the twelve reviewed bodies rather than claim perfectly noise-free original pixels.',
 'Hornet prop cloud atlas contains three authored wing perspectives of ordinary hornets, seven insects per cloud. Larger swarm behavior/individual insect dimensions cannot be 1:1 extracted at source resolution; no orange/red Bullet Bee mouth trace is imported into first phase.',
 'Unselected timeline searches and four repeated/unsuitable Part2 seek frames are retained but never used as canonical character proof. No complete movie downloaded; native ffmpeg single frames and original archive metadata preserved.'
]
layout={
 'idle':{'sheet':'a','indices':[0,1],'fps':4,'loop':True},'walk':{'sheet':'a','indices':[2,3,4,5],'fps':8,'loop':True},'guard':{'sheet':'a','indices':[6,7],'fps':4,'loop':True},'crouch':{'sheet':'a','indices':[8,9],'fps':4,'loop':True},'jump':{'sheet':'a','indices':[10,11],'fps':5,'loop':False},
 'punch':{'sheet':'b','indices':[0,1,2],'fps':12,'loop':False},'heavy':{'sheet':'b','indices':[3,4,5],'fps':10,'loop':False},'low':{'sheet':'b','indices':[6,7,8],'fps':10,'loop':False},'hit':{'sheet':'b','indices':[9],'fps':0,'loop':False},'ko':{'sheet':'b','indices':[10,11],'fps':6,'loop':False},
 'throw':{'sheet':'c','indices':[0,1],'fps':9,'loop':False},'shoot':{'sheet':'c','indices':[2,3,4],'fps':10,'loop':False},'deploy':{'sheet':'c','indices':[5,6],'fps':8,'loop':False},'optic':{'sheet':'c','indices':[7],'fps':0,'loop':False},'recover':{'sheet':'c','indices':[8,9],'fps':5,'loop':False},'charge':{'sheet':'c','indices':[10,11],'fps':9,'loop':False}}
slots={'light':'punch','heavy':'heavy','low':'low','throw':'throw','special':'shoot','specialDown':'deploy','specialForward':'shoot','specialBack':'walk','super':'charge','utility':'recover'}
phase={k:{'startup':[0],'active':[1],'recovery':[2]} for k in ['punch','heavy','low','shoot']}
phase.update({k:{'startup':[0],'active':[1],'recovery':[0]} for k in ['throw','deploy','charge']})
phase['optic']={'startup':[0],'active':[0],'recovery':[0]};phase['recover']={'startup':[0],'active':[1],'recovery':[1]};phase['walk']={'startup':[0],'active':[1,2],'recovery':[3]}
final=[];attempts=[]
for key in ['a-right','a-left','b-right','b-left','c-right','c-left']:
 name=key.upper().replace('-','_')+'_01';p=B/'native-attempts'/(name+'.png');im=Image.open(p);m=json.loads((B/'metadata'/(name+'.result-summary.json')).read_text());inspect=json.loads((B/'inspections'/(name+'.components.json')).read_text());hs=[x['rect'][3] for x in inspect['components']];stand=round(sum(hs[:2])/2)
 row={'source':str(p),'nativeOriginal':m['nativeOriginal'],'sha256':sha(p),'bytes':p.stat().st_size,'width':im.width,'height':im.height,'key':key,'columns':4,'rows':3,'poseCount':12,'facing':1 if key.endswith('right') else -1,'mirror':False,'inspection':str(B/'inspections'/(name+'.components.json')),'observedBodyHeights':hs,'standingSourceHeight':stand};assert sha(m['nativeOriginal'])==row['sha256'];final.append(row);attempts.append({**row,'status':'approved-final'})
review={'uid':UID,'incarnation':'Original MGS3 (2004) PS2 The Pain / Cobra Unit FIRST PHASE black balaclava','status':'approved','reviewer':'pass6_pain_native / producer physical source and seven-native-image review','reviewedAt':'2026-10-02','sourceKind':'original-game-capture','absolute1to1Certified':False,'fidelityStatus':'closest_supported','target':'1:1 original MGS3 original PS2 appearance within physically inspected evidence; first-phase mask only.','checks':{'identity':True,'costume':True,'equipment':True,'anatomicalSides':True,'singleFigure':True,'transparentBackground':True},'sources':refs,'limits':limits,'sourcePriority':['Konami original MGS3 color model','Original labelled PS2 Snake Eater gameplay/cutscenes','Original Shinkawa drawing shape only']}
write('CANONICAL_REVIEW.json',review)
marks={}
for side,points in [('right',{'shoot':[1412,74],'charge':[1406,795]}),('left',{'shoot':[1087,90],'charge':[1092,838]})]:
 row=next(r for r in final if r['key']=='c-'+side);im=Image.open(row['source']);marks[side]={}
 for action,point in points.items():
  rgba=list(im.getpixel(tuple(point)));assert rgba[3]>80
  marks[side][action]={'action':action,'frame':1,'sourcePoseIndex':3 if action=='shoot' else 11,'file':'assets/combat-sprites/'+UID+'/c-'+side+'-v1.png','source':row['source'],'sha256':row['sha256'],'point':point,'pointRGBA':rgba,'note':'Forward open gloved hand visible native alpha, first active phase. Authored Versus swarm source point, not original emergence fact. specialForward shares shoot; super uses charge. Never oral Bullet Bee in masked costume.'}
write('SOURCE_COMBAT_ORIGINS.json',{'uid':UID,'schema':'cqc.pass6.native-source-combat-marks/1','coordinateSystem':'Native full-sheet PNG x,y, no resize/flip. frame indexes local action group; sourcePoseIndex is fullsheet zero-based pose.','slotSourceGroups':{'special':'shoot','specialForward':'shoot','super':'charge'},'marks':marks,'sourceIncarnation':'FIRST PHASE black balaclava; second-phase oral Bullet Bee excluded'})
prop=B/'native-attempts/HORNET_PROPS_01.png';im=Image.open(prop);m=json.loads((B/'metadata/HORNET_PROPS_01.result-summary.json').read_text());a=np.asarray(im.getchannel('A'));props=[]
for i,key in enumerate(['wings-up','wings-level','wings-down']):
 lo=round(i*im.width/3);hi=round((i+1)*im.width/3);yy,xx=np.where(a[:,lo:hi]>=8);rect=[max(lo+int(xx.min())-4,lo),max(int(yy.min())-4,0),min(lo+int(xx.max())+5,hi),min(int(yy.max())+5,im.height)];rect=[rect[0],rect[1],rect[2]-rect[0],rect[3]-rect[1]];sub=a[rect[1]:rect[1]+rect[3],rect[0]:rect[0]+rect[2]];props.append({'id':key,'rect':rect,'pivot':[.5,.5],'suggestedDisplayWidth':48,'opaquePixels':int((sub>=80).sum()),'insectCountPhysicallyReviewed':7})
propdoc={'schema':'cqc.native-source-prop-atlas/1','uid':UID,'kind':'hornet-swarm','source':str(prop),'nativeOriginal':m['nativeOriginal'],'sha256':sha(prop),'bytes':prop.stat().st_size,'width':im.width,'height':im.height,'transparentBackground':True,'untouchedNativeSource':True,'fidelityStatus':'closest_supported','absolute1to1Certified':False,'props':props,'limits':['Three sparse clouds of seven natural dark ochre/black hornets, independent wing angles, no fire/glowing ball. Source species/fine leg count unavailable in low resolution and conservatively interpreted.','Each prop rect encloses a multi-component native insect cloud; renderer must preserve aspect ratio. Suggested48px width is authored readability scale only, projectile collision remains separate.','Native hidden RGB/fringe pixels retained; alpha>=8+4px crop is metadata only, never source editing. First-phase swarm art excludes phase-two Bullet Bee mouth rays.'],'sourceReferences':refs[:2]+[r for r in refs if 'shell' in r['role']]}
assert sha(propdoc['nativeOriginal'])==propdoc['sha256'];write('NATIVE_HORNET_PROP_ATLAS.json',propdoc);attempts.append({'key':'hornet-props','source':str(prop),'nativeOriginal':m['nativeOriginal'],'sha256':sha(prop),'status':'approved-additional-prop'})
write('NATIVE_PNG_INDEX.json',{'uid':UID,'attempts':attempts,'nativeImages':7,'approvedBodySheets':6,'poses':72,'rejects':0})
write('SOURCE_AND_ACTION_CONTRACT.json',{'uid':UID,'incarnation':GAME+' original PS2 FIRST PHASE mask','sourceBank':str(B/'CANONICAL_REVIEW.json'),'noRuntimeEdits':True,'actionMap':slots,'actionLayout':layout,'phaseMap':phase,'poseCount':72,'independentFacings':True,'mirror':False,'phaseSemantics':{'shoot':'open forward glove control preparation / open forward extended glove / hand retraction. special and specialForward share exactly one three-pose group','charge':'two-palms swarm barrage preparation / open forward palm barrage; no mouth','deploy':'arms open screen preparation / palms forward barrier control','recover':'settled breath / restored standing posture, existing utility adaptation'},'excluded':'Original phase-two bare disfigured face and mouth Bullet Bee are not selected.'})
delivery={'schema':'cqc.native-combat-delivery/1','uid':UID,'name':'THE PAIN','game':GAME,'incarnation':'Original MGS3 PS2 The Pain / Cobra Unit first-phase black balaclava','selectedCostume':'Original covered dark balaclava, charcoal full long sleeves and trousers, ochre vest/cartridges/rear equipment, black gloves and plain black boots','basis':'Original hornet swarm control and insect barrier; authored masked first-phase accelerated swarm replaces any incompatible oral phase-two Bullet Bee depiction. No physical gun or magical psychic beam.','displayHeight':240,'coverage':'action-frames','facing':1,'mirror':False,'sourceFiles':final,'actionLayout':layout,'actionMap':slots,'phaseMap':phase,'review':review,'nativeSourceCombatOrigins':str(B/'SOURCE_COMBAT_ORIGINS.json'),'additionalNativePropAtlas':str(B/'NATIVE_HORNET_PROP_ATLAS.json'),'limits':limits}
write('FINAL_DELIVERY.json',delivery)
allrefs=[]
for p in sorted((B/'references').glob('*')):
 if p.is_file():allrefs.append({'file':str(p),'bytes':p.stat().st_size,'sha256':sha(p),'selectedCanonical':str(p) in {r['file'] for r in refs},'note':'Retained raw download/scan; unselected searches are not canonical proof.'})
write('REFERENCE_PRESERVATION_INDEX.json',{'uid':UID,'references':allrefs,'canonicalSelected':len(refs),'fullMoviesDownloaded':0,'firstPhaseSourceSeconds':[10964,10970,10975,10983,11030,11110,11170],'secondPhaseExcludedSeconds':[11210,11213,11216,11220]})
files=[{'path':str(p.relative_to(B)),'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(B.rglob('*')) if p.is_file() and p.name!='FILE_SHA256_MANIFEST.json']
write('FILE_SHA256_MANIFEST.json',{'uid':UID,'fileCount':len(files),'files':files})
print(json.dumps({'status':'producer-reviewed-ready-for-independent-integration','delivery':str(B/'FINAL_DELIVERY.json'),'uid':UID,'sheets':6,'poses':72,'additionalHornetPNG':1,'nativeGeneratedPNG':7,'noSourcePixelEdits':True,'props':props},indent=2))
