from pathlib import Path
from PIL import Image
import json,hashlib,sys
B=Path(__file__).parent;uid='core__quiet'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(name,d):
 p=B/name;p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n');return str(p)
selected={'a-right':'A_RIGHT_01','a-left':'A_LEFT_01','b-right':'B_RIGHT_01','b-left':'B_LEFT_01','c-right':'C_RIGHT_01','c-left':'C_LEFT_05'}
heights={'a-right':385.5,'a-left':410,'b-right':400,'b-left':390,'c-right':342,'c-left':363}
contract=json.loads((B/'references/source-contract.json').read_text());refs=[]
for r in contract['references']:
 p=B/'references'/r['file'];assert sha(p)==r['sha256'];refs.append({'file':str(p),'url':r['download_url'],'sha256':sha(p),'bytes':p.stat().st_size,'sourceKind':'original-game-capture' if 'primary_' in r['provenance_level'] else 'original-game-model','provenanceLevel':r['provenance_level'],'scope':r['role'],'viewed':True,'limits':'Official original Steam game capture; Steam20 player AM MRS-4 HUD does NOT identify Quiet weapon. Steam21 rear actor blurred.' if 'primary_' in r['provenance_level'] else 'Secondary mirror claimed original-model render; original publisher URL not recovered. Supplementary anatomy/outfit evidence only, not primary-certified asset.'})
limits=[
 '1:1 original 2015 MGSV TPP default adult Quiet is the target. New 2D detailed cel-shaded art and 72 authored Versus poses are closest_supported, not extracted Fox Engine sprites, original animation data or absolute1to1 certification.',
 'Original official Steam20 confirms exposed neckline/torso, dark tied front top, olive harness, brown tied ponytail and long BLACK LEFT arm protection; original Steam21 is background context only. Secondary original-model mirrors supplement fullbody torn dark hosiery, shorts, dark laceup ankle boots, LEFT olive hip pouch and RIGHT thigh holster. Publisher source for mirrored renders not recovered; original primary all-side topology not certified.',
 'All facings independently generated; no PNG reflection, runtime body mirroring, resizing, recoloring, alpha cleanup, raster editing or crop/export performed. Native hidden RGB red/yellow fringe is alpha1-7 except single faint A-right pixel; physically viewed browser Canvas green/black composition at230px is clean. Small opaque red hip equipment agrees supplied reference; no red waist band approved.',
 'Rifle is ONE conventional long slender exposed-barrel bolt sniper with large black scope, silver bolt and skeletal black stock visually supported by official Steam20; exact selected weapon alias/upgrade/internal workings not established by original inventory/frame. Wicked/Guilty RENOV-ICKX aliases have only a preserved secondary2015Steam discussion, so no alias1:1 certification. Player HUD AM MRS-4 is excluded as identification. No new railgun, psychic energy, suppressor, anti-material or tranquilizer weapon depicted.',
 'shoot, deploy and charge use the SAME visually supported conventional rifle. deploy is a crouched aimed shot adaptation, not certified Guilty Butterfly tranquilizer. charge precision/super is conventional rifle recoil, not rail/beam. Ammo, five-round capacity,50metercost, damage and exact timings are authored versus balancing to be independently checked by integrator; no unlimited/freemmo canon claim.',
 'Anatomical asymmetries remain intended original LEFT long black sleeve, RIGHT bare forearm/short olive glove and RIGHT thigh holster/LEFT hip pouch. Forward supporting sleeve and bare trigger-arm overlap partly hides finger topology and exact shoulder/stock contact. Fine materials, eye color, holes/pouch counts, hidden buckles/seams and precise hand dominance in every pose are not certified at source resolution.',
 'Normal CQC punches/palm/sweep, throws, jump/guard, reload/recovery, precision pose and recoil are authored readable fighting-game adaptations. Parasite-assisted cloak/movement belongs to gameplay helper; no psi aura, rail blast or source-extracted teleport duration. Optic action uses the rifle own scope, not invented binocular gear.',
 'Standing source heights from physically observed upright head-to-boot silhouettes are fixed per sheet; crouch and KO retain naturally short native pose geometry. Crouched rifle muzzle origins are the actual visible pixels, not artificially lowered to claim guaranteed crouching contact; trajectory/collision must be independently tested.',
 'Some close native row cells have adjacent body pixels inside wide crops. Existing generic read-only component/Canvas contour metadata excludes foreign bodies; no native pixels changed. Source-scale differences and asymmetrical light/shading remain illustration approximation and are explicitly closest_supported.',
 'C_LEFT01 rejected mixed right aims;02 rejected sixth figure faced right;03 fixed direction but93 opaque bottom-edge boot pixels indicated clipping;04 complete directions/feet but noncanonical vivid red waist belt;05 repaired belt with image_gen and is selected. All four rejected native outputs/args/SHA retained, no OC created.',
 'Producer approval is for six physically viewed PNG body sheets/72pose cells and supplied provenance. Independent runtime/mobile/phase/ammo/contact validation is pending root/integrator, not certified by generation.'
]
layout={'idle':{'sheet':'a','indices':[0,1],'fps':4,'loop':True},'walk':{'sheet':'a','indices':[2,3,4,5],'fps':9,'loop':True},'guard':{'sheet':'a','indices':[6,7],'fps':5,'loop':True},'crouch':{'sheet':'a','indices':[8,9],'fps':4,'loop':True},'jump':{'sheet':'a','indices':[10,11],'fps':6,'loop':False},'punch':{'sheet':'b','indices':[0,1,2],'fps':12,'loop':False},'heavy':{'sheet':'b','indices':[3,4,5],'fps':10,'loop':False},'low':{'sheet':'b','indices':[6,7,8],'fps':10,'loop':False},'hit':{'sheet':'b','indices':[9],'fps':0,'loop':False},'ko':{'sheet':'b','indices':[10,11],'fps':6,'loop':False},'throw':{'sheet':'c','indices':[0,1],'fps':9,'loop':False},'shoot':{'sheet':'c','indices':[2,3,4],'fps':10,'loop':False},'deploy':{'sheet':'c','indices':[5,6],'fps':8,'loop':False},'optic':{'sheet':'c','indices':[7],'fps':0,'loop':False},'recover':{'sheet':'c','indices':[8,9],'fps':5,'loop':False},'charge':{'sheet':'c','indices':[10,11],'fps':9,'loop':False}}
slots={'light':'punch','heavy':'heavy','low':'low','throw':'throw','special':'shoot','specialDown':'deploy','specialForward':'jump','specialBack':'walk','super':'charge','utility':'recover'}
phase={k:{'startup':[0],'active':[1],'recovery':[2]} for k in ['punch','heavy','low','shoot']}
phase.update({k:{'startup':[0],'active':[1],'recovery':[0]} for k in ['throw','deploy','charge']});phase['optic']={'startup':[0],'active':[0],'recovery':[0]};phase['recover']={'startup':[0],'active':[1],'recovery':[1]};phase['walk']={'startup':[0],'active':[1,2],'recovery':[3]};phase['jump']={'startup':[0],'active':[0],'recovery':[1]}
final=[]
for key,name in selected.items():
 p=B/'native-attempts'/(name+'.png');m=json.loads((B/'metadata'/(name+'.result-summary.json')).read_text());im=Image.open(p);d=json.loads((B/'layouts'/(key+'.json')).read_text());assert sha(p)==sha(m['nativeOriginal']);assert m['opaqueEdgePixels']==0 and len(d['cells'])==12
 row={'key':key,'source':str(p),'nativeOriginal':m['nativeOriginal'],'sha256':sha(p),'bytes':p.stat().st_size,'width':im.width,'height':im.height,'columns':4,'rows':3,'poseCount':12,'facing':1 if key.endswith('right') else -1,'mirror':False,'inspection':str(B/'inspections'/(name+'.components.json')),'standingSourceHeight':heights[key],'observedBodyHeights':[c['bbox'][3]-c['bbox'][1] for c in d['cells']],'layout':str(B/'layouts'/(key+'.json'))};final.append(row)
review={'uid':uid,'incarnation':'Original 2015 MGSV The Phantom Pain adult Quiet default buddy outfit','status':'approved','reviewer':'pass7_quiet_native / actual unmodified original-model references and ten generated native sheets physically viewed; 12final Canvas composition captures physically viewed','reviewedAt':'2026-10-02','sourceKind':'original-game-capture','absolute1to1Certified':False,'fidelityStatus':'closest_supported','approvalScope':'Six selected source PNGs and72authoredbodyposes, true-alpha independentfacings. Root independent gameplay verification still pending.','checks':{'identity':True,'costume':True,'equipment':True,'anatomicalSides':True,'singleFigure':True,'transparentBackground':True},'sources':refs,'limits':limits,'sourcePriority':['Official Steam original TPP screenshot20 costume/rifle','Steam screenshot21 contextual only','Secondary mirrored original-model renders supplementary costume sides']}
write('CANONICAL_REVIEW.json',review)
marks={}
for side,points in [('right',{'shoot':[1509,74],'deploy':[1145,509],'charge':[1503,754]}),('left',{'shoot':[1142,78],'deploy':[761,525],'charge':[1142,764]})]:
 row=next(r for r in final if r['key']=='c-'+side);im=Image.open(row['source']);marks[side]={}
 for action,point in points.items():
  rgba=list(im.getpixel(tuple(point)));assert rgba[3]>80
  marks[side][action]={'action':action,'frame':1,'sourcePoseIndex':{'shoot':3,'deploy':6,'charge':11}[action],'file':'assets/combat-sprites/'+uid+'/c-'+side+'-v1.png','source':row['source'],'sha256':row['sha256'],'point':point,'pointRGBA':rgba,'note':'Actual visible conventional rifle muzzle native pixel for first active authored Versus action phase. Same original-visual rifle category; no exact original inventory alias certification, tranquilizer weapon, psi/rail source or free-ammo claim. Crouched deploy point must not be shifted below visible muzzle to force crouch contact.'}
write('SOURCE_COMBAT_ORIGINS.json',{'uid':uid,'schema':'cqc.pass7.native-source-combat-marks/1','coordinateSystem':'Native full-sheet PNG x,y no resize/flip; frame indices local action group, sourcePoseIndex fullsheet zero-based.','slotSourceGroups':{'special':'shoot','specialDown':'deploy','super':'charge'},'marks':marks,'sourceIncarnation':'Adult 2015 MGSV TPP default Quiet; same conventional scoped slimbarrel silverbolt blackstock rifle in all rangedactions'})
rejects={'C_LEFT_01':'Mixed screen-right rifle aiming among requested screen-left poses','C_LEFT_02':'Sixth kneeling pose faced right','C_LEFT_03':'Bottom boot atindex8clipped:93opaque bottom-edge pixels','C_LEFT_04':'Noncanonical vivid red waist belt'}
attempts=[]
for p in sorted((B/'native-attempts').glob('*.png')):
 name=p.stem;m=json.loads((B/'metadata'/(name+'.result-summary.json')).read_text());attempts.append({'name':name,'source':str(p),'nativeOriginal':m['nativeOriginal'],'sha256':sha(p),'bytes':p.stat().st_size,'status':'approved-final' if name in selected.values() else 'rejected-native-retained','reason':rejects.get(name),'args':str(B/'prompts'/(name+'.args.json'))})
write('NATIVE_PNG_INDEX.json',{'uid':uid,'nativeImages':len(attempts),'approvedBodySheets':6,'poses':72,'rejects':4,'attempts':attempts})
write('NATIVE_ALPHA_REVIEW.json',{'uid':uid,'noImageWrites':True,'nativeSelected':[{k:v for k,v in json.loads((B/'metadata'/(name+'.result-summary.json')).read_text()).items()} for name in selected.values()],'hiddenRgbCaveat':'view_image preview exposes hidden RGB; alpha compositing at230px physically reviewed on black and mutedgreen. No colored matte/aura appears in normal Canvas.','readOnlyFringeAudit':str(B/'FRINGE_ALPHA_AUDIT.json'),'canvasProofCommands':str(B/'inspections/canvas-compositing-final-commands.json'),'canvasCapturesPhysicallyViewed':[str(B/'inspections'/(key+'-canvas-final-'+color+'.png')) for key in selected for color in ['green','black']]})
write('SOURCE_AND_ACTION_CONTRACT.json',{'uid':uid,'sourceContract':str(B/'references/source-contract.json'),'actionLayout':layout,'actionMap':slots,'phaseMap':phase,'sourceReferences':refs,'weaponModelCertification':'pending_original_inventory_no_alias_1to1_claim','gameplayOwner':'Root/helper integration; producer did not edit runtime or catalog','supportedVisualActions':'Same ordinary scoped sniper shoot/deploy/charge; physical CQC norms, movement/bounds and rifle reload authored adaptations','excluded':'No psychic/railgun, no unproven Guilty tranquilizer loadout, no AM MRS-4 derived from playerHUD, no loosehair/closedcollar, no SniperWolf/XOF costumes'})
delivery={'schema':'cqc.native-combat-delivery/1','uid':uid,'name':'QUIET','game':'Metal Gear Solid V: The Phantom Pain (2015)','incarnation':'Original 2015 MGSV TPP adult Quiet default buddy outfit, conventional original-visual sniper','selectedCostume':'Adult original default tied black combat top/shorts/tornhosiery/oliveharness, brownponytail, anatomical LEFT long black sleeve and LEFT olive hip pouch; RIGHT thigh holster and bare forearm/short glove','basis':'Original conventional scoped sniper firearm; parasite-derived cloak/enhancedmovement remain source-supported lore scope and authored versus gameplay, never psychic/railgun. Exact selected alias pending original inventory proof.','displayHeight':230,'coverage':'action-frames','facing':1,'mirror':False,'sourceFiles':final,'actionLayout':layout,'actionMap':slots,'phaseMap':phase,'review':review,'nativeSourceCombatOrigins':str(B/'SOURCE_COMBAT_ORIGINS.json'),'sourceCombatOrigins':str(B/'SOURCE_COMBAT_ORIGINS.json'),'sourceContract':str(B/'references/source-contract.json'),'nativeAlphaReview':str(B/'NATIVE_ALPHA_REVIEW.json'),'counts':{'selectedNativePngSheets':6,'totalPoseCells':72,'facings':2,'nativeBodyGenerationAttempts':10,'rejectedNativeBodyAttempts':4},'limits':limits}
write('FINAL_DELIVERY.json',delivery)
files=[{'path':str(p.relative_to(B)),'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(B.rglob('*')) if p.is_file() and p.name!='FILE_SHA256_MANIFEST.json']
write('FILE_SHA256_MANIFEST.json',{'uid':uid,'fileCount':len(files),'files':files})
print(json.dumps({'status':'producer-reviewed-ready-for-independent-integration','delivery':str(B/'FINAL_DELIVERY.json'),'sha256':sha(B/'FINAL_DELIVERY.json'),'nativePNG':10,'selectedPNG':6,'poses':72,'rejectedRetained':4,'runtimeEdits':False,'byteUnchangedCopies':True},indent=2))
