from pathlib import Path
from PIL import Image
import json,hashlib,os,sys,datetime
B=Path(__file__).resolve().parent
sys.path.insert(0,'/workspace/cqc-game-working/cqc-versus-v056/tools')
from inspect_combat_sprite_sheet import inspect_components
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,d):
 raw=(json.dumps(d,ensure_ascii=False,indent=2)+'\n').encode()
 if p.exists() and p.read_bytes()!=raw:
  backup=p.with_name(p.stem+'.previous-'+hashlib.sha256(p.read_bytes()).hexdigest()[:12]+p.suffix)
  if not backup.exists():backup.write_bytes(p.read_bytes())
 p.write_bytes(raw)
layout={'idle':{'sheet':'a','indices':[0,1],'fps':4,'loop':True},'walk':{'sheet':'a','indices':[2,3,4,5],'fps':8,'loop':True},'guard':{'sheet':'a','indices':[6,7],'fps':4,'loop':True},'crouch':{'sheet':'a','indices':[8,9],'fps':4,'loop':True},'jump':{'sheet':'a','indices':[10,11],'fps':5,'loop':False},'punch':{'sheet':'b','indices':[0,1,2],'fps':10,'loop':False},'heavy':{'sheet':'b','indices':[3,4,5],'fps':9,'loop':False},'low':{'sheet':'b','indices':[6,7,8],'fps':9,'loop':False},'hit':{'sheet':'b','indices':[9],'fps':0,'loop':False},'ko':{'sheet':'b','indices':[10,11],'fps':4,'loop':False},'throw':{'sheet':'c','indices':[0,1],'fps':8,'loop':False},'shoot':{'sheet':'c','indices':[2,3,4],'fps':7,'loop':False},'deploy':{'sheet':'c','indices':[5,6],'fps':6,'loop':False},'optic':{'sheet':'c','indices':[7],'fps':0,'loop':False},'recover':{'sheet':'c','indices':[8,9],'fps':5,'loop':False},'charge':{'sheet':'c','indices':[10,11],'fps':5,'loop':False}}
slots={'light':'punch','heavy':'heavy','low':'low','throw':'throw','special':'throw','specialDown':'deploy','specialForward':'shoot','specialBack':'guard','super':'charge','utility':'recover'}
phase={k:{'startup':[0],'active':[1],'recovery':[2]} for k in ['punch','heavy','low','shoot']};phase.update({k:{'startup':[0],'active':[1],'recovery':[0]} for k in ['throw','deploy','charge']});phase['optic']={'startup':[0],'active':[0],'recovery':[0]};phase['recover']={'startup':[0],'active':[1],'recovery':[1]};phase['guard']={'startup':[0],'active':[1],'recovery':[0]}
for g in ['mgr']:
 D=B/g;contract=json.loads((D/'SOURCE_AND_ACTION_CONTRACT.json').read_text());uid=contract['uid'];selected={f'{s.lower()}-{side.lower()}':f'{s}_{side}_{"03" if side=="RIGHT" else "02"}' for s in ['A','B','C'] for side in ['RIGHT','LEFT']};refs=[]
 id='PS3_Longplay_081_Metal_Gear_Solid_4' if g=='mgs4' else 'PS3_Longplay_079_Metal_Gear_Rising_Revengeance';video=f'https://archive.org/download/{id}/{id}.mkv'
 refnotes=({8150:'Sunny original kitchen costume, silver child bob, black long sleeved high-neck top, white crossed cooking apron straps; black pan in kitchen. No adult redesign or tactical equipment.',17460:'Sunny holds the original white cylindrical kitchen container with dark bands; original cooking scene and egg dialogue with Naomi. Fine label/physical internals not certified.',17560:'Sunny standing beside adult Naomi establishes short child proportions, white apron crossed straps and waist tie, black long sleeves, full length blue-gray trousers. Feet below source camera not shown.',17580:'Original young round face, silver blond side fringe and blue rose newly given by Naomi on anatomical LEFT temple.'} if g=='mgs4' else {15300:'Original eleven-year-old Sunny at Solis: silver child bob, violet flower left clip, horizontal gray white striped covered tank with ochre piping, green neck headset, ochre work gloves, olive cargos and pale jacket tied at waist; actual greeting handshake with Raiden.',15340:'Original fullbody distant comparison to adult Raiden confirms child height, olive full cargo trousers and dark high work boot silhouette. Fine boot stitching/strap count not resolved.',15360:'Original front youthful face and left rose, green hearing protection with boom and curled cable around neck, ochre top piping, black badge lanyard and rectangular ID. Sunny explains the hybrid engine she designed.',15370:'Original anatomical LEFT profile with violet blue rose on left temple, silver bob, green headset cup, black padded headset band and curled cable. No electronic gun or combat power.'})
 for r in contract['references']:
  p=Path(r['file']);t=int(p.stem.split('-')[-1][:-1]);refs.append({**r,'url':video+'#t='+str(t),'timeSeconds':t,'scope':refnotes[t],'captureMethod':'ffmpeg remote seek single1280x720 native PS3 original-longplay frame; no full movie download, no resize/recolor or image editing; hardware framebuffer authenticity is not independently certified.'})
 limits=['Target1:1 original incarnation fidelity, result closest_supported authored 2D sprite illustration. Original refs physically observed; no absolute1to1 claim, model extraction or motion-capture identity.',f'Sunny remains a fully clothed child, approximately{contract["age"]}years in this incarnation. Child proportions and smaller display height are essential; no adultization, sexualized posing, adult make-up or nudity.', 'Sunny is a noncombatant cooking/technical support character in these original sources. All idle/walk/protection/duck/hop/rest and support animation timings are authored Versus presentation, not canonical Sunny fighting skills. B has open-hand halt, protective leaning, evasion/startle and seated rest; no punch, physical injury, killing or gun drawing.', 'Legacy renderer action keys punch/heavy/low/throw/shoot/deploy/charge are technical aliases for harmless source-supported support poses. shoot has NO gun/muzzle; throw has NO enemy throwing; charge has NO attack, energy beam or martial art. Runtime must keep any actual Versus benefits balanced and explicitly simulated, with no invented canonical weapon, projectile, CQC finish or damaging summon.', 'Both facings were independently generated, mirror=false. RIGHT near anatomicalRIGHT temple stays bare; source LEFT blue/violet rose is far-side occluded. LEFT near anatomicalLEFT temple shows rose. Both initial RIGHT01 sheets put a rose near right temple and were rejected, retained exact, never imported or repurposed as OC.', 'All twelve body PNGs are native RGBA1536x1024 and unchanged. Low-alpha RGB gray/brown background may show in file viewers but actual alpha is transparent; no pixel cleanup, crop export, resize, recolor, alpha edit or horizontal flip was performed. Runtime Canvas crops/contours and independent browser physical review remain integrator-owned.', 'Face, garment folds, straps, fine seams, tiny badge/ear-protector branding, finger overlaps and opposite-facing illustration differences are closest-supported interpretation. Display heights145/170are relative gameplay recommendations, not certified centimetres or canonical measured model scale.', 'Selected reference PNG budget below15MB perform; unsuitable search frames and an unrelated Pinterest search image remain preserved as rejected research, not canonical visual evidence. No source film downloaded in full.']
 if g=='mgs4':limits+=['Selected MGS4 incarnation is the black-sweater/blue-gray-trousers/white cooking-apron outfit aboard Nomad after Naomi gives the blue rose. Epilogue formal dress is a separate costume and is not mixed into these body sprites.', 'Original selected sources do not show close-up foot/shoe construction. Ordinary closed dark flat shoes are a conservative authored readability choice; exact canonical MGS4 shoe1:1 is unresolved. No combat boots, high heels, tactical harness or invented color blocks.', 'Black frying pan and egg cooking are original kitchen context; hand-held pan angle/two-egg presentation on LEFT active pan is authored support animation, not an offensive projectile. RIGHT pan interior appears dark due orientation; no visible egg count certified. White cylindrical kitchen container has source-supported broad shape, but labels/material/color precision and contents are not certified.', 'C7RIGHT is a self listening/thinking hand-near-head gesture; the far-side blue rose is invisible and exact left rose touch is not claimed. C7LEFT touches the visible left-side rose.']
 else:limits+=['Six initial short-back-hair MGR sheets were superseded and retained exact. Six native imagegen edits add lower silver hair locks beneath the rear headset band toward the upper shoulders as original PS3 profile15370. No Python pixel editing occurred; each revision has an independent saved original PNG and prompt.', 'MGR neck green hearing protection, black badge lanyard, striped top, ochre gloves, olive cargo pants, light jacket knotted at waist and dark boots are original support-engineer costume. Selected original fullbody view is distant: exact boot hardware, jacket tie topology and headset tiny manufacturer marks remain interpreted.', 'Actual original handshake confirms greeting, but generated C6 pose is an open gloved friendly greeting rather than exact handshake animation. C7 checks near headset/mic; actual gesture/detailed interface motion is authored. No laptop, invented wrench, tool projectile, cyborg body, lab coat worn on shoulders or battle robot summon.']
 review={'uid':uid,'status':'approved','reviewer':'sunny_two_versions / producer physical source and twelve native atlas review','reviewedAt':'2026-10-02','sourceKind':'original-game-capture','fidelityStatus':'closest_supported','absolute1to1Certified':False,'checks':{k:True for k in ['identity','costume','equipment','anatomicalSides','singleFigure','transparentBackground']},'sources':refs,'limits':limits,'approvalScope':'Six unchanged source-native body atlases and72 safe authored pose semantics perUID only; separate integration/Canvas/contact/browser review remains required.'}
 final=[];checks=[]
 for key,name in selected.items():
  p=D/'native-attempts'/f'{name}.png';q=D/'sources'/f'{name}.png'
  if not q.exists():os.link(p,q)
  assert sha(p)==sha(q)
  im=Image.open(q);a=im.getchannel('A');assert im.mode=='RGBA' and a.getextrema()[0]==0
  doc=inspect_components(q,4,3,'assets/combat-sprites/'+uid+'/'+key+'-v1.png')
  for c in doc['cells']:c['artistic_review']='producer-physically-observed-complete-fully-clothed-child-appropriate-canonical-costume-safe-pose-correct-facing';c['poseMeaning']=contract['poseSemantics'][key[0].upper()][c['index']]
  write(D/'layouts'/f'{key}.json',doc)
  indices=[0,1] if key[0]=='a' else [0,1,2] if key[0]=='b' else [0,1]
  hs=[doc['cells'][i]['bbox'][3]-doc['cells'][i]['bbox'][1] for i in indices];m=json.loads((D/'metadata'/f'{name}.result-summary.json').read_text())
  final.append({'key':key,'source':str(q),'nativeOriginal':m['nativeOriginal'],'sha256':sha(q),'bytes':q.stat().st_size,'width':im.width,'height':im.height,'columns':4,'rows':3,'poseCount':12,'facing':1 if key.endswith('right') else -1,'mirror':False,'layout':str(D/'layouts'/f'{key}.json'),'standingReferencePoseIndices':indices,'standingSourceHeight':round(sum(hs)/len(hs),2),'observedBodyHeights':[c['bbox'][3]-c['bbox'][1] for c in doc['cells']],'canvasContourFrames':doc['foreign_body_frames']})
  assert sha(m['nativeOriginal'])==sha(q)
  checks.append({'key':key,'sha256':sha(q),'producerPhysicalViewed':True,'completeBodyAndSupportPropViewed':True,'childAgeProportionsObserved':True,'noWeaponOrViolentPose':True,'nearRightTempleBare':True if key.endswith('right') else None,'leftRoseVisible':True if key.endswith('left') else None,'standingSourceHeight':round(sum(hs)/len(hs),2),'rgbaAlphaExtrema':list(a.getextrema()),'opaqueComponents':len(doc['cells']),'sourcePixelsEdited':False})
 attempts=[]
 for p in sorted((D/'native-attempts').glob('*.png')):
  m=json.loads((D/'metadata'/f'{p.stem}.result-summary.json').read_text());attempts.append({'key':p.stem,'source':str(p),'nativeOriginal':m['nativeOriginal'],'sha256':sha(p),'bytes':p.stat().st_size,'status':'rejected-anatomical-rose-side' if p.stem=='A_RIGHT_01' else 'approved-final' if p.stem in selected.values() else 'superseded-short-lower-nape-layer-retained','retainedUnchanged':True})
 origins={'schema':'cqc.pass8.native-source-combat-marks/1','uid':uid,'marks':{'right':{},'left':{}},'slotSourceGroups':{},'nonBallistic':True,'canonicalWeapon':None,'scope':'Sunny is original noncombatant support. There are no muzzle or projectile launch points. Separate optional hand-support points are presentation anchors only and cannot certify canonical attacking skills.'}
 write(D/'SOURCE_COMBAT_ORIGINS.json',origins);write(D/'CANONICAL_REVIEW.json',review);write(D/'NATIVE_PNG_INDEX.json',{'uid':uid,'attempts':attempts,'nativeImages':len(attempts),'approvedBodySheets':6,'approvedPoses':72,'rejectedNativeImages':1,'supersededHairRevisionSheets':6,'pixelEdits':0,'generatedOtherOCs':0});write(D/'PRODUCER_PHYSICAL_REVIEW.json',{'schema':'cqc.pass8.sunny-producer-physical-review/1','uid':uid,'status':'approved_closest_supported','reviewer':'sunny_two_versions','sources':checks,'observedCompletePoses':72,'sourceReferenceBytes':contract['selectedReferenceBytes'],'canonicalReviewSha256':sha(D/'CANONICAL_REVIEW.json'),'limits':limits})
 delivery={'schema':'cqc.native-combat-delivery/1','uid':uid,'name':'SUNNY (MGS4)' if g=='mgs4' else 'SUNNY (MGR)','game':'Metal Gear Solid 4: Guns of the Patriots (2008), original PlayStation3' if g=='mgs4' else 'Metal Gear Rising: Revengeance (2013), original PlayStation3','incarnation':f'Original PS3 {g.upper()} Sunny, child age{contract["age"]}; '+('Nomad kitchen black sweater, jeans and white cooking apron after Naomi blue rose' if g=='mgs4' else 'Solis child engineer, striped tank/cargos/workgloves/green neck headset/left violet rose'),'selectedCostume':'original-ps3-sunny-nomad-kitchen-apron-blue-rose' if g=='mgs4' else 'original-ps3-sunny-solis-cargo-headset-left-violet-rose','basis':'Original noncombatant child technical and kitchen support. All Versus poses are harmless authored presentation/avoidance, not combat-canon claims.','displayHeight':contract['displayHeight'],'coverage':'action-frames','facing':1,'mirror':False,'sourceFiles':final,'actionLayout':layout,'actionMap':slots,'phaseMap':phase,'review':review,'nativeSourceCombatOrigins':str(D/'SOURCE_COMBAT_ORIGINS.json'),'limits':limits,'nonCombatantSupport':True}
 write(D/'FINAL_DELIVERY.json',delivery)
 print(json.dumps({'uid':uid,'delivery':str(D/'FINAL_DELIVERY.json'),'sha256':sha(D/'FINAL_DELIVERY.json'),'sheets':6,'poses':72,'allSourcePixelsUnchanged':True,'selectedReferenceBytes':contract['selectedReferenceBytes'],'scales':{r['key']:r['standingSourceHeight'] for r in final}},indent=2))
