from pathlib import Path
import json,hashlib
B=Path(__file__).resolve().parent
A=['quiet upright idle, hands relaxed at sides','second upright idle, one small weight shift','walking leading foot forward','walking passing step','walking opposite foot forward','walking returning passing step','protective open palms held near chest','protective crossed forearms lowered slightly','compact crouch with both feet complete','low crouch looking ahead','small hop lifting heels and bending knees','soft landing with knees bent']
Bs=['open hand raised to ask someone to stop','open palm extended forward in a friendly halt','open palm returning to chest','both hands draw back protectively','leaning torso away with hands up defensively','recovering normal safe stance','knees flex in a sideways evasive step','low duck with arms close','standing from low duck','small startled step without injury','seated on ground resting, both legs folded safely','seated leaning on one palm, calm tired rest']
C4=['hands raised ready for a console','both hands forward typing gesture on an unseen fixed console, no floating object','holding the small original-style black cooking pan by handle near waist','gently tilting the same black pan to inspect cooked eggs, horizontal bottom','returning the same black pan to waist','holding the original white cylindrical kitchen bottle safely upright','lowering same white bottle with relaxed hand','checking the blue flower barrette with the left hand','hands clasped patiently listening','one friendly small wave','standing thoughtfully with hand near chin','standing smiling with both palms slightly open']
CR=['hands raised ready for engineering explanation','both hands forward typing gesture at an unseen fixed control console, no laptop','pointing with one gloved hand to explain machinery','open gloved hand showing a small adjustment gesture','relaxed lowered hands after explaining','right gloved hand politely offering a handshake','right gloved hand slightly extended as a friendly greeting','left gloved hand checking green headset at neck','hands clasped patiently listening','one friendly small wave','standing thoughtfully with gloved hand near chin','standing smiling with both gloved palms slightly open']
forms={
'mgs4':{'uid':'roster50__sunny_mgs4','name':'Sunny (MGS4)','age':7,'displayHeight':145,'outfit':'Original PS3 MGS4 Sunny in the Nomad kitchen after Naomi gives her a small blue rose: short pale silver blond bob with long side fringe, soft round seven-year-old face, blue rose hair clip on anatomical LEFT temple. Black long sleeved high-neck sweater, blue-gray full length jeans, ordinary dark closed flat shoes, white plain full cooking apron with white shoulder straps crossing at back and a waist tie. NO grown-up body, NO adult makeup, no high heels. Every pose remains fully clothed with actual child proportions: approximately 4.8 heads tall, short arms and short legs, age seven. The apron is a household cooking apron, not a nurse costume or dress. No green ear protectors or gloves: those belong to the older MGR version. Shoes are conservative closed dark flats because original chosen camera obscures fine shoe detail; do not invent combat boots or decorations.','refs':[8150,17460,17560,17580],'C':C4},
'mgr':{'uid':'roster50__sunny_mgr','name':'Sunny (MGR)','age':11,'displayHeight':170,'outfit':'Original PS3 Metal Gear Rising Revengeance eleven-year-old Sunny at Solis hangar: pale silver bob with asymmetrical long fringe, a small violet blue rose hair clip at anatomical LEFT temple, round youthful preteen face. Fully covering white and gray horizontally striped tank top with mustard yellow piping at neckline and arm holes; no neckline redesign. Loose olive khaki cargo trousers with side flap pockets. Off-white light work jacket tied around waist with sleeves knotted in front. Ochre leather working gloves on both hands, dark ordinary calf-height work boots as original fullbody image. Large original green ear-protection/headset with dark padded black headband around neck, green cups on either side of chest, small boom mic and curled black cable. Black lanyard with simple white rectangular work badge. Fully clothed genuine eleven-year-old child proportions approximately 5.5 heads tall, short youthful limbs. NO adultization, adult makeup, high heels, sexualized posing or cyber body. NO lab coat worn on shoulders; the light work jacket is tied around waist.','refs':[15300,15340,15360,15370],'C':CR}}
for g,f in forms.items():
 d=B/g
 for n in ['prompts','metadata','native-attempts','sources','layouts']:(d/n).mkdir(parents=True,exist_ok=True)
 refs=[str(d/'references'/f'original-ps3-frame-{t:05d}s.png') for t in f['refs']]
 contract={'schema':'cqc.pass8.sunny-source-and-action-contract/1','uid':f['uid'],'incarnation':g,'age':f['age'],'displayHeight':f['displayHeight'],'costume':f['outfit'],'sourceSupportedRole':'Original non-combatant child genius; cooking and technical support. All A/B motion phases are authored versus presentation and avoidance, not extracted combat abilities. No Sunny gun, shooting, offensive hacking beam, armored robot summon, CQC killing or explosive damage.','fidelityStatus':'closest_supported','absolute1to1Certified':False,'mirror':False,'references':[{'file':p,'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest(),'bytes':Path(p).stat().st_size,'sourceKind':'original-game-capture','viewed':True} for p in refs],'selectedReferenceBytes':sum(Path(p).stat().st_size for p in refs),'referenceBudgetBytes':15000000,'poseSemantics':{'A':A,'B':Bs,'C':f['C']}}
 (d/'SOURCE_AND_ACTION_CONTRACT.json').write_text(json.dumps(contract,ensure_ascii=False,indent=2)+'\n')
 for sheet,poses in [('A',A),('B',Bs),('C',f['C'])]:
  for side in ['RIGHT','LEFT']:
   facing='SCREEN '+side
   pose='; '.join(str(i+1)+'. '+x for i,x in enumerate(poses))
   prompt=f'''Create ONE brand-new high fidelity 2D GAME SPRITE ATLAS of Sunny from {"Metal Gear Solid 4 PS3" if g=="mgs4" else "Metal Gear Rising Revengeance PS3"}, faithfully matching the supplied actual original-game reference frames. This is a normal fully clothed child character in harmless nonsexual game support poses. This is NOT a weapon or fighting sheet. Use detailed clean illustrated sprite art with crisp silhouette and restrained original-game material colors, not chibi or adult anime. The actual child age and clothing are crucial. {f['outfit']}
Wide landscape 3:2 native transparent RGBA PNG, around1536x1024. EXACTLY twelve separate COMPLETE single-person fullbody poses in a clean regular grid FOUR COLUMNS and THREE ROWS. All twelve have the SAME scale and same costume and proportions. Leave large transparent gutters at least25pixels around each complete figure; absolutely no overlap, neighbor fragments, edge clipping, cut off feet, hair, hands or apron. Each pose occupies just its own cell. No labels, numerals, text, background, ground, shadows, weapons, effects, extra people or collage pieces.
All twelve Sunny bodies face {facing}, nose and toes oriented mainly {side.lower()}, side-on or gentle three-quarter same direction. This is independently drawn {side} art, do not mirror another sheet. Keep the blue/violet rose on her anatomical LEFT temple even when on the far side/occluded; do not move it onto the near right temple. Anatomical details consistent with original character, no gray beard or soldier body. Frame order row major left to right: {pose}. Every seated/crouched pose has complete whole clothing, legs, closed shoes and natural child posture. A genuinely separate full child per cell; no duplicate idle filling the grid. Each is a safe friendly engineer/cook or natural evasion/rest animation. No injury, nudity or sexualization. Reference screenshots are only to extract Sunny costume/face; do not draw Naomi, Snake, Raiden, aircraft, cabinets or the original scene. Sheet{sheet} direction{side}.'''
   args={'prompt':prompt,'transparent_background':True,'referenced_image_paths':refs}
   (d/'prompts'/f'{sheet}_{side}_01.args.json').write_text(json.dumps(args,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({g:{'uid':f['uid'],'selectedReferenceBytes':json.loads((B/g/'SOURCE_AND_ACTION_CONTRACT.json').read_text())['selectedReferenceBytes']} for g,f in forms.items()},indent=2))
