import profilesJson from '../data/mgs3ContactProfiles.json'; import incomingJson from '../data/mgs3IncomingSchedule.json'; import itemsJson from '../data/mgs3Items.json'; import portraitsJson from '../data/mgs3PortraitSets.json'; import timelineJson from '../data/mgs3Timeline.json'; import zonesJson from '../data/mgs3Zones.json';
import type { CallHistoryEntry, ConversationDefinition } from '../types/codec.types'; import type { Mgs3ContactProfile, Mgs3IncomingScheduleEntry, Mgs3ItemEntry, Mgs3PortraitSet, Mgs3TimelineEntry, Mgs3ZoneEntry } from '../types/mgs3Profile.types';
const profiles=profilesJson as Mgs3ContactProfile[]; const incoming=incomingJson as Mgs3IncomingScheduleEntry[]; const items=itemsJson as Mgs3ItemEntry[]; const portraits=portraitsJson as Mgs3PortraitSet[]; const timeline=timelineJson as Mgs3TimelineEntry[]; const zones=zonesJson as Mgs3ZoneEntry[];
export const getMgs3Profiles=()=>profiles; export const getMgs3Profile=(id?:string)=>profiles.find(e=>e.id===id); export const getMgs3ItemsForContact=(id:string)=>items.filter(e=>e.expertContactIds.includes(id)); export const getMgs3PortraitSets=()=>portraits; export const getMgs3ZoneForContext=(id:string)=>zones.find(e=>e.contextId===id); export const getMgs3Timeline=()=>timeline;
export function resolveMgs3IdentityLabel(profile:Mgs3ContactProfile,flags:string[]){return [...(profile.identityVariants??[])].reverse().find(e=>e.requiredFlags.every(f=>flags.includes(f)))?.label??profile.codename;}
export function getMgs3ScheduledIncomingForContext(id:string,done:string[]){const set=new Set(done);return incoming.filter(e=>e.contextId===id&&(!e.once||!set.has(e.id))).sort((a,b)=>a.delayMs-b.delayMs);}
export function getMgs3TimelineState(id:string,flags:string[]){const active=timeline.findIndex(e=>e.contextId===id);return timeline.map((e,i)=>({...e,active:e.contextId===id,complete:e.requiredFlags.every(f=>flags.includes(f))||(active>=0&&i<active)}));}
export function getMgs3DiscoverySummary(profile:Mgs3ContactProfile,conversations:ConversationDefinition[],history:CallHistoryEntry[]){const relevant=conversations.filter(e=>e.contactId===profile.id);const heard=new Set(history.filter(e=>e.contactId===profile.id&&e.disposition==='completed').map(e=>e.conversationId));return{totalConversations:relevant.length,heardConversations:relevant.filter(e=>heard.has(e.id)).length,completionPercent:relevant.length?Math.round(relevant.filter(e=>heard.has(e.id)).length/relevant.length*100):0};}
export function getMgs3Coverage(conversations:ConversationDefinition[]){return{contacts:profiles.length,conversations:conversations.filter(e=>e.era==='mgs3').length,contexts:new Set(profiles.flatMap(e=>e.chapterAvailability)).size,incomingCalls:incoming.length,zones:zones.length,items:items.length,timelineEvents:timeline.length};}
