from pathlib import Path
import os
p=Path('/tmp/cqc-pass19-application/public/cqc/src/cqc-sprite-renderer.js');s=p.read_text();Path('/workspace/cqc-pass20-preview/cqc-sprite-renderer.prior-tripod-extension.js').write_text(s)
s=s.replace("['retro','nextgen','cyborg','survive','metalgear','tuxedo'].includes(concept.family)","['retro','nextgen','cyborg','survive','metalgear','tuxedo','alternate'].includes(concept.family)")
s=s.replace("        if (frame.clipPolygon && (", "        const body = frame.previewStatureBounds;\n        if (body && (!['left','top','right','bottom'].every(key => finite(body[key])) || body.left < 0 || body.top < 0 || body.right > frame.rect[2] || body.bottom > frame.rect[3] || body.right <= body.left || body.bottom <= body.top)) return false;\n        if (frame.clipPolygon && (")
s=s.replace("    const stored = previewMeasurements.get(entry)?.get(face);", "    const reviewed = frame.previewStatureBounds;\n    if (reviewed) return { frame, height: reviewed.bottom - reviewed.top, bottom: reviewed.bottom, top: reviewed.top, measurement: 'reviewed-native-stature-bounds' };\n    const stored = previewMeasurements.get(entry)?.get(face);")
s=s.replace("  function previewGeometry(fighter, box, face = -1) {\n    const entry = entryFor(fighter?.uid, fighter || {});", "  function previewGeometry(fighter, box, face = -1) {\n    const directEntry = entryFor(fighter?.uid, fighter || {});\n    // Only this reviewed machine has a native cloth counterpart of the same stature.\n    const machineDatum = !directEntry && fighter?.uid === 'pass19__dwarf_gekko_humanoid_mgr'\n      && (!fighter.costume || fighter.costume === 'original');\n    const entry = directEntry || (machineDatum ? costumeEntries.get(fighter.uid)?.get('trenchcoat') : null);")
s=s.replace("      envelope = Object.freeze({ radius, above, below });", "      if (entry.uid === 'pass19__dwarf_gekko_humanoid_mgr') for (const side of [1, -1]) {\n        const id = root.CQC_PASS18_MACHINES?.physical?.(entry.uid, side);\n        const bounds = id && root.CQC_PASS19_WORLD_SCALE?.neutralBounds?.(id);\n        if (bounds?.height > 0) radius = Math.max(radius, bounds.width / bounds.height * .56);\n      }\n      envelope = Object.freeze({ radius, above, below });")
s=s.replace("      envelope, previewOnly: true };", "      envelope, previewOnly: true, ...(machineDatum ? { renderer: 'machine-stature-datum', referenceCostume: 'trenchcoat' } : {}) };")
q=p.with_name(p.name+'.tripod.tmp');q.write_text(s);os.replace(q,p)
