from pathlib import Path
import json,hashlib,statistics,re
from PIL import Image
import numpy as np
from scipy import ndimage
r=Path(__file__).resolve().parent
refs=json.loads((r/'CANONICAL_REFERENCE_REVIEW.draft.json').read_text())
for name,scope,time in [('ps2-mgs3-20-1388s.png','Original PS2 intro rear three-quarter harness, back webbing and hip fittings. Source forest lighting green/brown is not baked into body materials.',1388),('ps2-mgs3-20-1403s.png','Original PS2 top/rear view shows dark back shoulder webbing and full long sleeves; frontal chest block is not visible at this timestamp.',1403),('ps2-mgs3-20-1352s.png','Original physical metal crossbow BOLT in Snake hand: thin dark steel shaft and short gray cross-type stabilizer fins. Embedded front tip occluded. Snake body is weapon-only context, not Fear costume reference.',1352)]:
 p=r/'references'/name
 with Image.open(p) as im:dim=list(im.size)
 refs['references'].append({'file':str(p),'url':'https://archive.org/download/LP_Metal_Gear_Solid_3/mgs3_20.mp4','sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size,'dimensions':dim,'viewed':True,'scope':scope,'sourceKind':'original-game-capture','timeSeconds':time,'captureMethod':'ffmpeg remote timestamp seek, native first decoded PNG; no resize, recolor or full video download'})
refs['interpretation']='Original Konami and actual PS2 intro override the initial scout bare-chest suggestion. Fear wears complete long-sleeve brown/olive fatigues; no shirtless costume selected. Small Little Joe and longer William Tell remain distinct authored versus attack tools, source-hidden details closest_supported.'
(r/'CANONICAL_REFERENCE_REVIEW.json').write_text(json.dumps(refs,ensure_ascii=False,indent=2)+'\n')
files=[];geometries={};alpha=[];attempts=[]
for k in ['a-right','a-left','b-right','b-left','c-right','c-left']:
 i=k.upper().replace('-','_')+'_01';meta=json.loads((r/'metadata'/f'{i}.result-summary.json').read_text());p=Path(meta['preservedSource']);d=json.loads((r/'layouts'/f'{k}.json').read_text())
 assert meta['opaqueEdgesAt48']==0 and meta['bodyComponentsOver1000']==12 and meta['transparentPixels']>0
 assert p.read_bytes()==Path(meta['nativeOriginal']).read_bytes()
 inds=[0,1] if k.startswith('a') else [0,2]
 hs=[d['cells'][n]['bbox'][3]-d['cells'][n]['bbox'][1] for n in inds];height=statistics.median(hs)
 files.append({'key':k,'source':str(p),'nativeOriginal':meta['nativeOriginal'],'sha256':meta['sha256'],'bytes':meta['bytes'],'width':meta['width'],'height':meta['height'],'columns':4,'rows':3,'poseCount':12,'facing':1 if k.endswith('right') else -1,'mirror':False})
 geometries[k]={'recommendStandingSourceHeight':height,'nativeUprightHeights':hs,'observedUprightIndices':inds,'measuredLayouts':str(r/'layouts'/f'{k}.json'),'basis':'Fixed actual native upright body bounds, median over visually upright poses. Equipment width must not inflate body height. Integrator independently validates source crop/pivot/scale and contours; no posture-by-posture stretching.'}
 alpha.append({**meta,'foreignBodyFramesInPaddedRect':d['foreign_body_frames'],'contourRequirement':'Actual single alpha components remain separate. Where padding rectangle touches a neighboring row component, importer uses actual Canvas contour/clipPolygon; source bytes remain untouched. Independent contact review required.','physicallyViewed':True,'identity':'Original Fear full long-sleeve camouflage uniform and original pale angular face/white temples; no Delta, no bare chest.','selected':True,'fidelityStatus':'closest_supported'})
 attempts.append({'id':i,'nativeOriginal':meta['nativeOriginal'],'preservedSource':str(p),'sha256':meta['sha256'],'argsPath':str(r/'prompts'/f'{i}.args.json'),'status':'accepted_closest','nativeBytesUnmodified':True,'physicallyViewed':True})
(r/'NATIVE_ALPHA_REVIEW.json').write_text(json.dumps({'schema':'cqc.native-alpha-review/1','uid':'core__fear','method':'Read-only Pillow/NumPy/SciPy alpha inspection; no output PNG edited or saved. Native alpha80 large-component threshold, opaque-edge48.','selectedBodySheets':alpha,'totalDistinctBodyPoses':72,'rejectedBodyAttempts':0,'absolute1to1Certified':False},indent=2)+'\n')
(r/'NATIVE_ATTEMPTS.json').write_text(json.dumps({'schema':'cqc.native-attempt-preservation/1','uid':'core__fear','bodyAttempts':attempts,'bodyAttemptCount':6,'selectedBodyAttemptCount':6,'rejectedBodyAttemptCount':0,'projectileAttemptCount':1,'sourcePreservation':'All7 native image_gen PNGs copied byte-exact; /workspace/generated_images originals retained. All prompts are exact executed structured args.'},indent=2)+'\n')
origins={'uid':'core__fear','origins':{},'limits':['Observed full-native pixel coordinates, not guessed engine offsets. First active source frame matches phaseMap active1 for shoot/charge/deploy; root/integrator independently derives crop/pivot/sourceScale and exact live contact.','Crossbow bolt mouth means leading rail/forward bow exit, not a firearm muzzle. No projectile is baked into native body PNG.']}
for action,pts in [('shoot',{'right':[763,59],'left':[402,65]}),('charge',{'right':[435,724],'left':[32,734]}),('deploy',{'right':[327,636],'left':[104,623]})]:
 origins['origins'][action]={}
 for side,pt in pts.items():
  k='c-'+side;f=next(f for f in files if f['key']==k);a=np.array(Image.open(f['source']).getchannel('A'));assert int(a[pt[1],pt[0]])>=80
  origins['origins'][action][side]={'action':action,'frame':1,'sheet':k,'point':pt,'basis':('Native physically viewed leading short Little Joe bolt rail exit active global cell1.' if action=='shoot' else 'Native physically viewed leading long William Tell bolt rail exit active global cell8.' if action=='charge' else 'Native physically viewed low left releasing fingertips snare placement active global cell4; optional trap origin, no mine artwork.'),'file':f['source'],'sha256':f['sha256'],'sourceHeightRecommendation':geometries[k]['recommendStandingSourceHeight'],'alphaAtPoint':int(a[pt[1],pt[0]])}
(r/'SOURCE_COMBAT_ORIGINS.json').write_text(json.dumps(origins,indent=2)+'\n')
layout={}
for name,sheet,indices,fps,loop in [('idle','a',[0,1],4,True),('walk','a',[2,3,4,5],9,True),('guard','a',[6,7],5,True),('crouch','a',[8,9],4,True),('jump','a',[10,11],6,False),('punch','b',[0,1,2],12,False),('heavy','b',[3,4,5],10,False),('low','b',[6,7,8],10,False),('hit','b',[9],0,False),('ko','b',[10,11],6,False),('shoot','c',[0,1,2],10,False),('deploy','c',[3,4,5],8,False),('optic','c',[6],0,False),('charge','c',[7,8,9],10,False),('recover','c',[10,11],5,False)]:layout[name]={'sheet':sheet,'indices':indices,'fps':fps,'loop':loop}
phase={a:{'startup':[0],'active':[1],'recovery':[2]} for a in ['punch','heavy','low','shoot','deploy','charge']};phase.update({'jump':{'startup':[0],'active':[0],'recovery':[1]},'optic':{'startup':[0],'active':[0],'recovery':[0]},'recover':{'startup':[0],'active':[1],'recovery':[1]}})
limits=[
'Closest supported original MGS3 PS2 model era illustrated adaptation, never absolute pixel/model/material/skeletal 1:1 certification. Official Konami color model and actual original PS2-era intro physically inspected and preserved.',
'Archive LP_Metal_Gear_Solid_3 was recorded2009/archived2010 before HD/Delta. Metadata explicitly identifies the Subsistence re-release for camera features; shared original PS2 Fear model/cutscene supports original2004 identity, not a claim that footage uses the first pressing.',
'Initial scout bare-chest reading of monochrome concept art is rejected by original model and actual PS2 cutscene. Selected body wears complete long-sleeve brown/olive military fatigues with dark irregular tiger stripes, black gloves/boots and central ribbed chest pouch.',
'Exact invisible rear harness seams, glove seam/individual fingertip constructions, camouflage spot coordinates, webbing strap lengths, buckles and bootlace topology are partly inferred at atlas scale, no absolute exact hidden-surface claim.',
'Original front/three-quarter source proves prominent olive anatomical RIGHT front-hip pouch and central black chest block. Native views independently generated, intended original-side gear retained; projection/occluded far-side fittings remain closest-supported rather than exact360-model certification.',
'Compact Little Joe is visually supported by official original model and large original promo render. Longer William Tell attack atlas is a restrained two-handed versus adaptation of original crossbow family, using longer rail/stock and broad braced limbs. Compressed front/side cutscene partially obscures exact rear stock, limb joints and which named crossbow is on screen; strict weapon-name-to-model 1:1 is not independently certified.',
'All72 body action keyframes are newly authored versus adaptations, not extracted original PS2 animations. Actual engine10move timings/costs/collision remain authoritative. Heavy and throw intentionally share the same 3 physically authored left reach/shove/capture frames; no extra3 poses or original CQC-technique claim.',
'Little Joe shoot C0..2 and William Tell charge C7..9 visibly distinct; first active frame1/global cell1 or8. C3..5 depict left-hand low snare placement, no explosive mine. C6 depicts visible opaque stealth activation hand-to-harness; actual engine applies cloak separately without pixel edits. C10..11 recover breath, not unsourced eating or magic.',
'Crossbow carries in anatomical RIGHT hand intended consistently; original front model visibly uses right. Far-side arm occlusion means not every authored pose certifies exclusive handedness. Original combat can involve both arms. No modern rifle, laser, magazine, Scope optic, firearm muzzle flash or glowing poison added.',
'No detached projectiles baked into body sheets; native bolt atlas separate. Original1352s physical bolt shows dark cylindrical shaft and short gray cross-type stabilizers; front tip is embedded and occluded so plain cone and exact fin count/backside are interpreted, not absolute extracted geometry.',
'Both facings are six independently generated distinct native PNGs. No image mirroring, resizing, recoloring, alpha manipulation or raster edits outside image_gen. Native PNGs preserved unchanged, Canvas crops/contours inspect source only.',
'Standing source height fixed per PNG using upright poses; low crouch/sweep/KO must never be stretched to upright230. Some padded rectangles overlap neighboring-row components but complete body components are separate; importer uses actual source-derived Canvas stencil, retaining exact original PNG bytes.',
'Producer review covers original-source art/native alpha and metadata only; independent integrator/runtime/mobile/move-phase checks remain required before production acceptance. Approval means closest_supported art, not automatic source model or live-game QA certificate.'
]
contract={'schema':'cqc.native-source-contract/1','uid':'core__fear','targetGame':'Metal Gear Solid 3: Snake Eater (2004), original PlayStation 2 model era','selectedCostume':'Original Cobra boss long-sleeve brown/olive tiger-striped fatigues, original chest block, gloves and boots','references':refs['references'],'fidelityStatus':'closest_supported','absolute1to1Certified':False,'sourceGeometry':geometries,'sourceCombatOrigins':str(r/'SOURCE_COMBAT_ORIGINS.json'),'limits':limits,'doNotTransfer':['MGS Delta remake model/face','shirtless bare-arm costume','Naked Snake rolled sleeves','The Sorrow sweater','modern rifle or firearm muzzle','detached baked arrows','invented permanent invisibility or flight']}
(r/'SOURCE_CONTRACT.json').write_text(json.dumps(contract,ensure_ascii=False,indent=2)+'\n')
prop=json.loads((r/'BOLT_NATIVE_GEOMETRY.json').read_text())
delivery={'schema':'cqc.native-combat-delivery/1','uid':'core__fear','name':'THE FEAR','game':'Metal Gear Solid 3: Snake Eater (2004), original PlayStation 2 model era','incarnation':'Original MGS3 Cobra Unit boss, Graniny Gorki South; original PS2 long-sleeve fatigues','selectedCostume':'original-ps2-cobra-camouflage-fatigues','basis':'The Fear : arbalètes originales, agilité arachnéenne et camouflage coûteux ; actions Versus bornées.','displayHeight':230,'coverage':'action-frames','facing':1,'mirror':False,'sourceFiles':files,'actionLayout':layout,'actionMap':{'light':'punch','heavy':'heavy','low':'low','throw':'heavy','special':'shoot','specialDown':'deploy','specialForward':'jump','specialBack':'optic','super':'charge','utility':'recover'},'phaseMap':phase,'review':{'status':'approved','fidelityStatus':'closest_supported','reviewer':'pass6_fear_native','reviewedAt':'2026-10-02','sourceKind':'original-game-capture','checks':{'identity':True,'costume':True,'equipment':True,'anatomicalSides':True,'singleFigure':True,'transparentBackground':True},'sources':refs['references'],'limits':limits,'absolute1to1Certified':False,'approvalScope':'Six physically inspected native body sheets,72 isolated authored original-model-era Fear poses and independent opposite view; limited original crossbow mechanical interpretations explicitly listed. No exact PS2 animation or live-game QA certification.'},'counts':{'selectedNativePngSheets':6,'totalPoseCells':72,'poseCellsPerSheet':12,'facings':2,'nativeBodyGenerationAttempts':6,'selectedWeaponPropAtlases':1},'sourceGeometry':geometries,'layouts':{k:str(r/'layouts'/f'{k}.json') for k in geometries},'sourceCombatOrigins':str(r/'SOURCE_COMBAT_ORIGINS.json'),'sourceContract':str(r/'SOURCE_CONTRACT.json'),'nativeAlphaReview':str(r/'NATIVE_ALPHA_REVIEW.json'),'projectileProps':{'geometry':str(r/'BOLT_NATIVE_GEOMETRY.json'),'source':prop['source'],'nativeOriginal':prop['nativeOriginal'],'sha256':prop['sha256'],'review':'Three physically viewed independent all-right short steel crossbow bolt views, source1352 original PS2 capture; shaft/stub stabilizers observed, embedded front tip interpreted.','displayWidthRecommendation':34,'fidelityStatus':'closest_supported','limits':prop['limits']}}
(r/'FINAL_DELIVERY.json').write_text(json.dumps(delivery,ensure_ascii=False,indent=2)+'\n')
seen={Path(x['file']).name for x in refs['references']}
referenceInventory=[]
for p in sorted((r/'references').iterdir()):
 if not p.is_file():continue
 data=p.read_bytes();e={'path':str(p),'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest(),'physicallyViewedAndSelected':p.name in seen}
 if p.suffix=='.png' and p.name.startswith('ps2-mgs3-'):
  q=re.match(r'ps2-mgs3-(\d+)-(\d+)s',p.stem);e.update({'sourceUrl':f'https://archive.org/download/LP_Metal_Gear_Solid_3/mgs3_{q[1]}.mp4','timeSeconds':int(q[2]),'captureMethod':'ffmpeg native first decoded PNG via HTTP proxy remote seek, no edits/no full download'})
 referenceInventory.append(e)
(r/'REFERENCE_FILE_INVENTORY.json').write_text(json.dumps({'schema':'cqc.reference-preservation/1','uid':'core__fear','files':referenceInventory,'researchLimits':['Fandom returned402, metalgear.wiki and IMFDB returned403, no blocked source accepted or policy bypass attempted. Google/Bing search HTML saved as unapproved discovery, not canonical art.','Original promo43/45/46/47/48 include other identities, retained for discovery only, never selected as Fear costume.','All irrelevant remote-seek captures preserved but not automatically certified physically-viewed canonical references. Only selected source records explicitly viewed and described in final contract.']},indent=2)+'\n')
manifest=[]
for p in sorted(r.rglob('*')):
 if p.is_file() and p.name!='PRESERVATION_FILE_MANIFEST.json':manifest.append({'path':p.relative_to(r).as_posix(),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
(r/'PRESERVATION_FILE_MANIFEST.json').write_text(json.dumps({'schema':'cqc.native-artist-preservation/1','uid':'core__fear','files':manifest,'fileCount':len(manifest),'totalBytes':sum(x['bytes'] for x in manifest),'handoffFrozen':True},indent=2)+'\n')
print(json.dumps({'finalDelivery':str(r/'FINAL_DELIVERY.json'),'finalSha256':hashlib.sha256((r/'FINAL_DELIVERY.json').read_bytes()).hexdigest(),'bodySheets':len(files),'poses':72,'props':1,'sourceGeometry':{k:v['recommendStandingSourceHeight'] for k,v in geometries.items()},'preservationFiles':len(manifest)},indent=2))
