from pathlib import Path
from PIL import Image
import hashlib,json,numpy as np
B=Path(__file__).parent
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(root,name,data):
 p=root/name;p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');return str(p)
selected={'armor':{'a-right':'A_RIGHT_01','a-left':'A_LEFT_01','b-right':'B_RIGHT_01','b-left':'B_LEFT_01','c-right':'C_RIGHT_03','c-left':'C_LEFT_01'},'beauty':{'a-right':'A_RIGHT_01','a-left':'A_LEFT_01','b-right':'B_RIGHT_01','b-left':'B_LEFT_01','c-right':'C_RIGHT_01','c-left':'C_LEFT_01'}}
layout={'idle':{'sheet':'a','indices':[0,1],'fps':4,'loop':True},'walk':{'sheet':'a','indices':[2,3,4,5],'fps':8,'loop':True},'guard':{'sheet':'a','indices':[6,7],'fps':4,'loop':True},'crouch':{'sheet':'a','indices':[8,9],'fps':4,'loop':True},'jump':{'sheet':'a','indices':[10,11],'fps':5,'loop':False},'punch':{'sheet':'b','indices':[0,1,2],'fps':12,'loop':False},'heavy':{'sheet':'b','indices':[3,4,5],'fps':10,'loop':False},'low':{'sheet':'b','indices':[6,7,8],'fps':10,'loop':False},'hit':{'sheet':'b','indices':[9],'fps':0,'loop':False},'ko':{'sheet':'b','indices':[10,11],'fps':6,'loop':False},'throw':{'sheet':'c','indices':[0,1],'fps':9,'loop':False},'shoot':{'sheet':'c','indices':[2,3,4],'fps':10,'loop':False},'deploy':{'sheet':'c','indices':[5,6,7],'fps':10,'loop':False},'recover':{'sheet':'c','indices':[8,9],'fps':5,'loop':False},'charge':{'sheet':'c','indices':[10,11],'fps':9,'loop':False}}
slots={'light':'punch','heavy':'heavy','low':'low','throw':'throw','special':'shoot','specialDown':'low','specialForward':'deploy','specialBack':'guard','super':'charge','utility':'recover'}
phase={k:{'startup':[0],'active':[1],'recovery':[2]}for k in ['punch','heavy','low','shoot','deploy']}
phase.update({k:{'startup':[0],'active':[1],'recovery':[0]}for k in ['throw','charge','guard']});phase['recover']={'startup':[0],'active':[1],'recovery':[1]};phase['walk']={'startup':[0],'active':[1,2],'recovery':[3]}
refcontract=json.loads((B/'REFERENCE_CONTRACT.json').read_text());browser=json.loads((B/'CANVAS_BROWSER_VERIFICATION.json').read_text());assert browser['status']=='passed'and browser['chartsCount']==12 and browser['distinctPoses']==144
proof={'schema':'cqc.pass8.native-pair-delivery-verification/1','status':'passed','checks':[],'nativePNGEdited':False,'runtimeWritten':False}
for kind,uid,name,height,times in [('armor','core__raging_raven','RAGING RAVEN',245,[23650,24000,24320]),('beauty','archive__raging_beauty','RAGING BEAUTY',225,[24400,24410,24420,24450])]:
 root=B/kind;body=json.loads((root/'BODY_GROUND_PIVOTS.json').read_text());source=[];poses=set()
 for key,attempt in selected[kind].items():
  p=root/'native-attempts'/(attempt+'.png');meta=json.loads((root/'metadata'/(attempt+'.result-summary.json')).read_text());d=json.loads((root/'layouts'/(key+'.json')).read_text());im=Image.open(p);a=np.array(im)[:,:,3]
  assert sha(p)==meta['sha256']==sha(meta['nativeOriginal'])==d['unchanged_source_sha256']
  assert im.mode=='RGBA'and len(d['cells'])==12 and int(np.count_nonzero(a[0,:]>80)+np.count_nonzero(a[-1,:]>80)+np.count_nonzero(a[:,0]>80)+np.count_nonzero(a[:,-1]>80))==0
  for c in d['cells']:
   rect=c['frame']['rect'];assert all(0<=v<=1 for v in c['frame']['pivot']);assert rect[0]>=0 and rect[1]>=0 and rect[0]+rect[2]<=im.width and rect[1]+rect[3]<=im.height
   poses.add((sha(p),tuple(rect)));proof['checks'].append({'name':uid+'-'+key+'-'+str(c['index'])+'-source-rect-pivot','passed':True})
   c['artistic_review']='approved-producer-physically-viewed-native-and-final-completeCanvas-contact; closest_supported original incarnation'
  lp=root/'layouts'/(key+'.json');lp.write_text(json.dumps(d,indent=2)+'\n')
  source.append({'key':key,'source':str(p),'nativeOriginal':meta['nativeOriginal'],'sha256':sha(p),'bytes':p.stat().st_size,'width':im.width,'height':im.height,'columns':4,'rows':3,'poseCount':12,'facing':1 if key.endswith('right') else -1,'mirror':False,'layout':str(lp),'inspection':str(root/'inspections'/(attempt+'.components.json')),'standingSourceHeight':body['standingSourceHeights'][key],'uprightSourceHeight':body['standingSourceHeights'][key],'observedBodyHeights':[c['bbox'][3]-c['bbox'][1]for c in d['cells']],'observedBodyPivots':body['observedBodyPivots'][key],'completeCanvasContact':str(root/'inspections'/('Canvas-complete-'+key+'.png'))})
 assert len(poses)==72 and len(set(r['sha256']for r in source))==6
 refs=[{**r,'incarnation':'Original Metal Gear Solid4: Guns of the Patriots,2008 PlayStation3','scope':'Physically viewed original armor and grenade-launcher/wing/helmet silhouette.' if kind=='armor' else 'Physically viewed original adult face/hair, opaque gray/black full-length suit and unarmed original Beauty gameplay.'}for r in refcontract['sources']if r['seconds']in times]
 limits=[
 'Target1:1 original2008 PS3 incarnation wherever original evidence supports it. These are newly authored detailed2D poses, not extracted original sprites/mesh or exact motion capture. fidelityStatus closest_supported; absolute1to1Certified false.',
 'Original longplay metadata identifies PS3 game and recording deposited2014 by Spazbo4/worldoflongplays. Actual native1280x720 frames inspected. Emulator versus physical-console framebuffer, calibrated source palette, hidden reverse-side geometry and exact tiny surface texture are not independently certified.',
 'Every left and right native sheet independently generated; no runtime mirroring or pixel editing. Fine seams, panel shading, source proportions and detailed face/gear fasteners vary between independent sheets; exact original texture coordinates and seam counts are not certified.',
 'All CQC shoves/punches, sweeps, defenses, jumps, reaction/KO, animation timing and fighting-game resource/damage/armor values are authored Versus adaptation. Original boss equipment/chase categories do not certify these numerical mechanics or every action as an extracted canonical move.',
 'The PNG inspector measures12 major isolated native alpha components per sheet. Some bounding rectangles contain neighbor pixels and therefore retain source-bound contour polygons. The twelve final actual Chromium Canvas charts were physically viewed: complete body/equipment, transparent composition and independent facing; originals remain byte-exact. HiddenRGB/low-alpha edge residuals are preserved rather than repainted.',
 'Per-sheet standing/uprightSourceHeight and foot/body pivots are measured from source alpha, with C neutral pose8 excluding opened-wing tops. displayHeight is authored Canvas presentation, not certified in-world centimetres. Broad wings never determine a pelvis alpha-centroid pivot.',
 ]
 if kind=='armor':limits.extend([
 'Source frames23650/24000 establish olive/gray mechanical helmet/black visor+respirator, segmented human exosuit, two broad hinged aircraft blades with pale external struts, mechanical jet-leg/boot category and original hand-carried drum-fed grenade launcher. No feather wings, exposed head, Vulcan Raven man or magical laser substituted.',
 'Launcher category and silhouette are source supported; exact MGL manufacturer/model, real-world capacity, all hidden grip/feed joints and source ballistic damage/jet forces are not certified by these frames. Author does not label an ordinary rifle as a grenade launcher or claim source-perfect rotary-drum topology.',
 'Grounded wings are folded/swept to preserve complete silhouette and room; opened-wing hover appears in C9/10/11. All mechanical details remain approximate closest_supported original-category art. No detached smoke/jet flame, projectile or magic effect embedded in body sheets.',
 'First C RIGHT attempt lost the sling-mounted launcher in active grab and is rejected; second restored it but clipped3 opaque wing-tip edge pixels and is rejected. Third image_gen redraw retains launcher in every pose and complete wing tips with zero opaque border pixels. Both rejects retained unchanged; no OC repurpose.',
 'C shoot is standing launcher aim; C deploy is grounded low launcher aim; C charge is hovering launcher aim. Actual source muzzle points are measured on first-active-frame1 (whole-sheet3/6/11). Runtime slot binding, collision and weapon handling remain root integration/QA responsibilities.'
 ])
 else:limits.extend([
 'Adult original Raging Beauty face/hair and opaque full-length cool gray/black high-collar suit are source supported. Fine glove/boot joins, under-layer panel seams, exact ponytail tie position and perfect original face likeness are closest_supported reconstruction. No exposed/nude alternate, armor or wings added.',
 'Beauty is unarmed: original gameplay establishes chase/grab category. C shoot/deploy/charge are abstract renderer action names for forward shove, low evasion and chase grab. They MUST NOT become a firearm, grenade, mind attack, beam or magical projectile. All attacks remain short physical reach/contact and authored simulation where original gameplay does not establish the particular move.',
 'No projectile launch marks exist for Beauty. Separate source-observed glove/palm contacts are retained for physical integration only, not ballistic origins. No borrowed weapon from the armored form.'
 ])
 review={'uid':uid,'incarnation':'Original2008 PS3 MGS4 '+name+', '+('armored boss form'if kind=='armor'else'fully clothed unarmored adult Beauty boss form'),'status':'approved','reviewer':'bb_raging_raven producer original-reference/native/final completeCanvas physical review','reviewedAt':'2026-10-02','sourceKind':'original-game-capture','target':'1:1 originalPS3 incarnation where viewed evidence supports it','fidelityStatus':'closest_supported','absolute1to1Certified':False,'checks':{'identity':True,'costume':True,'equipment':True,'anatomicalSides':True,'singleFigure':True,'transparentBackground':True},'sources':refs,'limits':limits,'completeContacts':[r['completeCanvasContact']for r in source]}
 write(root,'CANONICAL_REVIEW.json',review)
 producer={'uid':uid,'status':'approved','fidelityStatus':'closest_supported','reviewer':review['reviewer'],'sources':{r['key']:{'sha256':r['sha256'],'completeBodyAndEquipmentViewed':True,'nativePhysicallyViewed':True,'completeCanvasPhysicallyViewed':True,'sourceStandingHeight':r['standingSourceHeight'],'observedBodyPivots':r['observedBodyPivots'],'handsPhysicallyObserved':True,'muzzleApplicable':kind=='armor'}for r in source},'nativePNGEdited':False,'spritePixelsModified':False,'allSixNativeSheetsPhysicallyViewed':True,'allSixCompleteCanvasChartsPhysicallyViewed':True,'originalReferenceImagesPhysicallyViewed':True,'independentFacings':True,'mirror':False,'ownedBrowserClosed':browser['ownedBrowserClosed'],'ownedServerStopped':browser['ownedServerStopped'],'browserProof':str(B/'CANVAS_BROWSER_VERIFICATION.json'),'limits':limits}
 write(root,'PRODUCER_VISUAL_REVIEW.json',producer)
 origins={'schema':'cqc.pass8.native-source-combat-marks/1','uid':uid,'coordinateSystem':'Full untouched native PNG pixel x,y; frame=local action index, sourcePoseIndex=whole-sheet index. No resize/flip.','marks':{},'slotSourceGroups':{},'sourceIncarnation':review['incarnation']}
 if kind=='armor':
  for side,points in [('right',{'shoot':[1440,130],'deploy':[1103,545],'charge':[1418,830]}),('left',{'shoot':[1087,98],'deploy':[729,537],'charge':[1087,823]})]:
   row=next(r for r in source if r['key']=='c-'+side);im=Image.open(row['source']);origins['marks'][side]={}
   for action,point in points.items():
    index={'shoot':3,'deploy':6,'charge':11}[action];rgba=list(im.getpixel(tuple(point)));assert rgba[3]>80;ground=body['observedBodyPivots']['c-'+side][str(index)]
    origins['marks'][side][action]={'action':action,'frame':1,'sourcePoseIndex':index,'file':f'assets/combat-sprites/{uid}/c-{side}-v1.png','source':row['source'],'sha256':row['sha256'],'point':point,'pointRGBA':rgba,'bodyGroundPoint':ground,'standingSourceHeight':row['standingSourceHeight'],'suggestedWorldHeight':round((ground[1]-point[1])/row['standingSourceHeight']*height*1.12,4),'note':'Physically viewed actual original-category grenade-launcher front muzzle, alpha>80, first active source frame. Versus spawn geometry, not original-certified original-game pixel coordinates.'}
    proof['checks'].append({'name':uid+'-'+side+'-'+action+'-measured-active-muzzle','passed':True})
  origins['slotSourceGroups']={'special':'shoot','specialForward':'deploy','super':'charge'};origins['gameplayGroupToSourceAction']={'shoot':'shoot','lowShoot':'deploy','charge':'charge'}
 else:
  contacts={}
  for side,points in [('right',{'throw':[725,84],'shoot':[1414,86],'deploy':[1067,556],'charge':[1414,834]}),('left',{'throw':[354,100],'shoot':[1117,94],'deploy':[773,601],'charge':[1038,848]})]:
   row=next(r for r in source if r['key']=='c-'+side);im=Image.open(row['source']);contacts[side]={}
   for action,point in points.items():
    index={'throw':1,'shoot':3,'deploy':6,'charge':11}[action];rgba=list(im.getpixel(tuple(point)));assert rgba[3]>80
    contacts[side][action]={'action':action,'frame':1,'sourcePoseIndex':index,'source':row['source'],'sha256':row['sha256'],'point':point,'pointRGBA':rgba,'kind':'unarmed-glove-contact-only','projectileOrigin':False,'note':'Observed authored forward glove/palm reach in actual native source first-active frame. Never ballistic, magic or canonical-perfect damage position.'};proof['checks'].append({'name':uid+'-'+side+'-'+action+'-measured-unarmed-contact','passed':True})
  write(root,'SOURCE_UNARMED_CONTACTS.json',{'schema':'cqc.pass8.unarmed-source-contacts/1','uid':uid,'contacts':contacts,'projectileOrigins':{},'unarmed':True})
 write(root,'SOURCE_COMBAT_ORIGINS.json',origins)
 write(root,'SOURCE_AND_ACTION_CONTRACT.json',{'schema':'cqc.pass8.source-and-action-contract/1','uid':uid,'incarnation':review['incarnation'],'referenceContract':str(B/'REFERENCE_CONTRACT.json'),'actionLayout':layout,'actionMap':slots,'phaseMap':phase,'nativeSheets':6,'uniquePoses':72,'independentFacings':True,'mirror':False,'unarmed':kind=='beauty','phaseSemantics':{'shoot':'standing original-category grenade launcher aim'if kind=='armor'else'unarmed forward shove','deploy':'low grounded grenade launcher aim'if kind=='armor'else'unarmed low evasion/reach','charge':'hovering launcher brace/aim'if kind=='armor'else'unarmed forward chase grab'},'runtimeWritten':False,'limits':limits})
 attempts=[]
 for p in sorted((root/'native-attempts').glob('*.png')):
  meta=json.loads((root/'metadata'/(p.stem+'.result-summary.json')).read_text());status='approved-final'if p.stem in selected[kind].values()else'rejected-missing-launcher-on-grab'if p.stem=='C_RIGHT_01'else'rejected-three-pixel-clipped-wing-tip';attempts.append({'id':p.stem,'source':str(p),'nativeOriginal':meta['nativeOriginal'],'sha256':sha(p),'bytes':p.stat().st_size,'status':status,'physicallyViewed':True,'nativePNGEdited':False,'request':str(root/'metadata'/(p.stem+'.request.json'))})
 write(root,'NATIVE_PNG_INDEX.json',{'uid':uid,'attempts':attempts,'nativeImages':len(attempts),'approvedBodySheets':6,'uniquePoses':72,'rejectedAttempts':len(attempts)-6,'nativePNGEdited':False,'noRejectRepurposed':True})
 delivery={'schema':'cqc.native-combat-delivery/1','uid':uid,'name':name,'game':'Metal Gear Solid4: Guns of the Patriots (2008), original PlayStation3','incarnation':review['incarnation'],'selectedCostume':'olive-gray segmented armored exosuit, original visor/respirator helmet, pale-strutted broad aircraft wing blades, jet boots, original-category drum-fed grenade launcher'if kind=='armor'else'original adult Beauty cool gray/black opaque full-length high-collar bodysuit and long tied black hair, unarmed','basis':refcontract['armorMechanics'if kind=='armor'else'beautyMechanics'],'displayHeight':height,'coverage':'action-frames','facing':1,'mirror':False,'sourceFiles':source,'actionLayout':layout,'actionMap':slots,'phaseMap':phase,'review':review,'nativeSourceCombatOrigins':str(root/'SOURCE_COMBAT_ORIGINS.json'),'producerVisualReview':str(root/'PRODUCER_VISUAL_REVIEW.json'),'bodyGroundPivots':str(root/'BODY_GROUND_PIVOTS.json'),'unarmedContacts':str(root/'SOURCE_UNARMED_CONTACTS.json')if kind=='beauty'else None,'limits':limits}
 write(root,'FINAL_DELIVERY.json',delivery)
 proof['checks'].append({'name':uid+'-six-distinct-native-sources-and72unique-layout-poses','passed':True})
write(B,'DELIVERY_VERIFICATION.json',{**proof,'assertions':len(proof['checks']),'uids':['core__raging_raven','archive__raging_beauty'],'selectedNativePNG':12,'uniquePoses':144,'allNativeAttempts':14,'rejectedPreserved':2,'finalDeliverySHA256':{kind:sha(B/kind/'FINAL_DELIVERY.json')for kind in selected}})
write(B,'REFERENCE_PRESERVATION_INDEX.json',{'schema':'cqc.pass8.reference-preservation/1','files':[{'path':str(p),'sha256':sha(p),'bytes':p.stat().st_size}for p in sorted((B/'references').iterdir())if p.is_file()],'totalBytes':sum(p.stat().st_size for p in (B/'references').iterdir()if p.is_file()),'fullVideosDownloaded':0,'originalFramesPixelsEdited':False})
print(json.dumps({'status':'passed','assertions':len(proof['checks']),'deliveries':[str(B/k/'FINAL_DELIVERY.json')for k in selected],'finalSHA':{kind:sha(B/kind/'FINAL_DELIVERY.json')for kind in selected}},indent=2))
