import json,pathlib,hashlib
B=pathlib.Path(__file__).parent
refs=B/'references'
video='https://archive.org/download/PS3_Longplay_081_Metal_Gear_Solid_4/PS3_Longplay_081_Metal_Gear_Solid_4.mkv'
rows=[]
for p in sorted(refs.glob('*.png')):
 t=int(p.stem.split('-')[-1][:-1]);role='original timeline search, not canonical selected proof'
 if t in [23650,24000,24320]:role='armor canonical selected original PS3 reference'
 if t in [24400,24410,24420,24450]:role='Beauty canonical selected original PS3 reference'
 rows.append({'file':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size,'url':video+'#t='+str(t),'seconds':t,'sourceKind':'original-game-capture','role':role,'viewed':True})
(B/'REFERENCE_CONTRACT.json').write_text(json.dumps({'schema':'cqc.pass8.original-reference-contract/1','uids':['core__raging_raven','archive__raging_beauty'],'game':'Original Metal Gear Solid4 PS3 2008','sources':rows,'metadata':str(refs/'original-ps3-archive-metadata.json'),'sourceLimit':'Longplay metadata deposited2014 identifies PS3 game. Hardware framebuffer and exact original texture/hidden geometry not certified. Native2D poses authored adaptation, closest_supported, absolute1to1Certified false.','armorMechanics':'Metal flight wings, armored jet leg/back assembly, source-visible handheld grenade launcher category; exact model, ballistic tuning/jet forces unknown. No magical laser, spirits or ordinary rifle substituted.','beautyMechanics':'Adult human opaque gray/black long sleeve full-leg bodysuit, long tied black hair; original chase/grab category only. No guns, armor, gore or nude/sexual depiction. Fighting-game guard, shove, low evasion, stumble are authored Versus adaptation.'},indent=2)+'\n')
armor="""RAGING RAVEN from the original2008 PlayStation3 Metal Gear Solid4. Reproduce the ORIGINAL armor visible in supplied game frames: olive-gray metallic human exosuit, rounded olive dark opaque helmet with black wraparound visor and round side disks, black lower respirator face mask, square dark/tan harness and layered chest plates, thick segmented gray thighs/greaves, large blunt mechanical jet boots; two enormous hinged dark olive aircraft wing blades fixed to upper back, leading sharp flat triangular panels and pale external support struts, original source handheld long rotary-drum grenade launcher carried by anatomicalRIGHT armored hand with anatomicalLEFT support. This is NOT Vulcan Raven; no bald man, bird feathers, exposed woman's head, magic, laser, pistol or ordinary rifle. Keep large wings attached, complete wing tips and complete boots inside each cell, folded/swept as necessary in grounded poses. Source hidden geometry can be reasonably reconstructed; preserve original category and silhouette."""
beauty="""RAGING BEAUTY from original2008 PS3 Metal Gear Solid4, adult Japanese/East Asian woman, same recognisable face as close-up original refs, almond brown eyes, black side parted long bangs and long straight black hair tied back into long ponytail, no blonde or short haircut. FULLY CLOTHED in opaque original cool medium-gray full-length long-sleeve high-collar tactical body suit with black/dark shoulder/chest side/outer-thigh panels, muted light piping and integrated gray glove/boot silhouettes. Match original panels as references support. Completely opaque clothing, no exposed torso, no translucent or nude depiction, no cleavage, no erotic poses. Unarmed, no armor, no wings, no guns, no robot. Neutral serious tense game chase/defense movement."""
common="""Create one native TRANSPARENT PNG sprite animation sheet4 columns×3 rows, EXACTLY12 DIFFERENT full isolated complete single-character poses in row-major order. Detailed realistic hand-painted2D game sprite art with controlled dark outline, crisp canonical materials and face, same character/costume/colors/proportions in every pose. No scene, no floor, no shadows cast outside character, no text, no labels, no boxes, no frame dividers, no glow or motion trails. Transparent blank generous gutters between all poses; figure and all gear must fit each own cell, no overlapping neighbors or clipped hair/head/feet/wing/weapon tips. Anatomical limbs complete, two arms/two legs only. Same scale within standing frames, sufficient margins on all edges. This is newly drawn facing requested direction, NOT mirrored image; anatomical clothing/hands stay the original sides."""
poses={
'a':'Row1: idle relaxed tense standing1; idle subtle weight shift2; walk forward left step3; walk forward right step4. Row2: walk forward passing step5; walk forward extended step6; guarded forearms close chest7; guarded forearms braced angled8. Row3: crouch down9; deep cautious crouch10; jump windup airborne knees bent11; jump apex forward reach12. No attacks except neutral guarding.',
'b':'Row1: short arm shove/punch startup1; shove contact arm extended2; recovering shove3; broad armored-arm/body shove startup4. Row2: broad body shove contact5; settling back6; low crouching leg sweep preparation7; low leg sweep active8. Row3: low sweep recovering9; recoil non-graphic hit stagger10; falling sideways non-graphic11; lying side on ground clothed intact12. No blood or injuries. For armored form keep wings/launcher attached, folded enough for all twelve complete figures.',
'c_armor':'Row1: close-range forward grab startup1; forward grab finish2; GRENADE LAUNCHER brace preparation3; GRENADE LAUNCHER actively aimed horizontally toward opponent4. Row2: GRENADE LAUNCHER recoil/settle5; LOW crouched grenade launcher brace6; LOW crouched launcher horizontally aimed7; LOW launcher recovery8. Row3: folded-wing cooling pause9; raised-wing ready reset10; hovering jet-leg launcher windup11; short hovering launcher actively aimed forward12. NO actual projectiles, muzzle flash, smoke, flame or floating loose effects. Horizontal original grenade-launcher barrel clearly visible in active poses.',
'c_beauty':'Row1: forward two-handed grab startup1; forward grab active reaching2; tense unarmed reaching preparation3; unarmed forward two-hand shove/contact4. Row2: unarmed shove recovery5; low evasion windup6; crouching evasion arms forward7; crouching evasion recovery8. Row3: exhausted standing recovery9; recovering standing guard10; forward chase grab windup11; forward forceful reaching grab active12. No weapon, no fireball, no magic, no imagined projectile. Existing gameplay names shoot/deploy/charge are abstract slots for these unarmed poses; do NOT illustrate them as shooting.'}
for kind,identity,ts in [('armor',armor,[23650,24000,24320]),('beauty',beauty,[24400,24420,24450])]:
 for sheet in 'abc':
  for side in ['RIGHT','LEFT']:
   order='c_'+kind if sheet=='c' else sheet
   prompt=common+' '+identity+' EVERY pose faces image '+side+' (nose/chest approach and feet travel toward '+side+'), readable three-quarter side view, never facing the opposite direction. '+poses[order]
   args={'prompt':prompt,'transparent_background':True,'referenced_image_paths':[str(refs/f'original-ps3-frame-{t}s.png') for t in ts]}
   (B/kind/'metadata'/f'{sheet.upper()}_{side}_01.request.json').write_text(json.dumps(args,indent=2)+'\n')
print('Original reference contract and twelve generation requests prepared.')
