/* Source data audit only: no browser, fetch, decoding, generation, APP write or gameplay test. */
import fs from'node:fs';import path from'node:path';import vm from'node:vm';import crypto from'node:crypto';
const app='/tmp/cqc-pass19-application/public/cqc',out='/workspace/cqc-pass19-backlog-final',html=fs.readFileSync(app+'/modules/unified-versus-v055.html','utf8'),pins=[],root={URL,console,addEventListener(){},localStorage:{getItem(){return null;},setItem(){throw Error('Source audit must not persist state');}}};root.globalThis=root;root.window=root;vm.createContext(root);
const allowed=/sprite-catalog|cqc-sprite-catalog|machine-parts-renderer|machine-parts-catalog|machine-catalog|gekko-catalog|gekko-poses|gekko-install|machine-source-points|machine-bridge|incarnation-scale|costume-parts|pixel-style|sprite-renderer|costume-catalog|acid-native-costumes|pass17-costumes\.js|costume-request-data|pass19-costumes\.js|world-scale|machine-costume-routing|retro-presentations|canonical-appearances|original-costumes|native-tuxedo-costumes|roster-additions|combat-additions|roster-native|native-wardrobe-index/;
for(const match of html.matchAll(/<script[^>]+src="([^" ]+)"/g)){const file=path.resolve(app+'/modules',match[1]);if(!allowed.test(file)||/stage|vfx|projectile/.test(file))continue;const bytes=fs.readFileSync(file);pins.push({path:file,bytes:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')});vm.runInContext(bytes.toString(),root,{filename:file});if(file.endsWith('/cqc-pass19-retro-presentations.js'))root.CQC_PASS19_MACHINE_PIXEL_STYLE.registerAll();}
const fighters=JSON.parse(fs.readFileSync(out+'/current-fighters-source-extracted-v1.json','utf8')),baseline=fighters.filter(f=>!f.uid.startsWith('pass19__'));const installed=root.CQC_PASS19_ROSTER_NATIVE.install(baseline);
const compact=o=>({id:o.id,family:o.family||null,label:o.label,provenance:o.provenance||null,presentation:o.presentation||null,assetReview:o.assetReview||null,physicalExtent:o.physicalExtent||null,machinePresentation:o.machinePresentation||null,sourceUID:o.sprite?.costumeConcept?.sourceUID||o.provenance?.sourceUID||null,concept:o.sprite?.costumeConcept||null,spriteReview:o.sprite?.review||null,renderStyle:o.sprite?.renderStyle||null,pixelArt:!!o.sprite?.pixelArt,files:o.sprite?[...new Map([...Object.values(o.sprite.actions||{}),...Object.values(o.sprite.oppositeActions||{})].flatMap(a=>a.frames).map(f=>[f.file,{file:f.file,sha256:f.sha256}])).values()]:[]});
const records=Object.fromEntries(Object.entries(root.CQC_PASS19_COSTUME_REQUEST_DATA.entries).map(([uid,e])=>[uid,{...e,actualRequestStatuses:e.requests.map(r=>root.CQC_PASS19_COSTUMES.requestFor(uid,r.id)),actualOptions:(root.CQC_COMBAT_COSTUME_CATALOG.entries[uid]?.options||[]).filter(o=>o.id!=='original').map(compact),height:root.CQC_PASS19_WORLD_SCALE.records[uid]||null}]));
const data={schema:'cqc.read-only-runtime-costume-source-audit/1',sourceHTMLSHA256:crypto.createHash('sha256').update(Buffer.from(html)).digest('hex'),scope:'Actual script data, source registration and requestFor code evaluated read-only without Image/fetch/DOM. No synthetic art, browser or gameplay test; previously passed receipts separately establish physical/runtime validation.',pins,rosterInstallResult:installed,sourceBodies:Object.fromEntries(Object.entries(root.CQC_COMBAT_SPRITE_CATALOG.entries).map(([uid,e])=>[uid,{uid,renderStyle:e.renderStyle,review:e.review,game:e.game,incarnation:e.incarnation,displayHeight:e.displayHeight}])),scopedHeights:root.CQC_PASS19_COSTUME_HEIGHTS||{},recordCount:Object.keys(records).length,baselineFighterCount:fighters.length,registry:root.CQC_PASS19_ROSTER_ADDITIONS.registry,records,lazyIndex:root.CQC_NATIVE_WARDROBE_INDEX,machineCatalog:Object.fromEntries(Object.entries(root.CQC_PASS18_MACHINE_CATALOG?.entries||{}).map(([uid,e])=>[uid,{uid,...e}])),heights:root.CQC_PASS19_WORLD_SCALE.audit()};
const target=out+'/RUNTIME_COSTUME_SOURCE_READ_ACTUAL_V2.json';fs.writeFileSync(target,JSON.stringify(data,null,2)+'\n',{flag:'wx',mode:0o400});const counts={};for(const e of Object.values(records))for(const o of e.actualOptions){const k=o.pixelArt||o.machinePresentation?'derived-pixel':o.family||'legacy';counts[k]=(counts[k]||0)+1;}console.log(JSON.stringify({path:target,records:data.recordCount,installed:installed.added,pending:installed.pending,counts}));
