from pathlib import Path
import hashlib,json,re,datetime
R=Path('/workspace/cqc-game-working/cqc-versus-v056'); W=Path('/workspace')
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def source(path,url,observation):
 p=Path(path);return dict(path=str(p),url=url,sha256=sha(p),bytes=p.stat().st_size,physicallyViewed=True,observation=observation)
sources=[
 source('/workspace/cqc-pass6-generation/pain/references/konami-pain-native-decoded.png','https://www.konami.com/mg/archive/mgs3/english/pic/chara_pain_pic.gif','Official original-model body: black first-phase balaclava, long dark sleeves/gloves/boots, ochre vest and rear equipment, actual hornets; no physical gun in hands. This decoded inspection copy retains original-model palette.'),
 source('/workspace/cqc-pass6-generation/pain/references/ps2-pain-10964.png','https://archive.org/download/PS2_Longplay-001-Metal_Gear_Solid_3-Snake_Eater/PS2_Longplay-001-Metal_Gear_Solid_3-Snake_Eater.mp4#t=10964','Original Snake Eater PS2 masked phase, original sleeves/ochre front/hand gesture; broad body consistency corroboration. No claim this still proves exact cinematic finisher, timer or all combat powers.'),
 source('/workspace/cqc-pass6-generation/fear/references/konami-fear.gif','https://www.konami.com/mg/archive/mgs3/english/pic/chara_fear_pic.gif','Official original model: uniform with long sleeves, chest equipment, small crossbow held in anatomical right hand. Little Joe/William Tell names exist in historical game profile; this still alone does not certify exclusive name-to-detailed-geometry association for both animation groups.'),
 source('/workspace/cqc-pass6-generation/end/references/konami-end.gif','https://www.konami.com/mg/archive/mgs3/english/pic/chara_end_pic.gif','Official original model: elderly ghillie figure, bare hands, conventional scoped wood-stock rifle and left-shoulder green parrot. No rail weapon or material laser fitting appears.'),
 source('/workspace/cqc-pass6-generation/fury/references/konami-fury.gif','https://www.konami.com/mg/archive/mgs3/english/pic/chara_fury_pic.gif','Official original model: closed dark Soviet spacesuit/bronze visor, hose-connected flamethrower and rear propulsion boom. No continuously free-flying gameplay claim established by still.'),
 source('/workspace/cqc-pass4-narrative-art/references/dirtyduck-original-sprite.webp','https://thecodex.wiki/images/6/61/Dirty_Duck.webp','Original1987 MSX2 Coward Duck small olive human sprite, ordinary boomerang silhouette; no Slasher Hawk bird equipment transferred.'),
 source('/workspace/cqc-pass4-narrative-art/references/dirtyduck-room-0504.png','https://lparchive.org/Metal-Gear-1-2/Update%2011/45-Metal_Gear_0504.png','Original Coward Duck named boss scene, three hostages and original brown tiled room. Player HUD gun belongs to Snake, not Coward Duck.'),
 source('/workspace/cqc-pass4-narrative-art/references/mercenaries-original-manual.jpg','https://lparchive.org/Metal-Gear-1-2/Update%2011/58-wSLfj.jpg','Original mercenary-group illustration: fifth figure from left holds ordinary boomerang. Monochrome and group art are equipment-category evidence, not color authority.'),
 source('/workspace/cqc-pass6-narrative-art/references/red-blaster-msx2-original-sprite.webp','https://thecodex.wiki/images/d/d0/Red_Blaster.webp','Original tiny green Red Blaster sprite: exact weapon/face/hardware not resolvable, no literal-red Fatman suit imported.'),
 source('/workspace/cqc-pass6-narrative-art/references/lp26-30-Metal_Gear_2_0470.png','https://lparchive.org/Metal-Gear-1-2/Update%2026/30-Metal_Gear_2_0470.png','Original RED-B dialogue names grenades; small green boss on elevated covered gallery with olive-yellow ribbed walls/elevator. Player HUD handgun belongs to Snake.'),
 source('/workspace/cqc-pass6-narrative-art/references/lp26-33-Metal_Gear_2_0471.png','https://lparchive.org/Metal-Gear-1-2/Update%2026/33-Metal_Gear_2_0471.png','Original Red Blaster room with crossed white immobilizing tripwire lines. Detailed grenade-launcher real-world model cannot be identified.'),
 source('/workspace/cqc-pass6-narrative-art/references/original1990-msx2-japanese-manual-text.pdf','https://archive.org/download/metal-gear-2-solid-snake-manual-original/MetalGear%202%20-%20SolidSnake%20Manual%20%28Original%29_text.pdf','Original1990 MSX2 Japanese manual, printed page42 rendered and physically viewed: SPETSNAZ/explosive sabotage and grenade mastery. Tiny source sprites, actual room captures and this manual ground equipment category, not exact fuse48 or reserve10.')]
html=(R/'modules/unified-versus-v055.html').read_text(); scripts=[m.group(1) for m in re.finditer(r'<script(?:\s[^>]*)?>(.*?)</script>',html,re.S)]
engine=next(s for s in scripts if s.startswith('/* CQC Versus 0.48'));engine_sha=hashlib.sha256(engine.encode()).hexdigest();assert engine_sha=='197acd7da230bf479a68d37ff409801c0d4390d001a98b4c1451075be55d2d51'
baseline=json.loads((W/'cqc-delivered-pass5-baseline-files.json').read_text()); old={r['path']:r for r in baseline}
raw=[]
for name in ['data/unified-roster-v053.json','data/finishers-v053.json']:
 p=R/name;assert sha(p)==old[name]['sha256'];raw.append(dict(path=str(p),sha256=sha(p),pass5ByteExact=True))
hook_finishers='window.CQC_PASS6_COMBAT_FIDELITY?.applyFinishers(FIN46,FIGHTERS);' in html
hook_pose='aPose=window.CQC_PASS6_COMBAT_FIDELITY?.finisherPose(winner.f.uid,sc.fin,phase,aPose,t)||aPose;' in html
fin_draw=html[html.index('function drawFinisher46()'):html.index('function openFinishers46(',html.index('function drawFinisher46()'))]
fallbacks=fin_draw.count('if(!nativeFinish&&');assert hook_finishers and hook_pose and fallbacks==3
snap=json.loads((W/'cqc-pass6-combat-runtime-review-snapshot.json').read_text());qa=json.loads((W/'cqc-pass6-finisher-runtime-review-qa.json').read_text());assert qa['status']=='passed' and qa['assertions']==827
by={p['uid']:p for p in snap['profiles']}
assert not any('Laser' in x for x in by['core__end']['counterplay'])
assert 'mine' not in by['core__fear']['moves']['specialDown']['counterplay']
assert by['core__fear']['counterplay']==[by['core__fear']['moves'][s]['counterplay'] for s in ['special','specialDown','specialForward','specialBack']]
assert by['core__end']['counterplay']==[by['core__end']['moves'][s]['counterplay'] for s in ['special','specialDown','specialForward','specialBack']]
uids=['core__pain','core__fear','core__end','core__fury','core__dirtyduck','core__redblaster_mg2'];assert snap['reviewedUIDs']==uids
allsource=[]
for uid in uids:
 for f in by[uid]['finishers']['finishers']:
  assert f['canonical'] is False and f['evidence']=='adaptation'
  assert all(any(n==m['name'] for m in by[uid]['moves'].values()) for n in f['sourceMoves'])
  allsource.append(dict(uid=uid,id=f['id'],name=f['name'],sourceMoves=f['sourceMoves'],phases=f['phases'],canonical=False,evidence='adaptation'))
helpers=['src/cqc-pass6-combat-fidelity.js','src/cqc-pass6-prop-art.js','src/cqc-pass6-prop-data.js','src/cqc-pass6-native-origins.js']
result=dict(schema='cqc.pass6.independent-combat-source-review/1',status='accepted_closest_supported',reviewer='pass6_narratives / independent runtime/source follow-up',reviewDate='2026-10-02',createdAtUtc=datetime.datetime.now(datetime.timezone.utc).isoformat(),fidelityTarget='1:1',fidelityResult='closest_supported',absolute1to1Certified=False,reviewedUIDs=uids,scope='Actual production helper API and HTML hooks, original physical equipment references, all24 targeted UI sourceMoves. This report is not a browser screenshot or full art-contact audit.',reviewedProductionFiles=[dict(path=str(R/n),sha256=sha(R/n)) for n in [*helpers,'modules/unified-versus-v055.html']],rawHistoricalCatalogs=raw,inlinePhysicsEngine=dict(sha256=engine_sha,pass5ByteExact=True),physicalExternalSources=sources,externalTextSupplement=dict(path='/workspace/cqc-pass6-narrative-art/references/lp-update-26.html',url='https://lparchive.org/Metal-Gear-1-2/Update%2026/',sha256=sha('/workspace/cqc-pass6-narrative-art/references/lp-update-26.html'),kind='Preserved original-game LP transcript, secondary to screenshots/manual',observations='Lines160–165 attribute grenade launcher and crossed immobilizing traps to original codec; portraitGIF first-frame alone does not prove text. Exact launcher model remains unknown.'),findings=[
 dict(uid='core__pain',status='accepted',original='Masked first-phase body and hornets',runtime='Forward name Essaim rapide — adaptation; hands/swarm rather than material firearm. Family changed psychic→ballistic, with physical CQC back conclusion. Old lift/orbit/mental-force sequences removed from all4 current finishers; no unmasked Bullet Bee move label remains.',limits='Poison, bounded homing, gauge, shield count/timing and authored conclusions are versus adaptations; former phase2 Bullet Bee mention exists only as explicit exclusion, never a represented current move.'),
 dict(uid='core__fear',status='accepted',original='Two crossbow aliases, uniform, camouflage/agility equipment category',runtime='Separate shoot/charge animation groups/anchors; existing Little Joe and William Tell aliases preserved. Trap counterplay now dispositif rather than inherited mine and global UI array refreshed.',limits='Original model/captures do not certify exclusive detailed geometry-to-name pairing of partly occluded crossbows. Producer sprite review keeps this limitation; group separation is authored renderer routing, not absolute weapon-model identification.'),
 dict(uid='core__end',status='accepted',original='Original scoped wood-stock Mosin and ghillie model',runtime='Super tag precision/cost1/meter50, finite reserve5; old rail tag removed. Special and global counterplay now refer to versus aiming marker, no inherited material Laser label. All4finisher sourceMoves refreshed to current Mosin-Nagant — dernier souffle name.',limits='Damage, reserve5/timing, line marker, photosynthesis budget and finisher choreography are explicit versus adaptations.'),
 dict(uid='core__fury',status='accepted',original='Closed spacesuit, hose-connected flamethrower, propulsion boom',runtime='Visual/combat weapon flamethrower; original fire/propulsion categories retained. No extra model or endless flight created; sourceMoves coherent on all4finishers.',limits='Jet/trap shapes, heat/gauge, damage/timing, finite propulsion and conclusion choreography are versus adaptations.'),
 dict(uid='core__dirtyduck',status='accepted',original='Original1987 Coward Duck/Dirty Duck with boomerang',runtime='Role Boomerangs aller-retour et repli; no hawk projectile transfer. Existing move/finisher sourceMoves retained.',limits='Boomerang timing, contact choreography and numerical stamina remain gameplay adaptations. Original basis explicitly excludes unrelated Slasher Hawk bird.'),
 dict(uid='core__redblaster_mg2',status='accepted',original='Original1990 grenades from covered gallery and crossed immobilizing tripwires',runtime='Special conventional grenade arc/fuse48; forward1ammo grenade520; super3ammo+meter50/count3; Down damage0/snare/slow/duration420/max2, no remoteOnly or detonate move. All4finishers replace plant/remote charges with visible grenade arcs or harmless wire staging.',limits='Grenade-launcher exact model, fuse48, reserve10, trajectories, destructible deployed wire and timing are versus adaptations. Direct wire damage is0 outside guard; unchanged engine imposes minimum1PV chip under successful guard, including crouching guard. No explosive damage mechanic is assigned to wire; UI promises no explosion, not absolute zero chip damage. Slow status is engine-capped140frames while trap lifetime420frames is independent.'),
],resolvedUiFindings=[dict(uid='core__end',finding='Global counterplay retained stale Laser label',resolution='Actual helper recomputes4current counterplay strings from corrected move definitions',verified=True),dict(uid='core__fear',finding='Snare counterplay inherited mine wording',resolution='Actual helper uses dispositif and recomputes4current counterplay strings',verified=True)],finisherHooks=dict(applyAfterCanonicalViper=hook_finishers,attackerNativePoseHook=hook_pose,threeGenericFxBranchesGuarded=fallbacks,propHook='CQC_PASS6_PROP_ART.drawFinisher',nonTargetFallbackRetained=True,feet='Pain phases no lift/orbit; old generic levitation condition never selected for new2UIDfinisher arrays. Physical CQC final fall remains authored staging.'),all24FinisherSourceMoves=allsource,meaningfulRuntimeMetadataQa=dict(path=str(W/'cqc-pass6-finisher-runtime-review-qa.json'),sha256=sha(W/'cqc-pass6-finisher-runtime-review-qa.json'),status='passed',assertions=827,unchangedOtherProfiles=348,all24FinisherIdsCommandsDurationsTonesRetained=True,all24RemainCanonicalFalseAdaptation=True,idempotenceVerified=True,familyCounts=snap['familyCounts'],countsDefinition='Profile family counts sum354; finisher catalogue still1416. Counts computed from actual helper applied alone; canonical Viper earlier hook retains its separate target.'),preservation=dict(noProductionWritesByReviewer=True,noArtistArtifactsChanged=True,proposalPath=str(W/'cqc-pass6-finisher-proposal.js'),proposalSha256=sha(W/'cqc-pass6-finisher-proposal.js'),runtimeSnapshotPath=str(W/'cqc-pass6-combat-runtime-review-snapshot.json'),runtimeSnapshotSha256=sha(W/'cqc-pass6-combat-runtime-review-snapshot.json')),honestLimits=['No new sprite PNGs or source assets edited by reviewer. Independent original physical source check covers equipment categories and current metadata; root owns final PNG contact/native origin/browser/end-to-end verification.','Authored finisher props/positions/scenes are cinematic versus staging after victory, not literal original-game animations or a guarantee of collision simulation during finisher playback.','Original LP YouTube Red Blaster movie was403blocked; saved failure is preserved. No precise original fuse duration was inferred or certified.','Three AC!D-related roof/ceiling projections are separately reviewed stage adaptations; original top-down screens do not establish unseen ceiling geometry. This combat-source report does not certify those hidden surfaces.','All revised conclusions remain canonical:false/evidence:adaptation; no rejected art promoted to an additional OC.'])
out=W/'cqc-pass6-combat-source-review.json';assert not out.exists();out.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n');print(json.dumps(dict(status=result['status'],path=str(out),bytes=out.stat().st_size,sha256=sha(out),runtimeQaAssertions=827,allTargetedFinishers=24),indent=2))
